Repair-Player.ArtificialHealth
Exiled-Team/EXILED pull request #1008
Opened 2022-01-08 22:06 UTC by louis1706

Fixes #931

2022-01-08 22:37 UTC, joker-119 commented
Can't .First() cause a nullref if they don't have any active processes though?

2022-01-08 22:38 UTC, joker-119 commented
Also change the target branch to dev :anger:

2022-01-08 22:44 UTC, louis1706 commented
> Can't .First() cause a nullref if they don't have any active processes though?

2022-01-08 23:21 UTC, joker-119 approved these changes

2022-01-09 02:45 UTC, sanyae2439 requested changes

2022-01-09 02:45 UTC, sanyae2439 commented on Exiled.API/Features/Player.cs
> +                if (ActiveArtificialHealthProcesses.Count() < 1)
Use Any().

2022-01-10 23:31 UTC, merged