Fix Pickup Locking when ev.IsAllowed = false
Exiled-Team/EXILED pull request #1029
Opened 2022-01-14 23:06 UTC by rayzerbrain

**PickingUpItemEventArgs.IsAllowed = false** caused the Pickup to permanently lock for some reason. I just made it so it spawned a replacement pickup with the same serial and everything. Tested by myself but could be problems I'm unaware of.

~~Not Invalid IL code I promise~~

2022-01-15 00:09 UTC, NaoUnderscore commented
"Avoiding the problem" is not a valid solution.
I'm pretty sure you're gonna break CustomItems.
Also, this could lead to many issues, and since you also said "but could be problems I'm unaware of" you already know that this "solution" is gonna lead to many issues instead.
Before approving it I need to make sure it doesn't break anything, although I'm sure it's not the right way to cope this problem.
I'd like to handle this issue, because I'm sure that I can fix it, but as I already said before, this is not the right way to solve this issue.

2022-01-15 00:42 UTC, rayzerbrain commented
That makes sense to me, I'll try poking around a bit more for a better solution, unless you want to take care of it instead?

2022-01-15 06:40 UTC, rayzerbrain commented
Don't ask me why this works, but it does.

It seems redundant but I did lots of testing and this is the easiest way it seems to work.

2022-01-15 07:13 UTC, NaoUnderscore requested changes

2022-01-15 07:13 UTC, NaoUnderscore commented on Exiled.Events/Patches/Events/Player/PickingUpItem.cs
> +            LocalBuilder syncInfo = generator.DeclareLocal(typeof(PickupSyncInfo));
Remove it

2022-01-15 17:41 UTC, SebasCapo commented
When testing these changes, make sure they don't cause #886 to happen again! 😅

2022-01-15 18:08 UTC, rayzerbrain commented
That's actually the exact issue I'm trying to fix. Either the NW code changed in the past month to reintroduce the bug or it's only happening in specific situations or something. Can you verify that you currently do or do not have this issue?

2022-01-16 00:10 UTC, joker-119 commented
The description of your fix and what the code actually does do not match. You're not spawning a new item here anywhere.

2022-01-16 00:29 UTC, rayzerbrain commented
> The description of your fix and what the code actually does do not match. You're not spawning a new item here anywhere.

That was my previous method of fixing the problem. My new solution is monkeying around with the PickupBase info, which somehow works

2022-01-17 03:59 UTC, joker-119 commented
My point was, you should update your first comment to reflect what's actually going on since they no longer match.

2022-01-17 03:59 UTC, joker-119 approved these changes

2022-01-17 04:58 UTC, NaoUnderscore approved these changes

2022-01-17 08:52 UTC, merged