Integrate Scp-2176
Exiled-Team/EXILED pull request #1051
Opened 2022-01-18 23:52 UTC by rayzerbrain

2022-01-19 09:39 UTC, NaoUnderscore requested changes

2022-01-19 09:39 UTC, NaoUnderscore commented on Exiled.API/Enums/GrenadeType.cs
> +        /// Scp-2176 lightbulb
Docs should be end with a period.

2022-01-19 09:39 UTC, NaoUnderscore commented on Exiled.Events/Patches/Events/Map/BreakingScp2176.cs
> +#pragma warning disable SA1118 // The parameter spans multiple lines
Move the pragma directive inside the namespace.

2022-01-19 09:39 UTC, NaoUnderscore commented on Exiled.Events/Patches/Events/Map/BreakingScp2176.cs
> +                new CodeInstruction(OpCodes.Newobj, Constructor(typeof(ExplodingGrenadeEventArgs), new[] { typeof(API.Features.Player), typeof(EffectGrenade), typeof(UnityEngine.Collider[]) })),
Use `AccessTools::GetDeclaredConstructors`, it's more readable.

2022-01-19 23:42 UTC, NaoUnderscore approved these changes

2022-01-21 00:13 UTC, BuildBoy12 approved these changes

2022-01-21 03:50 UTC, joker-119 commented
Fix build errors

2022-01-21 13:46 UTC, merged