Docs fixes
Exiled-Team/EXILED pull request #1071
Opened 2022-01-26 19:27 UTC by Ceglaa

Small Player.cs docs fixed

2022-01-27 00:33 UTC, NaoUnderscore approved these changes

2022-01-28 04:21 UTC, Thundermaker300 commented
Merge upstream/dev into your branch to fix the build errors.

2022-01-28 07:18 UTC, Jesus-QC requested changes
I agree with thunder

2022-01-28 07:38 UTC, Jesus-QC commented
Also, fetch dev to fix build errors

2022-01-31 01:17 UTC, NaoUnderscore approved these changes

2022-02-02 00:09 UTC, merged