Introducing Log::Assert
Exiled-Team/EXILED pull request #1082
Opened 2022-02-07 11:28 UTC by Jesus-QC

2022-02-07 12:04 UTC, louis1706 commented
You can just add a condition on the error like the Log.Debug(string,bool = true) no ?

2022-02-07 12:20 UTC, Jesus-QC commented
Yeah but that doesn't stop the execution.

2022-02-07 12:21 UTC, Jesus-QC commented
Instad of using Debug.Assert you can also use 5 lines to have the same but this is to help with debugging

2022-02-07 12:21 UTC, Jesus-QC commented
Also this is method is not compiled if it isn't a debug build.

2022-02-07 20:29 UTC, NaoUnderscore approved these changes

2022-02-07 20:48 UTC, joker-119 commented
Won't *exiled* have to be compiled as debug for this method to be compiled?
Therefore in our releases any plugin trying to use the method will hit missing method exceptions?
:hmm:

2022-02-08 00:57 UTC, NaoUnderscore commented
> Won't _exiled_ have to be compiled as debug for this method to be compiled? Therefore in our releases any plugin trying to use the method will hit missing method exceptions? :hmm:

Are you drunk?
![immagine](https://user-images.githubusercontent.com/60253860/152897711-015056d8-5152-4273-8dd6-52cf1386f052.png)

2022-02-08 00:58 UTC, NaoUnderscore commented
Oh wait, I am drunk.

2022-02-08 00:59 UTC, NaoUnderscore requested changes
Remove conditional thing.

2022-02-08 17:18 UTC, Jesus-QC commented
However I dont care, if people wants to use this on RELEASE builds let them.

2022-02-08 18:34 UTC, merged