Fixes CustomAbility.Check
Exiled-Team/EXILED pull request #1132
Opened 2022-03-08 17:40 UTC by KrisPrs

I met a strange bug in my own customrole's customability. Method Check was always returning false in any registered events because `CustomAbility.Players.Count == 0`:
![image](https://user-images.githubusercontent.com/63547495/157286282-cf38ae51-5fc6-45f5-b645-389d16fe9d3e.png)
![image](https://user-images.githubusercontent.com/63547495/157286605-aa1cf315-a124-4b38-a906-ef4f59b2b5cd.png)
![image](https://user-images.githubusercontent.com/63547495/157286680-18f609bd-99db-4d14-923b-315af1ac8765.png)
This is the fix of this problem.
First my idea was to make property `CustomAbility.Players` static, but it would make Players tracking common for all CustomRoles at all. So it will be needed to make separated static field for each CustomAbility type, but i have no idea, is it possible.
The only solution i found out it to enumerate all the players and check their CustomRoles and CustomAbilities.
`TrackedPlayers.Add(player);` is moved, because i think, that player already must be in `CustomRole.TrackedPlayers` at the moment, when CustomAbility.AbilityAdded is called for some logic needs.

2022-03-08 17:49 UTC, KrisPrs commented
(Ignore Exiled.Events excluding from compilation, it was accidentally)

2022-03-10 18:45 UTC, KrisPrs commented
Also, please, consider rechecking https://github.com/Exiled-Team/EXILED/pull/1121
I'm an active CustomRoles API user, abilities aren't really registered with current EXILED code.

2022-03-10 22:04 UTC, NaoUnderscore requested changes

2022-03-10 22:04 UTC, NaoUnderscore commented on Exiled.CustomRoles/API/Features/CustomAbility.cs
> +                return Player.List.Where(x =>
1. Lamdba exists
2. `Player::Get` exists

2022-03-11 15:39 UTC, joker-119 commented
The amount of needless enumerations in that linq expression makes me want to vomit.

It would be much more prudent to see why CustomAbility isn't adding them to the hashset properly, rather then resorting to an extremely janky, inefficient linq expression.

2022-03-11 16:55 UTC, KrisPrs commented
It happeneds because of custom ability registraton and usage specific.
When you register a custom ability, you need to create an instance and call SubscribeEvents. But in future calls it will execute `Check` method only for that instance, that was used in registration - not for the real ones.

Now CustomAbility.Players are separeted for each instances of the same ability, this is the reason

It could be solved, if we were able to make different Players property static for every CustomAbility child, but not for CustomAbility class

2022-04-12 11:53 UTC, closed without merging