Breakable Window API + Add DamageTypeExtensions Method
Exiled-Team/EXILED pull request #1148
Opened 2022-03-28 20:42 UTC by louis1706

- Window API
- Exiled.API.Enum : ``GlassType``
- Make public ``TranslationConversion`` and add ``TranslationIdConversion``
- New Event ``Handlers.Player.PlayerDamageWindow``

(Not tested for now)

2022-03-28 21:05 UTC, Thundermaker300 commented on Exiled.API/Features/Window.cs
> +        /// Gets or sets a value indicating whether or not this window is broken.
doc

2022-03-28 21:06 UTC, Thundermaker300 commented on Exiled.API/Features/Window.cs
> +        public void DamageDoor(float amount) => Base.ServerDamageWindow(amount);
Rename to DamageWindow or Damage, not DamageDoor

2022-03-28 22:34 UTC, joker-119 commented
Your DamageHandler conversion is unnecessary.. literally just ev.Handler.Type, when will you ever have a DamageHandler that isn't in an event?

2022-03-29 04:45 UTC, louis1706 commented
> Your DamageHandler conversion is unnecessary.. literally just ev.Handler.Type, when will you ever have a DamageHandler that isn't in an event?

It's nessecary in an harmony patch you don't need to recreated a new DamageHandler for just get an player

2022-03-29 07:50 UTC, louis1706 commented on Exiled.API/Features/Window.cs
> +        /// Gets or sets a value indicating whether or not this window is broken.
?

2022-04-04 21:36 UTC, louis1706 commented
All the Window with ToTring() for testing (work fine)
```
Plants 10 False False
Plants 10 False False
MicroHid 10 False False
Plants 10 False False
Scp330 120 False False
GR18 20 False False
Scp079 5 False False
GR18 20 False False
GR18 20 False False
GR18 20 False False
GR18 20 False False
GR18 20 False False
GR18 20 False False
GR18 20 False False
GR18 20 False False
GR18 20 False False
GR18 20 False False
GR18 20 False False
GR18 20 False False
GR18 20 False False
Scp079 5 False False
GR18 20 False False
Scp049 10 False False
GR18 20 False False
GR18 20 False False
GR18 20 False False
Scp079Trigger 5 False True```
I have tested the position and rotation too
And GetDamageType work
and i have verified for the event swith SanyaDevTools

2022-04-07 06:32 UTC, NaoUnderscore requested changes
Fix build errors + Rename the event to `DamagingWindowEventArgs`.

2022-04-07 07:18 UTC, louis1706 commented
> Fix build errors + Rename the event to `DamagingWindowEventArgs`.

I do the rename later i don't going to do it on phone :)

2022-04-12 12:03 UTC, merged