`Player::RemoveItem` overloads
Exiled-Team/EXILED pull request #1215
Opened 2022-04-30 16:16 UTC by IRacle1

2022-05-01 17:55 UTC, NaoUnderscore requested changes
Fix docs and grammer by the way.

2022-05-01 17:55 UTC, NaoUnderscore commented on Exiled.API/Features/Player.cs
> +            foreach (var item in enumeratedItems)
Don't use var.

2022-05-01 17:55 UTC, NaoUnderscore commented on Exiled.API/Features/Player.cs
> +        /// Removes a list of <see cref="Item"/>'s filtered on a predicate from the player's inventory.
It doesn't remove a "list" of items. Follow the existing docs' style.

2022-05-01 17:55 UTC, NaoUnderscore commented on Exiled.API/Features/Player.cs
> +        /// <returns>Returns count of a successfully removed <see cref="Item"/>'s.</returns>
Grammar.

2022-05-01 17:55 UTC, NaoUnderscore commented on Exiled.API/Features/Player.cs
> +        /// <param name="destroy">Whether or not to destroy the items.</param>
Grammar.

2022-05-01 17:55 UTC, NaoUnderscore commented on Exiled.API/Features/Player.cs
> +            List<Item> enumeratedItems = new(ItemsValue);
And.. why?

2022-05-02 13:00 UTC, IRacle1 commented
I resolved all that I could

2022-05-05 10:39 UTC, NaoUnderscore approved these changes
I'll do some modifications later. It's fine as it as, more less.

2022-05-15 06:32 UTC, merged