add teleport doorType
Exiled-Team/EXILED pull request #1216
Opened 2022-04-30 18:06 UTC by moddedmcplayer

2022-05-01 17:27 UTC, NaoUnderscore requested changes

2022-05-01 17:27 UTC, NaoUnderscore commented on Exiled.API/Features/Player.cs
> +                    Teleport(Door.List.FirstOrDefault(x => x.Type == doorType)?.Position + Vector3.up);
`Door::Get(DoorType)` exists.

2022-05-05 10:40 UTC, NaoUnderscore approved these changes

2022-05-06 17:39 UTC, Jesus-QC approved these changes

2022-05-06 17:39 UTC, merged