`ProcessDisarmMessage` to transpilers
Exiled-Team/EXILED pull request #1225
Opened 2022-05-06 16:06 UTC by IRacle1

2022-05-06 20:17 UTC, NaoUnderscore requested changes

2022-05-06 20:17 UTC, NaoUnderscore commented on Exiled.Events/Patches/Events/Player/ProcessDisarmMessage.cs
> +            newInstructions[newInstructions.Count - 1].WithLabels(returnLabel);
Don't use `WithLabels`

2022-05-06 20:23 UTC, IRacle1 commented on Exiled.Events/Patches/Events/Player/ProcessDisarmMessage.cs
> +            newInstructions[newInstructions.Count - 1].WithLabels(returnLabel);
`.labels.Add()`?

2022-05-15 06:36 UTC, joker-119 approved these changes

2022-05-15 13:38 UTC, merged