InteractingDoor event with KeycardThrow
Exiled-Team/EXILED pull request #1317
Opened 2022-07-07 07:30 UTC by IRacle1

The only problem is that the interaction with the collision occurs several times, and the event is also invoked several times (an average of 3 times), but I do not think that this is a big problem

2022-07-07 15:27 UTC, louis1706 commented
I can look for make it not trigger multiple time

2022-07-07 16:08 UTC, louis1706 commented
> I can imagine the "trigger multiple times" would be a problem for plugins such as discord game logging plugins, which would send a log multiple times.

I already know how fixed it ^^ do not worry

2022-07-12 11:41 UTC, louis1706 approved these changes
it's all fine

2022-07-20 07:34 UTC, NaoUnderscore requested changes

2022-07-20 07:34 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/ThrowKeycardInteractingEventArgs.cs
> +    public class ThrowKeycardInteractingEventArgs : EventArgs
I'd rename it to `ThrowingInteractableKeycard` or `KeycardInteracting`.

2022-07-20 07:34 UTC, NaoUnderscore commented on Exiled.Events/Patches/Events/Item/InteractingDoorWithThrow.cs
> +    internal static class InteractingDoorWithThrow
Keep the same name as the event if possible.

2022-07-20 07:34 UTC, NaoUnderscore commented on Exiled.Events/Config.cs
> +        public bool CanKeycardThrowAffectOnBasicDoors { get; set; } = true;
`CanKeycardThrowAffectDoors`

2022-07-20 07:34 UTC, NaoUnderscore commented on Exiled.Events/Config.cs
> +        [Description("Indicates whether keycard throw can affect on basic doors(door with empty permissions)")]
I'd change it to: _Indicates whether thrown keycards can affect doors that don't require any permissions_

2022-07-25 22:03 UTC, BuildBoy12 commented
While it does fire only once when the interaction is allowed, it still fires multiple times when it is not.

LczArmory Door:
![image](https://user-images.githubusercontent.com/29316412/180881372-f3906154-a3b6-4197-9d94-da2334a00675.png)

Checkpoint:
![image](https://user-images.githubusercontent.com/29316412/180881425-8edccb0d-811f-4791-a96f-e0fc38544004.png)

2022-07-25 22:10 UTC, IRacle1 commented
my problem is logic, I'll fix it tomorrow

2022-07-26 08:23 UTC, louis1706 commented
> While it does fire only once when the interaction is allowed, it still fires multiple times when it is not.
> 
> LczArmory Door:
> ![image](https://user-images.githubusercontent.com/29316412/180881372-f3906154-a3b6-4197-9d94-da2334a00675.png)
> 
> Checkpoint:
> ![image](https://user-images.githubusercontent.com/29316412/180881425-8edccb0d-811f-4791-a96f-e0fc38544004.png)
> 

Is not in base game already like that i don't see the problem with this ? It's pretty normal i thinks

2022-07-26 08:40 UTC, IRacle1 commented
It's still a duplicate event, lots of reasons why it's bad

2022-07-26 08:46 UTC, louis1706 commented
> It's still a duplicate event, lots of reasons why it's bad

I will try something later for see if it's do not break something

2022-08-13 21:30 UTC, Jesus-QC approved these changes

2022-08-14 15:34 UTC, merged