Call finishing recall earlier
Exiled-Team/EXILED pull request #1326
Opened 2022-07-14 21:41 UTC by rayzerbrain

This calls OnFinishingRecall even if the person being recalled isn't a spectator, and it just sets IsAllowed to false if this is the case.

2022-07-24 23:08 UTC, louis1706 commented
I really like thinks like that :)

2022-07-25 21:47 UTC, BuildBoy12 requested changes

2022-07-25 21:47 UTC, BuildBoy12 commented on Exiled.Events/Patches/Events/Scp049/StartingAndFinishingRecall.cs
> +            offset = 0;
If the required offset is 0 then `offset` can be set to a `const` of -4 and this can be removed.

2022-07-25 21:52 UTC, rayzerbrain commented
Done

2022-07-25 22:05 UTC, BuildBoy12 approved these changes

2022-07-25 22:09 UTC, BuildBoy12 requested changes
Fix build errors.

2022-07-26 03:01 UTC, merged