Is Valid Sentence
Exiled-Team/EXILED pull request #1343
Opened 2022-07-29 09:25 UTC by louis1706

2022-07-29 10:02 UTC, IRacle1 commented
How it can return true?

2022-07-29 15:33 UTC, IRacle1 commented on Exiled.API/Features/Cassie.cs
> +        /// Gets a value indicating whether or not the given word is a valid C.A.S.S.I.E sentence.
`word`

2022-07-29 15:34 UTC, IRacle1 commented on Exiled.API/Features/Cassie.cs
> +        /// Gets a value indicating whether or not the given word is a valid C.A.S.S.I.E sentence.
Change to `sentence`

2022-07-30 03:38 UTC, NaoUnderscore requested changes

2022-07-30 03:38 UTC, NaoUnderscore commented on Exiled.API/Features/Cassie.cs
> +            foreach (string word in sentence.Split(' '))
`return sentence.Split(' ').Any(word => !string.IsNullOrWhiteSpace(word) && IsValid(word))`

2022-08-08 23:33 UTC, Thundermaker300 approved these changes

2022-08-13 00:49 UTC, merged