`Exiled.Launcher`
Exiled-Team/EXILED pull request #1345
Opened 2022-07-30 01:08 UTC by Jesus-QC

Here we go.

`Exiled.Updater` and `Exiled.Installer` will be deprecated by this pull request, merging both into one.

The Launcher will:
- Check for an installation (if none, install exiled).
- Check for updates (if outdated update).
- Run LocalAdmin
- Inject Exiled.Loader into the game thread.

2022-07-30 03:20 UTC, Monaldcry7788 commented
Does it will support multiadmin?

2022-07-30 10:13 UTC, Jesus-QC commented
> Does it will support multiadmin?

Yeah, ofc, but u will have to write smt like `--starting-point MultiAdmin.exe`

2022-08-07 08:43 UTC, NaoUnderscore requested changes

2022-08-07 08:43 UTC, NaoUnderscore commented on Exiled.Launcher/Features/Updater/InstallManager.cs
> +                Console.WriteLine("Skyping installation.");
SKYPING LMAO

2022-08-08 20:19 UTC, BuildBoy12 commented on Exiled.Launcher/Features/Updater/InstallManager.cs
> +            Console.WriteLine("Dest url: " + asset.BrowserDownloadUrl);
Dest

2022-08-08 20:19 UTC, BuildBoy12 commented on Exiled.Launcher/Features/Updater/InstallManager.cs
> +                Console.WriteLine("Skyping installation.");
Skyping

2022-11-05 16:04 UTC, Jesus-QC commented
LocalAdmin is receiving an update to handle plugins, we shouldn't have anything that overrides localadmin.

2022-11-05 16:04 UTC, closed without merging

2022-11-05 16:05 UTC, Jesus-QC commented
Oh wait, forgot this launched localadmin after lol

2022-11-05 17:30 UTC, IRacle1 commented
🙃