Doc fixes
Exiled-Team/EXILED pull request #1375
Opened 2022-08-13 01:32 UTC by Thundermaker300

2022-08-13 07:21 UTC, Ficus-x commented on Exiled.API/Extensions/MirrorExtensions.cs
> +        /// Set's <see cref="Room.Color"/> of a <paramref name="room"/> that only the <paramref name="target"/> player can see.
Set`s 0_o?

2022-08-13 21:07 UTC, Jesus-QC requested changes

2022-08-13 21:07 UTC, Jesus-QC commented on Exiled.API/Extensions/MirrorExtensions.cs
> +        /// Set's <see cref="Room.Color"/> of a <paramref name="room"/> that only the <paramref name="target"/> player can see.
Sets

2022-08-13 21:07 UTC, Jesus-QC commented on Exiled.API/Extensions/MirrorExtensions.cs
> +        /// Set's <see cref="Room.Color"/> of a <paramref name="room"/> that only the <paramref name="target"/> player can see.
Sets

2022-08-14 04:31 UTC, Thundermaker300 commented on Exiled.API/Extensions/MirrorExtensions.cs
> +        /// Set's <see cref="Room.Color"/> of a <paramref name="room"/> that only the <paramref name="target"/> player can see.
tired brain moment, will fix tomorrow probably

2022-08-14 16:40 UTC, rus-skill-issue approved these changes

2022-08-14 22:50 UTC, PintTheDragon commented
Imo "or not" is redundant, but it's your choice if you want to include it.

2022-08-15 14:57 UTC, Thundermaker300 commented
> Imo "or not" is redundant, but it's your choice if you want to include it.

Some docs have it, some have "whether [property info here] or not", some don't have either. I'm just trying to make it consistent lol

2022-08-25 00:57 UTC, PintTheDragon approved these changes

2022-12-27 04:21 UTC, Thundermaker300 commented
Moved to Exiled EA

2022-12-27 04:21 UTC, closed without merging