RoleChanged to transpilers
Exiled-Team/EXILED pull request #1388
Opened 2022-08-20 11:43 UTC by Ficus-x

xD

2022-08-20 12:00 UTC, joker-119 commented
Ahh yes, adding a ret instruction to the end of the method is totally the same thing.

Learn how transpilers work.

2022-08-20 13:07 UTC, IRacle1 commented
🙃

2022-08-22 02:50 UTC, NaoUnderscore requested changes

2022-08-22 02:50 UTC, NaoUnderscore commented on Exiled.Events/Patches/Fixes/RoleChangedPatch.cs
> +        private static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions, ILGenerator generator)
`private static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions) => yield return OpCodes.Ret;` or something

2022-08-25 17:58 UTC, Ficus-x commented on Exiled.Events/Patches/Fixes/RoleChangedPatch.cs
> +        private static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions, ILGenerator generator)
Solved

2022-09-18 22:58 UTC, Michal78900 approved these changes

2022-09-20 07:36 UTC, merged