Warhead EventArgs renamed
Exiled-Team/EXILED pull request #1409
Opened 2022-09-12 17:20 UTC by ClaudioPanConQueso

2022-09-12 18:08 UTC, ClaudioPanConQueso commented
For exiled 6

2022-09-12 19:14 UTC, louis1706 approved these changes

2022-09-14 06:11 UTC, joker-119 commented
Since these are already in the Warhead namespace, is this even necessary? 
afaik there aren't even other events that share the same names, right?

2022-09-14 06:28 UTC, IRacle1 requested changes

2022-09-14 06:28 UTC, IRacle1 commented on Exiled.Events/Handlers/Scp079.cs
>          public static void OnStoppingSpeaker(StoppingSpeakerEventArgs ev)
xD, fix it

2022-09-14 10:15 UTC, IRacle1 commented
> Since these are already in the Warhead namespace, is this even necessary? 
> afaik there aren't even other events that share the same names, right?

Yes, but most of people search events by EventArg name, it will be easier for them and for understanding that event + also many event are named with StoppedXXX

2022-09-14 17:55 UTC, ClaudioPanConQueso commented
First time i was coding, i didn't know that StartingEventArgs and Stopping was from the warhead.

2022-09-14 17:58 UTC, ClaudioPanConQueso commented on Exiled.Events/Handlers/Scp079.cs
>          public static void OnStoppingSpeaker(StoppingSpeakerEventArgs ev)
What thing? XD

2022-09-14 19:46 UTC, ClaudioPanConQueso commented on Exiled.Events/Handlers/Scp079.cs
>          public static void OnStoppingSpeaker(StoppingSpeakerEventArgs ev)
fixed

2022-09-17 22:25 UTC, Thundermaker300 commented
It is very much necessary

2022-09-18 22:49 UTC, Michal78900 approved these changes

2022-09-19 00:07 UTC, xNexus-ACS approved these changes

2022-09-21 03:51 UTC, zhaguanyang commented
I would say the idea is fine, but you forgot to rename it in patches. You should actually build it before trying to PR.

2022-09-21 10:32 UTC, Michal78900 requested changes
Fix build issues please

2022-09-21 12:14 UTC, ClaudioPanConQueso commented
> Fix build issues please

ok

2022-09-21 12:32 UTC, ClaudioPanConQueso commented
done

2023-01-05 01:42 UTC, closed without merging