Decontamination Phase
Exiled-Team/EXILED pull request #1415
Opened 2022-09-20 11:10 UTC by louis1706

2022-09-21 10:46 UTC, joker-119 commented
Fix borked

2022-09-21 11:06 UTC, louis1706 commented
> Fix borked

Sorry i fixed it idk why my VS do not show me warning and idk how refreshing warning

2022-10-03 22:00 UTC, NaoUnderscore requested changes

2022-10-03 22:00 UTC, NaoUnderscore commented on Exiled.API/Features/Map.cs
> +        /// Gets a value indicating what the actual state of the Decontamination.
_Gets the current decontamination phase._

2023-01-05 01:43 UTC, closed without merging