French Translation
Exiled-Team/EXILED pull request #1434
Opened 2022-10-09 22:02 UTC by warquys

I translated the Readme into French, for French people who are not competent enough to read the English even with google translator (they exists).

2022-10-10 16:40 UTC, moddedmcplayer requested changes

2022-10-10 16:40 UTC, moddedmcplayer commented on Localization/README-ES.md
> -- [English](https://github.com/Exiled-Team/EXILED/blob/master/README.md)
ummm

2022-10-10 20:48 UTC, warquys commented on Localization/README-ES.md
> -- [English](https://github.com/Exiled-Team/EXILED/blob/master/README.md)
yea sory

2022-10-12 16:29 UTC, moddedmcplayer submitted a review, later dismissed

2022-10-29 18:30 UTC, NaoUnderscore requested changes
Do not target dev branch.

2022-11-02 00:40 UTC, warquys commented
I modified the development branch so I can't push to another branch without pushing the whole Dev branch

2022-11-02 00:50 UTC, warquys commented
https://github.com/Exiled-Team/EXILED/pull/1443

2022-11-02 00:50 UTC, closed without merging