Fix CheckPermission
Exiled-Team/EXILED pull request #1445
Opened 2022-11-17 19:39 UTC by zhaguanyang

2022-11-17 19:50 UTC, zhaguanyang commented
https://discord.com/channels/656673194693885975/664263236048388097/1042882262708015204

2023-01-06 09:40 UTC, IRacle1 approved these changes

2023-01-06 12:51 UTC, iopietro requested changes

2023-01-06 12:51 UTC, iopietro commented on Exiled.Permissions/Extensions/Permissions.cs
> +                    return false;
```suggestion
                if (Player.Get(sender.SenderId) is not Player player)
                    return false;
```

2023-01-07 02:06 UTC, Thundermaker300 commented
PR should target dev branch, not master

2023-01-09 19:47 UTC, Thundermaker300 commented
`sender is GameCore.ConsoleCommandSender` what is `ConsoleCommandSender` in this case?

2023-01-10 01:02 UTC, iopietro approved these changes

2023-01-10 01:12 UTC, iopietro requested changes

2023-01-10 01:12 UTC, iopietro commented on Exiled.Permissions/Extensions/Permissions.cs
> +            if (sender.FullPermissions || sender is ServerConsoleSender || sender is GameCore.ConsoleCommandSender || sender == Server.Host.Sender)
```suggestion
            if (sender.FullPermissions || sender is ServerConsoleSender || sender == Server.Host.Sender)
```
`GameCore.ConsoleCommandSender` doesn't exist anymore.

2023-01-10 01:12 UTC, iopietro commented on Exiled.Permissions/Extensions/Permissions.cs
> +            else if (sender is PlayerCommandSender)
```suggestion
            else if (sender is PlayerCommandSender || sender is UserPrint)
```
Should this check be added to other ifs of `Exiled.Permissions` as well? `UserPrint` is the client-side player's console.

2023-01-10 02:47 UTC, iopietro approved these changes

2023-01-10 02:49 UTC, merged