Fix Teleport Method
Exiled-Team/EXILED pull request #1449
Opened 2022-11-30 21:26 UTC by louis1706

Using NW method is not bad :) it's does what we have needed here also fix people teleporting in wall or in object or in the void

2022-12-01 06:51 UTC, IRacle1 commented on Exiled.API/Features/Player.cs
> +        public void Teleport(Vector3 position) => ReferenceHub.playerMovementSync.OverridePosition(position);
Better to just edit `Position` setter

2023-01-05 20:47 UTC, louis1706 commented on Exiled.API/Features/Player.cs
> +        public void Teleport(Vector3 position) => ReferenceHub.playerMovementSync.OverridePosition(position);
no :)

2023-01-06 00:30 UTC, iopietro requested changes
Should we add the `isSafe` optional parameter to safely or not safely spawn the player at the chosen coordinates?

2023-01-06 00:30 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +            ReferenceHub.playerMovementSync.OverridePosition(safepos);
```suggestion
            if (!PlayerMovementSync.FindSafePosition(position, out Vector3 safepos, true, true))
                safepos = position;

            ReferenceHub.playerMovementSync.OverridePosition(safepos);
```

2023-01-07 02:07 UTC, Thundermaker300 commented
Target dev branch.

2023-01-08 22:53 UTC, louis1706 commented
I close this PR Because FindSafePosition no longer exist and nothing similar than this exist

2023-01-08 22:53 UTC, closed without merging