ThrownItem to ThrownGrenade
Exiled-Team/EXILED pull request #1467
Opened 2023-01-05 16:33 UTC by xNexus-ACS

2023-01-05 17:00 UTC, iopietro approved these changes

2023-01-05 18:22 UTC, louis1706 requested changes
ThrownProjectile

2023-01-06 00:23 UTC, iopietro commented
Yeah, we could call it like that then.

2023-01-06 00:24 UTC, iopietro requested changes
Call it ThrownProjectile

2023-01-06 03:20 UTC, xNexus-ACS commented
Sure

2023-01-06 13:59 UTC, xNexus-ACS commented
Done guys

2023-01-06 14:00 UTC, iopietro approved these changes

2023-01-06 18:31 UTC, joker-119 commented
Prs should always target dev not master

2023-01-07 00:26 UTC, Thundermaker300 commented on .github/workflows/programs.yml
> +        proj_name: [Exiled.Installer]
?

2023-01-07 01:10 UTC, iopietro commented on .github/workflows/programs.yml
> +        proj_name: [Exiled.Installer]
It's from Joker's commit.

2023-01-07 02:06 UTC, xNexus-ACS commented on .github/workflows/programs.yml
> +        proj_name: [Exiled.Installer]
yeah

2023-01-07 03:39 UTC, iopietro approved these changes

2023-01-07 03:49 UTC, Thundermaker300 commented on .github/workflows/programs.yml
> +        proj_name: [Exiled.Installer]
got it

2023-01-07 12:29 UTC, iopietro approved these changes

2023-01-07 14:54 UTC, Thundermaker300 approved these changes

2023-01-07 14:56 UTC, merged