JailBird API and better docs
Exiled-Team/EXILED pull request #1473
Opened 2023-01-06 20:36 UTC by Thundermaker300

2023-01-06 20:56 UTC, IRacle1 approved these changes

2023-01-07 01:25 UTC, iopietro requested changes

2023-01-07 01:25 UTC, iopietro commented on Exiled.API/Features/Items/Jailbird.cs
> +            set => TotalDamageDealt = JailbirdItem.DamageLimit - value;
```suggestion
            set => TotalDamageDealt = Mathf.Clamp(JailbirdItem.DamageLimit - value, 0, JailbirdItem.DamageLimit);
```

2023-01-07 01:25 UTC, iopietro commented on Exiled.API/Features/Items/Jailbird.cs
> +            set => TotalCharges = JailbirdItem.ChargesLimit - value;
```suggestion
            set => TotalCharges = Mathf.Clamp(JailbirdItem.ChargesLimit - value, 0, JailbirdItem.ChargesLimit);
```

2023-01-07 01:25 UTC, iopietro commented on Exiled.API/Features/Pickups/JailbirdPickup.cs
> +            set => TotalDamageDealt = JailbirdItem.DamageLimit - value;
```suggestion
            set => TotalDamageDealt = Mathf.Clamp(JailbirdItem.DamageLimit - value, 0, JailbirdItem.DamageLimit);
```

2023-01-07 01:25 UTC, iopietro commented on Exiled.API/Features/Pickups/JailbirdPickup.cs
> +            set => TotalCharges = JailbirdItem.ChargesLimit - value;
```suggestion
            set => TotalCharges = Mathf.Clamp(JailbirdItem.ChargesLimit - value, 0, JailbirdItem.ChargesLimit);
```

2023-01-07 03:41 UTC, iopietro approved these changes

2023-01-07 03:48 UTC, merged