Door type extension and room fix
Exiled-Team/EXILED pull request #1485
Opened 2023-01-08 21:20 UTC by louis1706

2023-01-08 21:22 UTC, Thundermaker300 commented
yamato i swear if you target master one more time

2023-01-08 21:23 UTC, Thundermaker300 commented
Replace all cases of "room" with "door" in DoorExtensions.

2023-01-08 21:30 UTC, Thundermaker300 requested changes

2023-01-08 21:30 UTC, Thundermaker300 commented on Exiled.API/Extensions/DoorTypeExtensions.cs
> +        public static bool IsGate(this DoorType room) => room is DoorType.GateA or DoorType.GateB or DoorType.Scp914Gate or
```suggestion
        public static bool IsGate(this DoorType door) => door is DoorType.GateA or DoorType.GateB or DoorType.Scp914Gate or
```

2023-01-08 21:30 UTC, Thundermaker300 commented on Exiled.API/Extensions/DoorTypeExtensions.cs
> +        public static bool IsCheckpoint(this DoorType room) => room is DoorType.CheckpointLczA
```suggestion
        public static bool IsCheckpoint(this DoorType door) => door is DoorType.CheckpointLczA
```

2023-01-08 21:30 UTC, Thundermaker300 commented on Exiled.API/Extensions/DoorTypeExtensions.cs
> +        public static bool IsElevator(this DoorType room) => room is DoorType.ElevatorGateA or DoorType.ElevatorGateB
```suggestion
        public static bool IsElevator(this DoorType door) => door is DoorType.ElevatorGateA or DoorType.ElevatorGateB
```

2023-01-08 21:30 UTC, Thundermaker300 commented on Exiled.API/Extensions/DoorTypeExtensions.cs
> +        /// <param name="room">The door to be checked.</param>
```suggestion
        /// <param name="door">The door to be checked.</param>
```

2023-01-08 21:30 UTC, Thundermaker300 commented on Exiled.API/Extensions/DoorTypeExtensions.cs
> +        /// <param name="room">The door to be checked.</param>
```suggestion
        /// <param name="door">The door to be checked.</param>
```

2023-01-08 21:30 UTC, Thundermaker300 commented on Exiled.API/Extensions/DoorTypeExtensions.cs
> +        /// <param name="room">The door to be checked.</param>
```suggestion
        /// <param name="door">The door to be checked.</param>
```

2023-01-08 21:37 UTC, Thundermaker300 approved these changes

2023-01-08 21:38 UTC, Thundermaker300 commented on Exiled.API/Extensions/DoorTypeExtensions.cs
> +        /// Checks if a <see cref="DoorType">door type</see> is a elevator.
```suggestion
        /// Checks if a <see cref="DoorType">door type</see> is an elevator.
```
English :trollface:

2023-01-08 21:40 UTC, Thundermaker300 approved these changes

2023-01-08 23:46 UTC, iopietro requested changes

2023-01-08 23:46 UTC, iopietro commented on Exiled.API/Extensions/DoorTypeExtensions.cs
> +            or DoorType.CheckpointLczB or DoorType.CheckpointEzHczA or DoorType.CheckpointEzHczB;
```suggestion
        public static bool IsCheckpoint(this DoorType door) => door is DoorType.CheckpointLczA or DoorType.CheckpointLczB or DoorType.CheckpointEzHczA or DoorType.CheckpointEzHczB;
```

2023-01-09 13:50 UTC, iopietro approved these changes

2023-01-09 13:51 UTC, merged