Get max ammo(pickup) 2
Exiled-Team/EXILED pull request #1488
Opened 2023-01-08 23:13 UTC by louis1706

2023-01-08 23:14 UTC, louis1706 commented
remake of #1999

2023-01-09 14:33 UTC, iopietro requested changes
I haven't looked at your algorithm yet.

2023-01-09 14:33 UTC, iopietro commented on Exiled.API/Extensions/ItemExtensions.cs
> +            return ammo += (byte)UnityEngine.Mathf.Clamp(GetAttachmentsValue(firearm, AttachmentParam.MagazineCapacityModifier), byte.MinValue, byte.MaxValue);
```suggestion
            return ammo += (byte)UnityEngine.Mathf.Clamp(firearm.GetAttachmentsValue(AttachmentParam.MagazineCapacityModifier), byte.MinValue, byte.MaxValue);
```

2023-01-09 14:33 UTC, iopietro commented on Exiled.API/Extensions/ItemExtensions.cs
> +            byte ammo = GetMaxAmmo(firearm.Info.ItemId.GetFirearmType());
```suggestion

            byte ammo = GetMaxAmmo(firearm.Info.ItemId.GetFirearmType());
```

2023-01-09 14:33 UTC, iopietro commented on Exiled.API/Extensions/ItemExtensions.cs
> +            }
```suggestion
            foreach (AttachmentIdentifier attachmentIdentifier in attachments)
            {
                Attachment attachment = AttachmentsList.FirstOrDefault(x => x.Name == attachmentIdentifier.Name);

                if (attachment is null || !attachment.TryGetValue((int)attachmentParam, out float paraValue))
                    continue;

                num = AttachmentsUtils.MixValue(num, paraValue, definitionOfParam.MixingMode);
            }
```

2023-01-09 14:33 UTC, iopietro commented on Exiled.API/Extensions/ItemExtensions.cs
> +            IEnumerable<AttachmentIdentifier> attachements = GetAttachmentIdentifiers(firearmPickup.Info.ItemId.GetFirearmType(), firearmPickup.Status.Attachments);
```suggestion
            IEnumerable<AttachmentIdentifier> attachments = GetAttachmentIdentifiers(firearmPickup.Info.ItemId.GetFirearmType(), firearmPickup.Status.Attachments);
```

2023-01-10 19:33 UTC, Thundermaker300 commented
Fix build errors

2023-09-05 07:45 UTC, closed without merging