SCP-939 events
Exiled-Team/EXILED pull request #1490
Opened 2023-01-09 15:37 UTC by Thundermaker300

Moved from https://github.com/Exiled-Team/Exiled-EA/pull/206

2023-01-09 15:38 UTC, Thundermaker300 commented
Events need transpilers

2023-01-10 00:51 UTC, iopietro requested changes

2023-01-10 00:51 UTC, iopietro commented on Exiled.Events/EventArgs/Scp939/ChangingFocusEventArgs.cs
> +            Player = player;
We should get the player in every event constructor from its `ReferenceHub` like you do in every other event below.

2023-01-11 16:45 UTC, iopietro approved these changes

2023-01-12 17:02 UTC, IRacle1 approved these changes

2023-01-12 22:59 UTC, iopietro approved these changes

2023-01-12 22:59 UTC, merged