Add Map.FindParentRoom overloads
Exiled-Team/EXILED pull request #1497
Opened 2023-01-13 02:24 UTC by Thundermaker300

Make it more convenient to find a room based on position by providing FindParentRoom overloads

2023-01-13 02:42 UTC, iopietro requested changes

2023-01-13 02:42 UTC, iopietro commented on Exiled.API/Features/Map.cs
> +            => Room.Get(position);
```suggestion
        public static Room FindParentRoom(Vector3 position) => Room.Get(position);
```

2023-01-13 02:42 UTC, iopietro commented on Exiled.API/Features/Map.cs
> +            => Room.Get(position.Position);
```suggestion
        public static Room FindParentRoom(RelativePosition position) => Room.Get(position.Position);
```

2023-01-15 15:35 UTC, iopietro approved these changes

2023-01-15 17:43 UTC, louis1706 commented
> I'm wondering if we should rename these to `FindRoom`, as `FindParentRoom` is kind of misleading for Vector3s that don't have a "parent" room.
your  FindRoom() are useless here they should be all In Room api (also Map.FindParentRoom because it's a Room so should be in Room)

2023-01-15 17:46 UTC, Thundermaker300 commented
Moving `Map.FindParentRoom` is a breaking change. I added these because Room.Get() isn't exactly as obvious. Having them doesn't hurt anything

2023-01-16 11:01 UTC, louis1706 commented
> Moving `Map.FindParentRoom` is a breaking change. I added these because Room.Get() isn't exactly as obvious. Having them doesn't hurt anything

I know it's breaking change it's why i don't want it to be moved for now but i thinks everything related to Room should be kept in Room

2023-01-17 16:56 UTC, IRacle1 approved these changes

2023-01-17 19:26 UTC, louis1706 approved these changes

2023-01-17 21:14 UTC, merged