Add Player.Lift property
Exiled-Team/EXILED pull request #1509
Opened 2023-01-15 04:02 UTC by Thundermaker300

2023-01-15 12:15 UTC, iopietro approved these changes

2023-01-15 23:01 UTC, louis1706 commented on Exiled.API/Features/Player.cs
> +                foreach (var lift in Lift.List)
idk if it's possible but we have possibly a way to make it better

2023-01-15 23:09 UTC, iopietro requested changes

2023-01-15 23:09 UTC, iopietro commented on Exiled.API/Features/Lift.cs
> +        }
```suggestion
        ~Lift() => ListPool<ElevatorDoor>.Pool.Return(internalDoorsList);
```

2023-01-16 09:18 UTC, louis1706 commented
https://github.com/Thundermaker300/EXILED/pull/3 suggested change

2023-01-16 14:43 UTC, closed without merging

2023-01-16 14:46 UTC, Thundermaker300 commented
Will recreate without a breaking pr from yamato :trollface: