Fix changing spectated player
Exiled-Team/EXILED pull request #1512
Opened 2023-01-15 17:41 UTC by louis1706

- actually having IL error code on line newobj
but everything else work

- Remove Setter and IDeniableEvent because client will not sync

2023-01-15 22:18 UTC, Thundermaker300 approved these changes

2023-01-15 23:23 UTC, iopietro requested changes

2023-01-15 23:23 UTC, iopietro commented on Exiled.Events/Patches/Events/Player/ChangingSpectatedPlayerPatch.cs
> +                    new CodeInstruction(OpCodes.Ldloca_S, owner.LocalIndex),
```suggestion
                    new CodeInstruction(OpCodes.Ldloc_S, owner.LocalIndex),
```

2023-01-15 23:23 UTC, iopietro commented on Exiled.Events/Patches/Events/Player/ChangingSpectatedPlayerPatch.cs
>                      new(OpCodes.Ldarga_S, 1),
```suggestion
                    new(OpCodes.Ldarg_1),
```

2023-01-15 23:23 UTC, iopietro commented on Exiled.Events/Patches/Events/Player/ChangingSpectatedPlayerPatch.cs
> +                    new CodeInstruction(OpCodes.Pop),
```suggestion
                    // _ = this.TryGetOwner(out ReferenceHub owner)
                    new CodeInstruction(OpCodes.Ldarg_0),
                    new CodeInstruction(OpCodes.Ldloca_S, owner.LocalIndex),
                    new CodeInstruction(OpCodes.Callvirt, Method(typeof(PlayerRoleBase), nameof(PlayerRoleBase.TryGetOwner), new[] { typeof(ReferenceHub).MakeByRefType() })),
                    new CodeInstruction(OpCodes.Pop),
```

2023-01-17 13:40 UTC, iopietro approved these changes

2023-01-17 13:40 UTC, merged