SCP-079 API part 2
Exiled-Team/EXILED pull request #1517
Opened 2023-01-15 23:02 UTC by Thundermaker300

2023-01-15 23:29 UTC, iopietro requested changes

2023-01-15 23:29 UTC, iopietro commented on Exiled.API/Features/Roles/Scp079Role.cs
> +        public IReadOnlyCollection<Room> MarkedRooms => RewardManager._markedRooms.Select(kvp => Room.Get(kvp.Key)).ToList();
```suggestion
        public IEnumerable<Room> MarkedRooms => RewardManager._markedRooms.Select(kvp => Room.Get(kvp.Key));
```

2023-01-15 23:43 UTC, iopietro approved these changes

2023-01-17 19:25 UTC, louis1706 approved these changes

2023-01-17 21:22 UTC, merged