Update UpgradingPlayer.cs
Exiled-Team/EXILED pull request #1525
Opened 2023-01-16 23:25 UTC by louis1706

2023-01-16 23:27 UTC, Thundermaker300 approved these changes

2023-01-17 00:21 UTC, Misaka-ZeroTwo requested changes
The transpiler needs to be fixed

2023-01-17 16:54 UTC, IRacle1 commented
Why is it exists, when transpiler and so on fixed in #1527?

2023-01-17 18:07 UTC, Misaka-ZeroTwo commented
> Why is it exists, when transpiler and so on fixed in #1527?

Cuz Yamato thought the transpiler works.

2023-01-17 18:54 UTC, closed without merging