914 fix for process player
Exiled-Team/EXILED pull request #1527
Opened 2023-01-17 01:53 UTC by Undid-Iridium

As title states

2023-01-17 01:59 UTC, Undid-Iridium commented
Let me test a little more variations, I will let you know when I am ready for merge.

2023-01-17 13:48 UTC, iopietro requested changes
Also update the comments above `newInstructions.InsertRange(...)`.

2023-01-17 13:48 UTC, iopietro commented on Exiled.Events/Patches/Events/Scp914/UpgradingPlayer.cs
> +            newInstructions[continueIndex].labels.Add(continueLabel);
```suggestion
            int continueIndex = newInstructions.FindIndex(index, instruction => instruction.opcode == OpCodes.Leave_S) - 3;

            newInstructions[continueIndex].labels.Add(continueLabel);
```

2023-01-17 13:49 UTC, iopietro requested changes

2023-01-17 13:49 UTC, iopietro commented on Exiled.Events/Patches/Events/Scp079/ChangingCamera.cs
> +            Scp079.OnChangingCamera(ev);
```suggestion
            ChangingCameraEventArgs ev = new ChangingCameraEventArgs(Player.Get(instance.Owner), instance._switchTarget, cost);

            Scp079.OnChangingCamera(ev);
```

2023-01-17 22:49 UTC, louis1706 requested changes
Testing show than 079 sometimes get stuck(unable to choose other camera). 

 (it's not always happening so not sure at 100% than it's from here)

2023-01-18 00:40 UTC, iopietro approved these changes

2023-01-18 04:23 UTC, IRacle1 submitted a review, later dismissed

2023-01-18 04:23 UTC, IRacle1 commented on Exiled.Events/Patches/Events/Scp079/ChangingCamera.cs
> +            if(ev.IsAllowed)
```suggestion
            if (ev.IsAllowed)
```

2023-01-18 12:31 UTC, iopietro requested changes

2023-01-18 12:31 UTC, iopietro commented on Exiled.Events/Patches/Events/Scp079/ChangingCamera.cs
> +            return ev.IsAllowed;
```suggestion
            instance.ServerSendRpc(true);

            if (ev.IsAllowed)
                cost = ev.AuxiliaryPowerCost;

            return ev.IsAllowed;
```

2023-01-18 18:27 UTC, louis1706 approved these changes

2023-01-19 13:09 UTC, Thundermaker300 approved these changes

2023-01-19 13:09 UTC, merged