Lunge modification
Exiled-Team/EXILED pull request #1528
Opened 2023-01-17 07:43 UTC by Undid-Iridium

At least allows damage refusal and other things. @louis1706 @Thundermaker300 thoughts

2023-01-17 20:28 UTC, louis1706 requested changes

2023-01-17 20:28 UTC, louis1706 commented on Exiled.Events/Handlers/Scp939.cs
>          ///     Invoked before SCP-939 uses its lunge ability.
After

2023-01-17 20:28 UTC, louis1706 commented on Exiled.Events/Handlers/Scp939.cs
>          ///     Called before SCP-939 uses its lunge ability.
After

2023-01-17 22:42 UTC, louis1706 requested changes

2023-01-17 22:42 UTC, louis1706 commented on Exiled.Events/EventArgs/Scp939/LungedEventArgs.cs
> +        /// Gets or sets scp939's lunge state. If you deny event, lunge state changes to this.
you can't deny this event ? now

2023-01-18 00:44 UTC, iopietro requested changes

2023-01-18 00:44 UTC, iopietro commented on Exiled.Events/Patches/Events/Scp939/Lunge.cs
> +        [HarmonyTranspiler]
This should be done like other patches.

2023-01-20 12:33 UTC, iopietro requested changes

2023-01-20 12:33 UTC, iopietro commented on Exiled.Events/Patches/Events/Scp939/Lunge.cs
> +                }
```suggestion
                if (!instance.IsReady)
                    return;
```

2023-01-20 12:33 UTC, iopietro commented on Exiled.Events/Patches/Events/Scp939/Lunge.cs
> +            if (instance.State != Scp939LungeState.Triggered)
```suggestion

            if (instance.State != Scp939LungeState.Triggered)
```

2023-01-20 12:33 UTC, iopietro commented on Exiled.Events/Patches/Events/Scp939/Lunge.cs
>              }
```suggestion
```

2023-01-20 12:33 UTC, iopietro commented on Exiled.Events/Patches/Events/Scp939/Lunge.cs
>              if (!flag || referenceHub.IsAlive())
```suggestion

            if (!flag || referenceHub.IsAlive())
```

2023-01-20 12:33 UTC, iopietro commented on Exiled.Events/Patches/Events/Scp939/Lunge.cs
>              }
```suggestion
```

2023-01-20 12:33 UTC, iopietro commented on Exiled.Events/Patches/Events/Scp939/Lunge.cs
> +            newInstructions.InsertRange(
```suggestion
            int index = newInstructions.FindIndex(instruction => instruction.Calls(Method(typeof(ScpSubroutineBase), nameof(ScpSubroutineBase.ServerProcessCmd)))) + 1;

            newInstructions.InsertRange(
```

2023-01-25 02:03 UTC, iopietro requested changes

2023-01-25 02:03 UTC, iopietro commented on Exiled.Events/Patches/Events/Scp939/Lunge.cs
> +                    new(OpCodes.Br, returnLabel),
```suggestion
                    new(OpCodes.Br_S, returnLabel),
```

2023-01-25 11:04 UTC, iopietro approved these changes

2023-01-26 00:15 UTC, louis1706 requested changes
Make LungingEventArgs / OnLunging Obsolete instead of renaming them

Obsolete["Replace by LungingEventArgs", true]

2023-01-26 02:58 UTC, Undid-Iridium commented
> Make LungingEventArgs / OnLunging Obsolete instead of renaming them
> 
> Obsolete["Replace by LungingEventArgs", true]

![image](https://user-images.githubusercontent.com/24619207/214748814-bdd954c5-063f-4fa9-abc6-37c85cef8f73.png)

Make the change you want and I'll commit it like Pietro does

2023-01-26 09:53 UTC, louis1706 commented
Also the event will need a rework to be a real transpiler

2023-02-02 04:30 UTC, Undid-Iridium commented
Since I can't seem to tag it, Needs testing.

2023-02-14 01:43 UTC, Undid-Iridium commented
Someone else can take this

2023-02-14 01:43 UTC, closed without merging