Updated polish localization
Exiled-Team/EXILED pull request #1536
Opened 2023-01-18 09:49 UTC by Mikihero

2023-01-18 09:49 UTC, Mikihero commented
wtf why does it show commits from months ago that I'm pretty sure were merged in a PR 💀

2023-01-21 10:57 UTC, Michal78900 commented on Localization/README-PL.md
> +  - Przenieść go do folderu: ``C:\Users\(Wasz_użytkownik)\AppData\Roaming\EXILED\Plugins`` (aby się tutaj dosta wystarczy wcisnąć Win + R i wpisać `%appdata%`)
dosta -> dosta**ć**

2023-01-21 10:57 UTC, Michal78900 commented on Localization/README-PL.md
> +  - Przenieście folder **`SCP Secret Laboratory`** do ścieżki **``~/.config``**. *UWAGA: The folder musi znaleźć się w ``~/.config``, **A *NIE*** ``~/.config/SCP Secret Laboratory``* (SSH: **`mv SCP
The folder

2023-01-21 10:59 UTC, Michal78900 commented on Localization/README-PL.md
> + - Gdy plugin jest załadowany kod zawarty w metodzie ``OnEnabled()`` nie czeka aż pozostałe pluginy zostaną załadowane, nie czeka aż proces uruchamiania serwera się zakończy. ***Nie czeka na nic.***
O jeden apostrof za dużo w `ServerConsole.Port`

2023-01-21 11:00 UTC, Michal78900 commented on Localization/README-PL.md
> +    for (;;) //powtórz następujący w nieskończoność
następujący co? chyba kod

2023-01-21 11:01 UTC, Michal78900 requested changes
There are minor spelling mistakes

2023-01-21 12:45 UTC, Mikihero commented
> There are minor spelling mistakes

I'll get on it later today

2023-02-19 04:38 UTC, merged