Flashbangfix
Exiled-Team/EXILED pull request #1551
Opened 2023-01-20 22:22 UTC by Undid-Iridium

2023-01-21 00:21 UTC, Undid-Iridium commented
> Will need to finish Transpiler disable 

What.

2023-01-21 19:09 UTC, Thundermaker300 approved these changes

2023-01-24 14:02 UTC, louis1706 requested changes

2023-01-24 14:02 UTC, louis1706 commented on Exiled.Events/Patches/Events/Map/BreakingScp2176.cs
> +    // [HarmonyPatch(typeof(Scp2176Projectile), nameof(Scp2176Projectile.ServerShatter))]
can't we keep this not comment ?

2023-01-25 01:46 UTC, iopietro commented on Exiled.Events/Patches/Events/Map/ExplodingFlashGrenade.cs
> +                    new(OpCodes.Br, returnLabel),
```suggestion
                    new(OpCodes.Br_S, returnLabel),
```

2023-01-25 01:46 UTC, iopietro commented on Exiled.Events/Patches/Events/Map/ExplodingFlashGrenade.cs
> +            }
```suggestion
            if (!explodingGrenadeEvent.IsAllowed)
                return;
```

2023-01-25 01:46 UTC, iopietro commented on Exiled.Events/Patches/Events/Map/ExplodingFlashGrenade.cs
> +            Handlers.Map.OnExplodingGrenade(explodingGrenadeEvent);
```suggestion
            ExplodingGrenadeEventArgs explodingGrenadeEvent = new ExplodingGrenadeEventArgs(Player.Get(instance.PreviousOwner.Hub), instance);

            Handlers.Map.OnExplodingGrenade(explodingGrenadeEvent);
```

2023-01-25 01:46 UTC, iopietro commented on Exiled.Events/Patches/Events/Map/ExplodingFlashGrenade.cs
> +                }
```suggestion
                if (!ExiledEvents.Instance.Config.CanFlashbangsAffectThrower && (explodingGrenadeEvent.Player == player))
                    continue;

                if (HitboxIdentity.CheckFriendlyFire(explodingGrenadeEvent.Player.ReferenceHub, player.ReferenceHub))
                    instance.ProcessPlayer(player.ReferenceHub);
```

2023-01-25 01:46 UTC, iopietro commented on Exiled.Events/Patches/Events/Player/Shot.cs
> +            return shotEvent.CanHurt;
```suggestion
        private static bool ProcessShot(ReferenceHub player, RaycastHit hit, IDestructible destructible, ref float damage)
        {
            ShotEventArgs shotEvent = new ShotEventArgs(Player.Get(player), hit, destructible, damage);
            
            Handlers.Player.OnShot(shotEvent);
            
            if (shotEvent.CanHurt)
                damage = shotEvent.Damage;

            return shotEvent.CanHurt;
```

2023-01-25 01:46 UTC, iopietro commented on Exiled.Events/Patches/Events/Player/Shot.cs
> +                    new(OpCodes.Brfalse, returnLabel),
```suggestion
                    new(OpCodes.Brfalse_S, returnLabel),
```

2023-01-25 01:46 UTC, iopietro commented on Exiled.Events/Patches/Events/Player/Shot.cs
> +                    new(OpCodes.Call, Method(typeof(Shot), nameof(ProcessShot))),
```suggestion
                    new(OpCodes.Call, Method(typeof(Shot), nameof(ProcessShot), new[] { typeof(ReferenceHub), typeof(RaycastHit), typeof(IDestructible),  typeof(float).MakeByRefType()})),
```

2023-01-25 01:46 UTC, iopietro commented on Exiled.Events/Patches/Events/Player/Shot.cs
>                      new(OpCodes.Brfalse, returnLabel),
```suggestion
                    new(OpCodes.Brfalse_S, returnLabel),
```

2023-01-25 01:46 UTC, iopietro commented on Exiled.Events/Patches/Events/Player/Shot.cs
> +                    new(OpCodes.Call, Method(typeof(Shot), nameof(ProcessShot))),
```suggestion
                    new(OpCodes.Call, Method(typeof(Shot), nameof(ProcessShot), new[] { typeof(ReferenceHub), typeof(RaycastHit), typeof(IDestructible),  typeof(float).MakeByRefType()})),
```

2023-01-25 04:09 UTC, Undid-Iridium commented on Exiled.Events/Patches/Events/Map/BreakingScp2176.cs
> +    // [HarmonyPatch(typeof(Scp2176Projectile), nameof(Scp2176Projectile.ServerShatter))]
Do as IOPietro did and I'll commit it

2023-01-25 11:11 UTC, iopietro approved these changes

2023-01-25 16:20 UTC, louis1706 approved these changes

2023-01-25 18:34 UTC, iopietro requested changes
Build errors.

2023-01-26 02:50 UTC, Undid-Iridium commented
The fact there is not just a simple ruleset for a formatter is a really sad part of Exiled, and wastes a lot of time. Action on Save, CSharpier, Prettier, dotnet-format. Several options with configurations/rulesets that could be defined but ¯\_(ツ)_/¯
![image](https://user-images.githubusercontent.com/24619207/214742971-25ec42f8-25aa-45be-9aec-829c38f300af.png)

It would be a lot simpler than the current waste of time, and honestly it's almost all opinionated arbitrary preferences, such as no braces for single if conditions (which is normally NOT recommended). You dev-bois should really figure out what rules you want, and then make it a requirement to have than stylecop whose purpose is just to complain instead of fix.    

For example, brace spacing 

![image](https://user-images.githubusercontent.com/24619207/214743587-e5be2685-58b7-4dfe-85f1-e85be4d5b37c.png)

![image](https://user-images.githubusercontent.com/24619207/214745752-4c0f3af5-649d-4c9b-b4e0-e2389733d675.png)
![image](https://user-images.githubusercontent.com/24619207/214745877-1371f649-0c99-4573-b2d6-26584cafe8ff.png)

![image](https://user-images.githubusercontent.com/24619207/214743944-44fd8714-11ba-4080-8530-4be67fa166ea.png)

Anyway, that's my ted talk rant. 

[editorconfig TXT](https://github.com/Exiled-Team/EXILED/files/10505981/editorconfig.TXT)

2023-01-28 11:37 UTC, iopietro commented
@Undid-Iridium

I mean, apart from StyleCop rules the only three formatting rules that we are following right now are: 
- Do not clog up your code and space it as much as possible to make it more understandable;
- Do not use braces in single-line ifs;
- Try to keep inline methods in one line when possible.

That's it, if you've some other issues about the formatter you can make a PR about the `.editorconfig` file to reflect something that you want to add/change.

2023-01-28 11:46 UTC, iopietro requested changes
Don't use `var`.

2023-01-31 01:43 UTC, iopietro requested changes

2023-01-31 01:43 UTC, iopietro commented on Exiled.Events/Patches/Events/Map/ExplodingFlashGrenade.cs
> +                if (!ExiledEvents.Instance.Config.CanFlashbangsAffectThrower && (explodingGrenadeEvent.Player == player))
```suggestion
                if (!ExiledEvents.Instance.Config.CanFlashbangsAffectThrower && explodingGrenadeEvent.Player == player)
```

2023-01-31 01:43 UTC, iopietro commented on Exiled.Events/Patches/Events/Map/ExplodingFlashGrenade.cs
> +                    // Returns DoctorSenseEventArgs
```suggestion
                    // Processes ExplodingGrenadeEventArgs
```

2023-02-01 23:06 UTC, merged