Fixes
Exiled-Team/EXILED pull request #1562
Opened 2023-01-25 14:17 UTC by IRacle1

2023-01-27 15:55 UTC, louis1706 approved these changes

2023-01-27 16:27 UTC, louis1706 requested changes
Making this error when killing a player with 939 
```[2023-01-27 17:19:04.114 +01:00] [STDOUT] NullReferenceException: Object reference not set to an instance of an object
[2023-01-27 17:19:04.114 +01:00] [STDOUT]   at BasicRagdoll.Start () [0x00032] in <f8a7dc9f7e1542b6b7f61ba2e37f0749>:0
[2023-01-27 17:19:04.114 +01:00] [STDOUT] (Filename: <f8a7dc9f7e1542b6b7f61ba2e37f0749> Line: 0)
[2023-01-27 17:19:04.178 +01:00] [STDOUT] Caught fatal signal - signo:11 code:1 errno:0 addr:0x3dcccced
[2023-01-27 17:19:04.192 +01:00] [STDOUT] Obtained 9 stack frames.
[2023-01-27 17:19:04.193 +01:00] [STDOUT] #0  0x007f1fe774c730 in funlockfile
[2023-01-27 17:19:04.193 +01:00] [STDOUT] #1  0x007f1fe8301699 in Scripting::ScriptingWrapperFor(Object*)
[2023-01-27 17:19:04.193 +01:00] [STDOUT] #2  0x007f1fe83b07cb in Component_Get_Custom_PropGameObject(ScriptingBackendNativeObjectPtrOpaque*)
[2023-01-27 17:19:04.193 +01:00] [STDOUT] #3  0x00000042071da6 in (wrapper managed-to-native) UnityEngine.Component:get_gameObject (UnityEngine.Component)
[2023-01-27 17:19:04.193 +01:00] [STDOUT] #4  0x000000427b16d8 in Exiled.Events.EventArgs.Scp939.PlayingVoiceEventArgs:.ctor (ReferenceHub,ReferenceHub)
[2023-01-27 17:19:04.193 +01:00] [STDOUT] #5  0x0000004278ac90 in PlayerRoles.PlayableScps.Subroutines.SubroutineMessage:ServerApplyTrigger (Mirror.NetworkConnection)
[2023-01-27 17:19:04.193 +01:00] [STDOUT] #6  0x00000042787672 in Mirror.MessagePacking/<>c__DisplayClass7_0`2<PlayerRoles.PlayableScps.Subroutines.SubroutineMessage, Mirror.NetworkConnection>:<WrapHandler>b__0 (Mirror.NetworkConnection,Mirror.NetworkReader,int)
[2023-01-27 17:19:04.193 +01:00] [STDOUT] #7  0x00000042611362 in Mirror.NetworkConnection:UnpackAndInvoke (Mirror.NetworkReader,int)
[2023-01-27 17:19:04.193 +01:00] [STDOUT] #8  0x00000042723a6c in Mirror.NetworkServer:OnDataReceived (int,System.ArraySegment`1<byte>,int)
```

2023-01-27 16:48 UTC, louis1706 approved these changes

2023-01-28 11:19 UTC, iopietro approved these changes

2023-01-28 11:22 UTC, merged