``Pickup::Get(GameObject)``
Exiled-Team/EXILED pull request #1566
Opened 2023-01-25 17:15 UTC by louis1706

2023-01-25 18:33 UTC, iopietro requested changes

2023-01-25 18:33 UTC, iopietro commented on Exiled.API/Features/Pickups/Pickup.cs
> +        public static Pickup Get(GameObject gameObject) => Get(gameObject?.GetComponent<ItemPickupBase>());
```suggestion
        public static Pickup Get(GameObject gameObject) => Get(gameObject == null ? null : gameObject.GetComponent<ItemPickupBase>());
```

`?.` can't be used with Unity objects.

`if (pickupBase is null)` above should also be changed to `if (pickupBase == null)`.

2023-01-26 17:39 UTC, Thundermaker300 commented on Exiled.API/Features/Pickups/Pickup.cs
> +        /// <param name="gameObject"> The serial of the Pickup you search.</param>
Fix doc :trollface:

2023-01-28 11:06 UTC, iopietro approved these changes

2023-01-28 11:15 UTC, merged