Add argument and fix bug
Exiled-Team/EXILED pull request #1570
Opened 2023-01-25 23:38 UTC by louis1706

2023-01-26 15:35 UTC, iopietro requested changes

2023-01-26 15:35 UTC, iopietro commented on Exiled.Events/Handlers/Player.cs
> +        /// Called after spawned a <see cref="API.Features.Player"/>.
```suggestion
        /// Called after a <see cref="API.Features.Player"/> has spawned.
```

2023-01-28 11:06 UTC, iopietro approved these changes

2023-01-29 16:52 UTC, Thundermaker300 approved these changes

2023-01-29 16:55 UTC, merged