Make Debug config Dynamic
Exiled-Team/EXILED pull request #1571
Opened 2023-01-25 23:50 UTC by louis1706

2023-01-26 15:36 UTC, iopietro requested changes

2023-01-26 15:36 UTC, iopietro commented on Exiled.Events/Commands/Reload/Configs.cs
>              foreach (IPlugin<IConfig> plugin in Loader.Plugins)
```suggestion
            API.Features.Log.KnownDebugValues.Clear();

            foreach (IPlugin<IConfig> plugin in Loader.Plugins)
```

2023-01-27 17:09 UTC, IRacle1 approved these changes

2023-01-27 18:23 UTC, Michal78900 approved these changes

2023-01-28 11:04 UTC, iopietro approved these changes

2023-01-28 11:04 UTC, merged