Remake TriggeringTesla Event
Exiled-Team/EXILED pull request #1573
Opened 2023-01-26 14:46 UTC by louis1706

Make what config say

2023-01-26 15:06 UTC, iopietro commented
The name `TriggeringTeslaEventArgs::IsAllowed` is more intuitive and consistent as it is.

2023-01-26 19:55 UTC, Misaka-ZeroTwo commented
``IsTriggerable``, ``IsAllowed``, and ``DisableTesla``
Seems to be very confusing

2023-01-27 19:27 UTC, louis1706 commented
> ``IsTriggerable``, ``IsAllowed``, and ``DisableTesla``
> Seems to be very confusing

What would be better @Misaka-ZeroTwo ?

2023-01-27 20:38 UTC, Misaka-ZeroTwo requested changes

2023-01-27 20:38 UTC, Misaka-ZeroTwo commented on Exiled.Events/EventArgs/Player/TriggeringTeslaEventArgs.cs
> +        ///     Gets or sets a value indicating whether or not the player will be detect by the tesla.
```suggestion
        ///     Gets or sets a value indicating whether or not the player will be detected by the tesla.
```

2023-01-27 20:38 UTC, Misaka-ZeroTwo commented on Exiled.Events/EventArgs/Player/TriggeringTeslaEventArgs.cs
> +        ///     Gets or sets a value indicating whether or not the tesla is going to be activated.
```suggestion
        ///     Gets or sets a value indicating whether or not the tesla will be deactivated.
```
consistency

2023-02-06 02:04 UTC, iopietro requested changes

2023-02-06 02:08 UTC, Misaka-ZeroTwo commented on Exiled.Events/EventArgs/Player/TriggeringTeslaEventArgs.cs
> +        ///     Gets or sets a value indicating whether or not the player will triggering the tesla and going to be activated.
```suggestion
        ///     Gets or sets a value indicating whether or not the player will cause the tesla going to be activated.
```

2023-02-06 02:08 UTC, Misaka-ZeroTwo commented on Exiled.Events/EventArgs/Player/TriggeringTeslaEventArgs.cs
> +        ///     Gets or sets a value indicating whether or not the player will idling the tesla and going to be idle.
```suggestion
        ///     Gets or sets a value indicating whether or not the player will cause the tesla going to be idle.
```

2023-02-06 03:17 UTC, Misaka-ZeroTwo approved these changes

2023-02-07 20:18 UTC, Michal78900 approved these changes

2023-02-08 13:10 UTC, Thundermaker300 approved these changes

2023-02-08 13:11 UTC, merged