Player nickname change
Exiled-Team/EXILED pull request #1586
Opened 2023-02-01 19:49 UTC by louis1706

2023-02-02 16:09 UTC, iopietro requested changes

2023-02-02 16:09 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        /// Gets a value indicating whether if the player has an active CustomName.
```suggestion
        /// Gets a value indicating whether or not the player has an active CustomName.
```

2023-02-02 16:09 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        /// Gets or sets the player's nickname display to other player.
```suggestion
        /// Gets or sets the player's nickname displayed to other player.
```

2023-02-02 16:09 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        /// Gets or sets the player's nickname if null it's send the original nickname.
```suggestion
        /// Gets or sets the player's nickname, if null it sets the original nickname.
```

2023-02-04 17:37 UTC, Thundermaker300 approved these changes

2023-02-06 01:54 UTC, iopietro approved these changes

2023-02-06 01:59 UTC, merged