Fixed Player object in Joined event being null
Exiled-Team/EXILED pull request #1597
Opened 2023-02-06 03:15 UTC by Misaka-ZeroTwo

2023-02-06 03:30 UTC, Misaka-ZeroTwo commented
Player is no longer null, yet Player.UserId and Player.Nickname is still null. But it is called even after NW API join event. How could it be null when it's not in NW API???

2023-02-06 10:30 UTC, louis1706 requested changes

2023-02-06 10:30 UTC, louis1706 commented on Exiled.Events/Patches/Events/Player/Joined.cs
> +                CallEvent(__instance, out _);
this should always being call

2023-02-06 10:31 UTC, louis1706 commented on Exiled.Events/Patches/Events/Player/Joined.cs
> +                CallEvent(__instance, out _);
the code does that in IL 
```
            if (ReferenceHub.AllHubs.Count - 1 < CustomNetworkManager.slots)
                            MultiAdminFeatures.CallEvent(MultiAdminFeatures.EventType.SERVER_FULL);
            CallEvent(__instance, out _);
          ```

2023-02-06 10:31 UTC, louis1706 commented on Exiled.Events/Patches/Events/Player/Joined.cs
> +                CallEvent(__instance, out _);
the code does that in IL 
```
            if (ReferenceHub.AllHubs.Count - 1 < CustomNetworkManager.slots)
                            MultiAdminFeatures.CallEvent(MultiAdminFeatures.EventType.SERVER_FULL);
            CallEvent(__instance, out _);
          ```

2023-02-07 06:13 UTC, louis1706 approved these changes

2023-02-07 19:42 UTC, louis1706 requested changes
Fix error

2023-02-07 20:00 UTC, louis1706 approved these changes

2023-02-07 20:14 UTC, Misaka-ZeroTwo commented
Macos + github.dev moment

2023-02-07 21:18 UTC, Michal78900 commented
Update branch

2023-02-07 22:01 UTC, Misaka-ZeroTwo commented
done

2023-02-08 09:07 UTC, Michal78900 approved these changes

2023-02-08 09:29 UTC, merged