Latejoinfix
Exiled-Team/EXILED pull request #1601
Opened 2023-02-07 22:09 UTC by Undid-Iridium

for @louis1706

2023-02-07 23:34 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +using MEC;
```suggestion

```

2023-02-07 23:34 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +    using Mirror;
```suggestion
    using MEC;
    using Mirror;
```

2023-02-07 23:35 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +            }
```suggestion
            }
            
```

2023-02-08 00:14 UTC, Misaka-ZeroTwo requested changes

2023-02-08 00:14 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +            Log.Debug("1");
Debug log go brrr

2023-02-08 00:14 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +                Log.Debug("1.5");
same as above

2023-02-08 00:14 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +                Log.Debug("2");
same as above

2023-02-08 00:14 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +                Log.Debug("2.5");
same as above

2023-02-08 00:14 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +                Timing.CallDelayed(.5f, () =>
same as above

2023-02-08 00:14 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +                Log.Debug("3");
same as above

2023-02-08 00:16 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +            Log.Debug("1");
```suggestion

```

2023-02-08 00:16 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +                Log.Debug("1.5");
```suggestion

```

2023-02-08 00:16 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +                Log.Debug("2");
```suggestion
```

2023-02-08 00:16 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +                Log.Debug("2.5");
```suggestion
```

2023-02-08 00:16 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Generic/FixLateJoin.cs
> +                Timing.CallDelayed(.5f, () =>
```suggestion
```

2023-02-08 19:56 UTC, Misaka-ZeroTwo commented on Exiled.Events/EventArgs/Map/ExplodingGrenadeEventArgs.cs
> +        public ExplodingGrenadeEventArgs(Player thrower, EffectGrenade grenade, bool isAllowed = true)
breaking change?

2023-02-08 20:53 UTC, louis1706 commented on Exiled.Events/EventArgs/Map/ExplodingGrenadeEventArgs.cs
> +        public ExplodingGrenadeEventArgs(Player thrower, EffectGrenade grenade, bool isAllowed = true)
Nope

2023-02-08 23:00 UTC, Undid-Iridium commented
NOT TESTED.

2023-02-14 01:43 UTC, Undid-Iridium commented
This didn't fix anything, closing

2023-02-14 01:43 UTC, closed without merging