CustomRoles SpawnChance Feature
Exiled-Team/EXILED pull request #1613
Opened 2023-02-10 02:36 UTC by xNexus-ACS

Suggested in Discord

2023-02-10 15:39 UTC, louis1706 approved these changes
Tested by xNexus-ACS and don't see any problem

2023-02-12 22:46 UTC, iopietro requested changes

2023-02-12 22:46 UTC, iopietro commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +                    AddRole(ev.Player);
```suggestion
            if (SpawnChance > 0 && !Check(ev.Player) && ev.Player.Role.Type == Role)
            {
                if (Loader.Random.Next(100) <= SpawnChance)
                    AddRole(ev.Player);
```

2023-02-12 22:52 UTC, xNexus-ACS commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +                    AddRole(ev.Player);
Done

2023-02-12 22:55 UTC, iopietro requested changes

2023-02-12 22:55 UTC, iopietro commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +            }
```suggestion
            if (SpawnChance > 0 && !Check(ev.Player) && ev.Player.Role.Type == Role && Loader.Random.Next(100) <= SpawnChance)
                AddRole(ev.Player);
```

2023-02-12 22:57 UTC, xNexus-ACS commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +            }
Done XD

2023-02-12 23:00 UTC, iopietro approved these changes

2023-02-13 21:04 UTC, louis1706 commented
Update branch

2023-02-13 21:05 UTC, xNexus-ACS commented
> Update branch

Done

2023-02-17 15:50 UTC, Thundermaker300 approved these changes

2023-02-17 22:37 UTC, merged