Add SCP-079 API
Exiled-Team/EXILED pull request #1617
Opened 2023-02-11 18:00 UTC by Thundermaker300

2023-02-12 22:43 UTC, iopietro requested changes

2023-02-12 22:43 UTC, iopietro commented on Exiled.API/Features/Roles/Scp079Role.cs
> +            DoorStateChanger = scp079DoorAbility;
```suggestion

            DoorStateChanger = scp079DoorAbility;
```

2023-02-12 22:43 UTC, iopietro commented on Exiled.API/Features/Roles/Scp079Role.cs
> +        public int GetCost(Camera camera) => CurrentCameraSync.GetSwitchCost(camera.Base);
```suggestion
        public int GetSwitchCost(Camera camera) => CurrentCameraSync.GetSwitchCost(camera.Base);
```

2023-02-17 22:50 UTC, louis1706 approved these changes

2023-02-20 11:16 UTC, IRacle1 approved these changes

2023-02-20 15:39 UTC, merged