PlayRippleSound for 939 and UsableRipple Enum
Exiled-Team/EXILED pull request #1619
Opened 2023-02-12 17:37 UTC by xNexus-ACS

2023-02-12 21:55 UTC, Michal78900 approved these changes

2023-02-13 12:26 UTC, louis1706 requested changes

2023-02-13 12:26 UTC, louis1706 commented on Exiled.API/Features/Roles/Scp939Role.cs
> +                    SubroutineModule.TryGetSubroutine(out FootstepRippleTrigger footstepRippleTrigger);
put subroutine in memory in the cttor

2023-02-13 12:26 UTC, louis1706 commented on Exiled.API/Features/Roles/Scp939Role.cs
> +                    SubroutineModule.TryGetSubroutine(out FirearmRippleTrigger firearmRippleTrigger);
Same

2023-02-13 15:30 UTC, xNexus-ACS commented on Exiled.API/Features/Roles/Scp939Role.cs
> +                    SubroutineModule.TryGetSubroutine(out FootstepRippleTrigger footstepRippleTrigger);
Done

2023-02-13 15:30 UTC, xNexus-ACS commented on Exiled.API/Features/Roles/Scp939Role.cs
> +                    SubroutineModule.TryGetSubroutine(out FirearmRippleTrigger firearmRippleTrigger);
Done

2023-02-13 20:50 UTC, louis1706 approved these changes

2023-02-13 20:51 UTC, louis1706 commented
@xNexus-ACS  is it tested ?

2023-02-13 20:51 UTC, xNexus-ACS commented
> @xNexus-ACS is it tested ?

yes

2023-02-13 21:03 UTC, merged