More events
Exiled-Team/EXILED pull request #1620
Opened 2023-02-12 18:27 UTC by xNexus-ACS

2023-02-13 12:28 UTC, louis1706 approved these changes

2023-02-13 12:28 UTC, louis1706 commented on Exiled.Events/Patches/Events/Scp049/Consuming.cs
> +    public class Consuming
put //TODO Rework Transpiler

2023-02-13 12:28 UTC, louis1706 commented on Exiled.Events/Patches/Events/Scp049/SendingCall.cs
> +    public class SendingCall
put //TODO Rework Transpiler

2023-02-13 12:29 UTC, louis1706 commented on Exiled.Events/Patches/Events/Scp049/ActivatingSense.cs
> +    public class ActivatingSense
put //TODO Rework Transpiler

2023-02-17 22:51 UTC, louis1706 approved these changes

2023-02-18 00:57 UTC, louis1706 requested changes

2023-02-18 00:57 UTC, louis1706 commented on Exiled.Events/EventArgs/Scp049/ConsumingCorpseEventArgs.cs
> +    public class ConsumingCorpseEventArgs : IPlayerEvent, IDeniableEvent
IRagdollEvent

2023-02-18 00:57 UTC, louis1706 commented on Exiled.Events/EventArgs/Scp049/ConsumingCorpseEventArgs.cs
> +        public BasicRagdoll Ragdoll { get; }
Use Exiled API :)

2023-02-18 15:35 UTC, xNexus-ACS commented on Exiled.Events/EventArgs/Scp049/ConsumingCorpseEventArgs.cs
> +    public class ConsumingCorpseEventArgs : IPlayerEvent, IDeniableEvent
oh, right, I forgot that exists XD

2023-02-18 15:36 UTC, xNexus-ACS commented on Exiled.Events/EventArgs/Scp049/ConsumingCorpseEventArgs.cs
> +    public class ConsumingCorpseEventArgs : IPlayerEvent, IDeniableEvent
Done

2023-02-18 15:36 UTC, xNexus-ACS commented on Exiled.Events/EventArgs/Scp049/ConsumingCorpseEventArgs.cs
> +        public BasicRagdoll Ragdoll { get; }
Done

2023-02-20 00:12 UTC, louis1706 requested changes
Sorry for this request change again

2023-02-20 00:12 UTC, louis1706 commented on Exiled.Events/EventArgs/Scp049/ConsumingCorpseEventArgs.cs
> +        public byte ErrorCode { get; set; }
use Enum

2023-02-26 13:29 UTC, Thundermaker300 requested changes

2023-02-26 13:29 UTC, Thundermaker300 commented on Exiled.Events/EventArgs/Scp049/ConsumingCorpseEventArgs.cs
> +        ///     Gets or sets a value indicating whether or not the server will send 049 information on the recall.
Wrong documentation

2023-02-26 13:34 UTC, xNexus-ACS commented on Exiled.Events/EventArgs/Scp049/ConsumingCorpseEventArgs.cs
> +        ///     Gets or sets a value indicating whether or not the server will send 049 information on the recall.
Done

2023-02-28 15:28 UTC, IRacle1 approved these changes

2023-02-28 15:52 UTC, louis1706 approved these changes

2023-02-28 15:52 UTC, merged