Room local position
Exiled-Team/EXILED pull request #1659
Opened 2023-03-03 10:36 UTC by louis1706

2023-03-03 18:16 UTC, IRacle1 approved these changes

2023-03-06 13:10 UTC, Thundermaker300 requested changes

2023-03-06 13:10 UTC, Thundermaker300 commented on Exiled.API/Features/Room.cs
> +        /// Send you the position from world space to local space.
```suggestion
        /// Returns the local space position from the world space position.
```

2023-03-06 13:10 UTC, Thundermaker300 commented on Exiled.API/Features/Room.cs
> +        /// <returns>Local position based with room.</returns>
```suggestion
        /// <returns>Local position, based on the room.</returns>
```

2023-03-06 13:12 UTC, Thundermaker300 commented on Exiled.API/Features/Room.cs
> +        /// Returns the local space position from the world space position.
```suggestion
        /// Returns the local space position, based on a world space position.
```

2023-03-06 13:12 UTC, Thundermaker300 approved these changes

2023-03-06 13:15 UTC, merged