Implementing new Property
Exiled-Team/EXILED pull request #1708
Opened 2023-04-04 20:56 UTC by louis1706

2023-08-10 17:59 UTC, Misaka-ZeroTwo reviewed
should be 100 instead of 101?

2023-08-10 17:59 UTC, Misaka-ZeroTwo commented on Exiled.API/Features/Items/Armor.cs
> +                if (value is > 101 or < 0)
```suggestion
                if (value is > 100 or < 0)
```

2023-08-10 17:59 UTC, Misaka-ZeroTwo commented on Exiled.API/Features/Items/Armor.cs
> +                if (value is > 101 or < 0)
```suggestion
                if (value is > 100 or < 0)
```

2023-08-10 17:59 UTC, Misaka-ZeroTwo commented on Exiled.API/Features/Pickups/BodyArmorPickup.cs
> +                if (value is > 101 or < 0)
```suggestion
                if (value is > 100 or < 0)
```

2023-08-10 17:59 UTC, Misaka-ZeroTwo commented on Exiled.API/Features/Pickups/BodyArmorPickup.cs
> +                if (value is > 101 or < 0)
```suggestion
                if (value is > 100 or < 0)
```

2023-08-11 15:46 UTC, NaoUnderscore requested changes

2023-08-11 15:46 UTC, NaoUnderscore commented on Exiled.API/Features/Pickups/Pickup.cs
> +            if (item is not null)
Use conditional expression

2023-08-11 15:46 UTC, NaoUnderscore commented on Exiled.API/Features/Pickups/Pickup.cs
> +            if (item is not null)
Same as above

2023-08-11 16:00 UTC, merged