Cleanup methods for Map and Fix typo in Recontainer
Exiled-Team/EXILED pull request #1712
Opened 2023-04-11 23:34 UTC by xNexus-ACS

2023-04-12 19:12 UTC, louis1706 requested changes

2023-04-12 19:12 UTC, louis1706 commented on Exiled.API/Features/Map.cs
> +            var pickups = Object.FindObjectsOfType<ItemPickupBase>();
Pickup.List Exist !??!

2023-04-12 19:12 UTC, louis1706 commented on Exiled.API/Features/Map.cs
> +            var basicRagDolls = Object.FindObjectsOfType<BasicRagdoll>();
Ragdoll.List !?!?

2023-04-12 19:12 UTC, louis1706 commented on Exiled.API/Features/Recontainer.cs
> +        public static bool IsContainmentZoneOpen
BreakingChange put //TODO : IsContainmentZoneOpen

2023-04-12 19:13 UTC, louis1706 requested changes

2023-04-12 19:13 UTC, louis1706 commented on Exiled.API/Features/Map.cs
> +        public static void CleanAllItems(List<Pickup> pickups)
IEnumerable

2023-04-12 19:13 UTC, louis1706 commented on Exiled.API/Features/Map.cs
> +        public static void CleanAllRagdolls(List<Ragdoll> ragDolls)
IEnumerable

2023-04-12 23:19 UTC, xNexus-ACS commented on Exiled.API/Features/Map.cs
> +            var pickups = Object.FindObjectsOfType<ItemPickupBase>();
fixed

2023-04-12 23:19 UTC, xNexus-ACS commented on Exiled.API/Features/Recontainer.cs
> +        public static bool IsContainmentZoneOpen
fixed

2023-04-12 23:19 UTC, xNexus-ACS commented on Exiled.API/Features/Map.cs
> +        public static void CleanAllItems(List<Pickup> pickups)
same as above XD

2023-04-12 23:19 UTC, xNexus-ACS commented on Exiled.API/Features/Map.cs
> +        public static void CleanAllRagdolls(List<Ragdoll> ragDolls)
:)

2023-04-13 21:06 UTC, louis1706 requested changes

2023-04-13 21:06 UTC, louis1706 commented on Exiled.API/Features/Map.cs
> +            foreach (Ragdoll ragDoll in Ragdoll.List)
.ToList()

2023-04-13 21:06 UTC, louis1706 commented on Exiled.API/Features/Map.cs
> +            foreach (Pickup pickup in Pickup.List)
.ToList()

2023-04-21 19:36 UTC, xNexus-ACS commented
also tested

2023-04-22 03:24 UTC, Misaka-ZeroTwo approved these changes

2023-05-10 23:27 UTC, louis1706 approved these changes

2023-05-13 23:38 UTC, Thundermaker300 approved these changes

2023-05-13 23:38 UTC, merged