New zombie events
Exiled-Team/EXILED pull request #1720
Opened 2023-04-14 19:15 UTC by VALERA771

Checklist:
* Test Consuming
* Fix AttackingEventArgs::IsAllowed (error in patch)

2023-04-15 02:41 UTC, xNexus-ACS commented
@VALERA771 the consuming event already exists

2023-04-15 02:42 UTC, xNexus-ACS commented
and don't name Hurting to the Scp0492 Attack, bcs it will conflict with the normal one

2023-04-15 07:37 UTC, louis1706 commented
Scp0492 don't need this event Player HurtingEvent can cancel it too

2023-04-15 12:13 UTC, xNexus-ACS commented
@VALERA771 lmao instead of putting the other event in Obsolete, just move it to the correct folder

2023-04-15 12:50 UTC, VALERA771 commented
Gonna test it one day

2023-04-15 13:15 UTC, xNexus-ACS commented
if you can, please use the old transpiler, same for the old ConsumingEvent constructor @VALERA771

2023-04-15 13:53 UTC, VALERA771 commented
> if you can, please use the old transpiler, same for the old ConsumingEvent constructor @VALERA771 if you can, do not change anything in the consuming event

But why? And if remove = no changed, so then I can just close pr

2023-04-15 14:17 UTC, louis1706 commented
> > if you can, please use the old transpiler, same for the old ConsumingEvent constructor @VALERA771 if you can, do not change anything in the consuming event
> 
> But why? And if remove = no changed, so then I can just close pr

mostly do not make useless change

2023-04-15 14:20 UTC, louis1706 requested changes

2023-04-15 14:20 UTC, louis1706 commented on Exiled.Events/EventArgs/Scp0492/ConsumingCorpseEventArgs.cs
> +        public ConsumingCorpseEventArgs(ReferenceHub player, BasicRagdoll ragDoll, byte error, bool isAllowed = true)
keep ZombieConsumeAbility.ConsumeError and don't use byte

2023-04-15 14:21 UTC, xNexus-ACS commented
> > if you can, please use the old transpiler, same for the old ConsumingEvent constructor @VALERA771 if you can, do not change anything in the consuming event
> 
> But why? And if remove = no changed, so then I can just close pr

yeah ignore what I said, srry

2023-04-15 19:41 UTC, louis1706 requested changes

2023-04-15 19:41 UTC, louis1706 commented on Exiled.Events/Patches/Events/Scp0492/Consuming.cs
> +                new(OpCodes.Stfld, Field(typeof(RagdollAbilityBase<ZombieRole>), nameof(RagdollAbilityBase<ZombieRole>._errorCode))),
Add comment to explain what the code does

2023-04-16 00:35 UTC, joker-119 commented
> @VALERA771 lmao instead of putting the other event in Obsolete, just move it to the correct folder without creating a new one, same for the handlers and the patch

That creates a breaking change since the reference will change

2023-04-16 11:01 UTC, VALERA771 commented
> > @VALERA771 lmao instead of putting the other event in Obsolete, just move it to the correct folder without creating a new one, same for the handlers and the patch
> 
> That creates a breaking change since the reference will change

Any ways to remove breaking change or leave draft till new major release?

2023-04-18 11:51 UTC, louis1706 approved these changes
Accepted for Exiled7 (will just need a require testing)

2023-05-09 07:04 UTC, VALERA771 commented
7.0.0 soon. I'm making this not draft

2023-05-10 15:41 UTC, Misaka-ZeroTwo commented
tested, works fine

2023-05-14 20:45 UTC, louis1706 approved these changes

2023-06-25 10:29 UTC, louis1706 commented
Transpiler need to be check again

2023-06-28 06:54 UTC, Misaka-ZeroTwo commented
Do not merge due to break change

2023-08-10 21:13 UTC, VALERA771 commented
Yay! Milestone

2023-08-31 07:25 UTC, merged