This is not lunge fix
Exiled-Team/EXILED pull request #1755
Opened 2023-04-24 20:24 UTC by VALERA771

"Fix" for #1734. We've tried

2023-04-24 23:52 UTC, louis1706 approved these changes

2023-04-24 23:52 UTC, louis1706 commented
i miss something keep , IDeniableEvent and add TODO to remove it

2023-04-25 06:00 UTC, ITeMbI4 commented
If this event called after, why you can't name it `LungedEventArgs`, and can you please add `ev.Target` property to it?

2023-04-25 06:04 UTC, ITeMbI4 commented
@louis1706 why you approve this?
TriggerLunge called before, not after...

2023-04-25 06:05 UTC, ITeMbI4 commented
And what about https://github.com/Exiled-Team/EXILED/pull/1754 ?

2023-04-25 07:04 UTC, VALERA771 commented
IsAllowed there cause desync

2023-04-25 07:11 UTC, VALERA771 commented
> i miss something keep , IDeniableEvent and add TODO to remove it

Maybe just remove IDeniableEvent?

2023-04-25 20:34 UTC, Misaka-ZeroTwo commented
Why are you changing the lunging event but not adding another lunged event?

2023-04-25 21:40 UTC, Misaka-ZeroTwo commented
> Like make this ev args and event obsolete and make lunged?

Don't touch anything on lunging event, just do make another lunged event like you did before in #1709

2023-04-25 21:54 UTC, Misaka-ZeroTwo commented
Dunno why you are putting things in obsolete, cuz #1754 will fix the lunging event.

2023-04-25 22:14 UTC, VALERA771 commented
> Dunno why you are putting things in obsolete, cuz #1754 will fix the lunging event.

Same thing I done in #1709

2023-04-25 22:21 UTC, Misaka-ZeroTwo commented
> Same thing I done in #1709. And if it will fix I gonna just close this PR cuz they're gonna be same

No, the purpose of Lunged event is that it invokes after the event. Just like Dying and Died. And they can be used with different purposes.

2023-04-25 22:21 UTC, Misaka-ZeroTwo commented
Also you could add targets in Lunged eventarg

2023-04-25 22:26 UTC, VALERA771 commented
> Also you could add targets in Lunged eventarg

Then it'll be just like hurting, isn't it?

2023-04-26 08:02 UTC, VALERA771 commented
Yes. If I add target it'll be just like hurting or dying ev

2023-04-26 08:17 UTC, Misaka-ZeroTwo commented
> Yes. If I add target it'll be just like hurting or dying ev


It can just be get only.

2023-04-26 08:55 UTC, VALERA771 commented
Okay, let it be like this

2023-05-23 17:30 UTC, louis1706 requested changes
can you add a Void Prefix for Lunging (with Obsolete IsAllowed)

2023-05-25 20:16 UTC, louis1706 approved these changes

2023-05-26 11:55 UTC, joker-119 commented
Fix merge conflicts

2023-05-26 16:49 UTC, louis1706 requested changes

2023-05-26 16:49 UTC, louis1706 commented on Exiled.Events/EventArgs/Scp939/LungedEventArgs.cs
> +            Target = target == null ? null : Player.Get(target);
Player.Get(null) should return null; so the check is useless

2023-06-27 17:10 UTC, Misaka-ZeroTwo requested changes

2023-06-27 17:10 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Events/Scp939/Lunge.cs
> +            LungingEventArgs ev = new(Player.Get(__instance.Owner));
Lunged?

2023-06-27 17:10 UTC, Misaka-ZeroTwo commented on Exiled.Events/Patches/Events/Scp939/Lunge.cs
> +            Handlers.Scp939.OnLunging(ev);
same as above

2023-06-27 17:14 UTC, Misaka-ZeroTwo commented on Exiled.Events/EventArgs/Scp939/LungingEventArgs.cs
> +        public LungingEventArgs(Player player)
breaking change. No need to change anything for LungingEventArgs,

2023-08-31 16:18 UTC, closed without merging