Detonating prefix
Exiled-Team/EXILED pull request #1756
Opened 2023-04-25 11:50 UTC by VALERA771

Idk why there was NW event. Maybe it's necessary but ye.

2023-04-25 12:39 UTC, VALERA771 commented
Tested

2023-05-06 16:37 UTC, louis1706 approved these changes

2023-05-09 21:55 UTC, IRacle1 reviewed
Lgtm

2023-05-09 21:55 UTC, IRacle1 commented on Exiled.Events/Patches/Events/Warhead/Detonated.cs
> +            newInstructions[0].WithLabels(continueLabel);
Little thing, dont use `.WithLabels` in that case, use `instructions[0].labels.Add(label)`. 
It is better to use `.WithLabels` only for situations when you'll should keep your modified instruction and do something with that later

2023-05-09 21:55 UTC, IRacle1 commented on Exiled.Events/Patches/Events/Warhead/Detonated.cs
> +                yield return instruction;
Using `for` with `z` iterator instead of `foreach` is a exiled tradition, dont break it🙃

2023-05-09 21:55 UTC, IRacle1 commented on Exiled.Events/Patches/Events/Warhead/Detonated.cs
> +                    new(OpCodes.Ldloc_S, ev.LocalIndex),
Another thing that doesn't matter so much, it is better to prefer using short forms of op codes (with `_S` postfix).
`Stloc` can be replaced by `Stloc_S`

(But you can ignore it rly, this is the most minimal optimization that can be)

2023-05-10 02:12 UTC, joker-119 requested changes

2023-05-10 02:12 UTC, joker-119 commented on Exiled.Events/Patches/Events/Warhead/Detonated.cs
> +            newInstructions[0].WithLabels(continueLabel);
instruction[0].labels.Add(label) is more performant.

2023-05-10 02:12 UTC, joker-119 commented on Exiled.Events/Patches/Events/Warhead/Detonated.cs
> +                    new(OpCodes.Stloc, ev.LocalIndex),
`Stloc_S` would be more performant here.

2023-05-10 02:12 UTC, joker-119 commented on Exiled.Events/Patches/Events/Warhead/Detonated.cs
> -            for (int z = 0; z < newInstructions.Count; z++)
Changing this is a loss in performance as we're now allocating a variable for each instruction in the element when we don't need to. This is the main reason I'm requiring changes before accepting this PR

2023-05-22 09:54 UTC, louis1706 approved these changes

2023-05-25 20:10 UTC, louis1706 requested changes
Resolve conflict

2023-05-26 16:47 UTC, louis1706 requested changes

2023-05-26 16:47 UTC, louis1706 commented on Exiled.Events/Events.cs
> +            EventManager.UnregisterEvents<Handlers.Player>(this);
just remove it no ?

2023-05-26 16:47 UTC, louis1706 commented on Exiled.Events/Events.cs
> +            EventManager.RegisterEvents<Handlers.Player>(this);
Same things

2023-06-12 20:30 UTC, louis1706 requested changes
Resolve conflict

2023-06-13 10:57 UTC, louis1706 approved these changes

2023-06-25 10:29 UTC, louis1706 commented
Transpiler need to be check again

2023-08-12 18:26 UTC, VALERA771 commented
77 commits... how long this thread wasn't updated?

2023-08-12 23:12 UTC, louis1706 commented
> 77 commits... how long this thread wasn't updated?

now

2023-08-13 09:25 UTC, joker-119 approved these changes

2023-08-13 09:25 UTC, merged