Respawing team event fix
Exiled-Team/EXILED pull request #1758
Opened 2023-04-25 20:36 UTC by VALERA771

Returned wrong value because patch got list before removing values.

Fix for #1757

2023-04-25 20:52 UTC, Misaka-ZeroTwo requested changes
You also need to handle the logic which when ``ev.MaximumRespawnAmount`` got set to a lower value, ``ev.Players`` needs to be adjusted.

2023-04-25 21:17 UTC, Misaka-ZeroTwo reviewed
accidentally added a file?

2023-04-25 21:18 UTC, VALERA771 commented
Oops

2023-04-25 21:19 UTC, Misaka-ZeroTwo commented
also it still doesn't solve the problem, because ev.Players only gets adjusted when the eventargs is constructed.

2023-04-25 21:30 UTC, VALERA771 commented
Okay, now should be fine

2023-04-25 22:16 UTC, VALERA771 commented
> I feel like it's better to just change the setter in the eventarg instead. cuz that way ev.Players will be the same.

Okay but I don't get what is wrong. ev.Players will be same but list will be adjusted anyway

2023-04-25 22:23 UTC, Misaka-ZeroTwo commented
For example
```
ev.MaximumRespawnAmount = 10; // smaller than current ev.Players
List<Player> spawnablePlayers = ev.Players; // this won't work if you are changing afterwards
```

2023-04-25 22:27 UTC, VALERA771 commented
> For example
> 
> ```
> 
> ev.MaximumRespawnAmount = 10; // smaller than current ev.Players number
> 
> List<Player> spawnablePlayers = ev.Players; // this won't work if you are changing afterwards
> 
> ```

In this case yeah. And it'll be easier

2023-04-26 10:25 UTC, VALERA771 commented
Tested

2023-04-28 14:42 UTC, VALERA771 commented
Small thing, I think requires-testing label should be removed

2023-05-06 16:39 UTC, louis1706 requested changes

2023-05-06 16:39 UTC, louis1706 commented on Exiled.Events/EventArgs/Server/RespawningTeamEventArgs.cs
> +                    return;
not required

2023-05-10 02:09 UTC, merged