ThrowingRequest
Exiled-Team/EXILED pull request #1759
Opened 2023-04-26 00:54 UTC by Misaka-ZeroTwo

Obsolete IsAllowed to "fix" #1746

2023-05-06 16:41 UTC, louis1706 approved these changes

2023-05-06 16:42 UTC, louis1706 requested changes
Oups

2023-05-06 16:42 UTC, louis1706 commented on Exiled.Events/EventArgs/Player/ThrowingRequestEventArgs.cs
> +    public class ThrowingRequestEventArgs : IPlayerEvent
this change should not be done you need to make a TODO

2023-05-06 16:42 UTC, louis1706 requested changes
Oups

2023-05-09 05:36 UTC, IRacle1 approved these changes

2023-05-09 10:02 UTC, Misaka-ZeroTwo commented
Do not merge, will make it a breaking change since it’s exiled 7

2023-05-09 16:43 UTC, louis1706 approved these changes

2023-05-09 16:43 UTC, louis1706 approved these changes

2023-05-10 02:08 UTC, merged