Activate warhead ev fix
Exiled-Team/EXILED pull request #1778
Opened 2023-05-10 18:03 UTC by VALERA771

Idk why there is long check for access but if remove it everything works fine!

Fix for #1771

2023-05-12 08:16 UTC, Misaka-ZeroTwo requested changes
By placing it before ``OnInteract``, you are making the event not fire when player doesn't have sufficient permission.

2023-05-12 23:57 UTC, joker-119 commented
This 'fix' removes a core feature of the event for the reason stated in Misaka's comment, please change this so that it doesn't remove functionality from the event to fix the issue.

2023-05-13 07:50 UTC, VALERA771 commented
Also tested

2023-05-13 08:43 UTC, Misaka-ZeroTwo reviewed
Why not insert after ``if (!this.ChckDis(player.Position)``?

2023-05-13 09:24 UTC, VALERA771 commented
> Why not insert after `if (!this.ChckDis(player.Position)`?

Cuz there is some troubles with labels that I couldn't fix

2023-05-17 15:42 UTC, louis1706 requested changes

2023-05-17 15:42 UTC, louis1706 commented on Exiled.Events/Patches/Events/Player/ActivatingWarheadPanel.cs
> +            newInstructions[index].labels.Add(retLabel);
Rename it continueLabel or anything you want but not ret since it's will not going to a return direclty

2023-05-21 12:15 UTC, louis1706 approved these changes

2023-05-26 11:53 UTC, merged