Custom roles fix
Exiled-Team/EXILED pull request #1800
Opened 2023-05-15 16:19 UTC by VALERA771

Just changed the calling assembly, cuz in case if we call RegisterRoles(bool, object) calling assembly will be custom roles

2023-05-15 16:19 UTC, VALERA771 commented
Fix for #1797 and tested by reporter

2023-05-20 20:01 UTC, IRacle1 approved these changes

2023-05-21 12:22 UTC, louis1706 requested changes

2023-05-21 12:22 UTC, louis1706 commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +        public static IEnumerable<CustomRole> RegisterRoles(bool skipReflection = false, object? overrideClass = null, bool inheritAttributes = true, Assembly? assembly = null)
this is a breaking change please make a copy with Obsolete

2023-05-21 17:18 UTC, louis1706 approved these changes

2023-05-26 11:49 UTC, merged