Allow editing tickets in Escaping event
Exiled-Team/EXILED pull request #1815
Opened 2023-05-21 15:42 UTC by 4310V343k

also fixes #1810

2023-05-21 16:09 UTC, Misaka-ZeroTwo commented
Should be getting tickets, not editing tickets.

2023-05-21 17:49 UTC, Misaka-ZeroTwo commented on Exiled.Events/EventArgs/Player/EscapingEventArgs.cs
> +        public Dictionary<SpawnableTeamType, float> TicketsToChange { get; }
That's get only.

2023-05-21 19:02 UTC, Misaka-ZeroTwo commented on Exiled.Events/EventArgs/Player/EscapingEventArgs.cs
> +        public Dictionary<SpawnableTeamType, float> TicketsToChange { get; }
Oh ok, then just do `get; set;`? Because that indicates the property can be edited.

2023-05-22 09:01 UTC, louis1706 requested changes
also there no need to make a Dictionary and new argument for the ctor

2023-05-22 09:01 UTC, louis1706 commented
this PR also conflict with #1807  (that not a requested change it's only informative)

2023-05-23 09:51 UTC, louis1706 approved these changes

2023-05-25 15:49 UTC, VALERA771 commented
Why you've created 2 new constructors?

2023-05-25 16:28 UTC, merged