Event stuff
Exiled-Team/EXILED pull request #1818
Opened 2023-05-22 21:05 UTC by VALERA771

* Convert some prefixes to transpilers cuz they're using NW event system which'll be updated in 13.0 NWAPI
* Adds Scanning event for 079

I'm also planning to convert some of prefixes with TODO to transpilers

2023-05-22 21:53 UTC, VALERA771 commented
Few events have major changes (removing setters)

2023-05-23 09:46 UTC, louis1706 requested changes

2023-05-23 16:41 UTC, VALERA771 commented
Everything new tested. All transpilers except Stalking working fine

2023-05-23 17:02 UTC, louis1706 approved these changes

2023-05-26 11:49 UTC, merged

2023-05-31 07:16 UTC, Misaka-ZeroTwo commented
Stalking doesn't work.