Room::ReverseLocalPosition
Exiled-Team/EXILED pull request #1833
Opened 2023-05-26 23:52 UTC by louis1706

2023-05-27 09:58 UTC, Misaka-ZeroTwo commented
`WorldPosFromLocalPos`, `PositionFromLocalPos`. Aren't great name but I don't feel ReverseLocalPosition is a intuitive name.

2023-05-27 09:59 UTC, louis1706 commented
yeah i was not knowing what name to give for it

2023-06-06 18:36 UTC, FakeMan2332 commented on Exiled.API/Features/Room.cs
> +        /// Returns the World position position, based on a local space position.
position postion

2023-06-06 18:37 UTC, FakeMan2332 commented on Exiled.API/Features/Room.cs
> +        /// Returns the World position position, based on a local space position.
```suggestion
        /// Returns the World position, based on a local space position.
```

2023-08-11 16:42 UTC, NaoUnderscore requested changes

2023-08-11 16:42 UTC, NaoUnderscore commented on Exiled.API/Features/Room.cs
> +        public Vector3 ReverseLocalPosition(Vector3 offset) => Transform.InverseTransformPoint(offset);
Just name it `WorldPosition`

2023-08-12 10:42 UTC, merged