(ru_RU) Russian localization update
Exiled-Team/EXILED pull request #1890
Opened 2023-06-23 15:42 UTC by swdmeow

* Update README-Русский.md

2023-06-24 09:39 UTC, IRacle1 requested changes

2023-06-24 09:39 UTC, IRacle1 commented on Localization/README-Русский.md
> +Например, если вы запускаете сервер с единственным плагином `Exiled.Events` и хотите добавить новый, вам не нужно перезагружать сервер для выполнения этой задачи. Вы можете просто использовать команд
`в RemoteAdmin или консоль сервера` думаю будет логичнее

2023-06-24 10:07 UTC, swdmeow commented on Localization/README-Русский.md
> +Например, если вы запускаете сервер с единственным плагином `Exiled.Events` и хотите добавить новый, вам не нужно перезагружать сервер для выполнения этой задачи. Вы можете просто использовать команд
исправил

2023-06-24 11:38 UTC, IRacle1 approved these changes

2023-06-25 15:41 UTC, louis1706 approved these changes

2023-06-25 15:41 UTC, merged