Fix pickup.list being empty
Exiled-Team/EXILED pull request #1902
Opened 2023-06-25 10:09 UTC by louis1706

2023-06-25 10:25 UTC, IRacle1 requested changes
Idk if that change can break anything or not, our PickupAPI is very complex

2023-06-25 10:25 UTC, IRacle1 commented on Exiled.API/Features/Pickups/Pickup.cs
> +                BaseToPickup.Add(pickupBase, this);
Im pretty sure it is useless, for getting/creating pickups we use `Pickup::Get`, who has that check

2023-06-25 10:25 UTC, IRacle1 commented on Exiled.Events/Events.cs
> +            ItemPickupBase.OnPickupAdded += x => Pickup.BaseToPickup.Add(x, new Pickup(x));
dont use `new Pickup(x)` use `Pickup::Get`

2023-06-25 17:33 UTC, IRacle1 requested changes

2023-06-25 17:33 UTC, IRacle1 commented on Exiled.Events/Events.cs
> +            ItemPickupBase.OnPickupAdded += x => Pickup.BaseToPickup.Add(x, Pickup.Get(x));
oh, bruh, i forgot that `Pickup.Get(x)` includes adding to list, just keep `Pickup.Get` and remove `Pickup.BaseToPickup.Add`

2023-06-25 18:09 UTC, IRacle1 commented on Exiled.Events/Events.cs
> +            ItemPickupBase.OnPickupAdded += x => Pickup.BaseToPickup.Add(x, Pickup.Get(x));
```suggestion
            ItemPickupBase.OnPickupAdded += x => Pickup.Get(x);
```

2023-06-25 18:17 UTC, IRacle1 approved these changes

2023-06-26 08:51 UTC, louis1706 commented
@joker-119

2023-06-27 02:41 UTC, joker-119 commented
I am failing to see how this would possibly fix the Pickup.List being empty, when you are removing the only line of code that adds to the dictionary for pickups.

2023-06-27 04:06 UTC, merged