Removed option to set ID
Exiled-Team/EXILED pull request #1915
Opened 2023-06-29 01:28 UTC by NotIntense

Removed the option to set the ID, and is now determined by player count and NPC count. Server handles it and can break when trying to set it manually

2023-06-29 07:28 UTC, Misaka-ZeroTwo requested changes

2023-06-29 07:28 UTC, Misaka-ZeroTwo commented on Exiled.API/Features/Npc.cs
> +            FakeConnection fakeConnection = new(Player.List.Count + Npc.List.Count);
That would cause duplicate ids.

2023-06-29 07:28 UTC, Misaka-ZeroTwo commented on Exiled.API/Features/Npc.cs
> +            FakeConnection fakeConnection = new(Player.List.Count + Npc.List.Count);
Also breaking change

2023-06-29 07:53 UTC, louis1706 commented
I closed the PR this is clearly not how it should be handled to add id for npc automatically

2023-06-29 07:53 UTC, closed without merging

2023-06-30 06:41 UTC, joker-119 commented
Fixed without breaking changes in [ee8becb](https://github.com/Exiled-Team/EXILED/commit/ee8becbbfaac397d9fde071711a748e54b55ac58)