Update README.md
Exiled-Team/EXILED pull request #1922
Opened 2023-06-30 11:37 UTC by Misaka-ZeroTwo

2023-06-30 12:39 UTC, IRacle1 approved these changes

2023-06-30 13:05 UTC, joker-119 commented
Why are you sending them to a random docs page for enums??

2023-06-30 13:20 UTC, louis1706 requested changes
You will need to update Translation File in the same PR

2023-09-14 22:45 UTC, louis1706 commented
reopen it if you want

2023-09-14 22:45 UTC, closed without merging