New 939 event
Exiled-Team/EXILED pull request #1931
Opened 2023-07-01 17:11 UTC by VALERA771

Fires then scp attacks ~air~ noting

2023-07-01 17:12 UTC, VALERA771 commented
Tested

2023-07-04 01:21 UTC, Thundermaker300 approved these changes
LGTM, needs someone who can read IL

2023-07-04 07:39 UTC, louis1706 requested changes

2023-07-04 07:39 UTC, louis1706 commented on Exiled.Events/Patches/Events/Scp939/Clawed.cs
> +            newInstructions.InsertRange(
Not needed

2023-07-31 21:33 UTC, louis1706 approved these changes

2023-08-10 21:33 UTC, merged