Add keypress stuffs
Exiled-Team/EXILED pull request #2002
Opened 2023-08-17 04:07 UTC by joker-119

Allows players to manage having multiple on-use abilities in a single Custom Role easier, without the need for the old `cmdbind` system.

While cmdbind stuff will still work perfectly the same, this is a hugely breaking change to the ActiveAbility class, that will require active code changes in most plugins using them.

This allows active abilities to be used via simple keypresses, regardless of the role you are playing and how many abilities that role has.

Keypress guide:
1x Alt - Use currently selected ability (if any)
2x Alt - Switch to next ability (if possible)
C + 2x Alt - Switch to previous ability (if possible)
C + 1x Alt - Display information on current selected ability, including name, description, duration, cooldown and current usability status (will display remaining cooldown if it's on cooldown still)

Video Demonstration:
https://discord.com/channels/656673194693885975/668651891944587264/1141582398178459659

This PR will be marked as DNM until EXILED has begun accepting breaking changed for 8.0.0

2023-08-17 14:35 UTC, xNexusACS commented
imagine copying other frameworks idea & stuff but changing the code

2023-08-17 20:29 UTC, louis1706 commented
> imagine copying other frameworks idea & stuff but changing the code, cringe, literally the synapse keypress system but edited

Bruh you really thinks than joker / nao was looking at synapse for copying code even me wasn't knowing that.

2023-08-18 00:14 UTC, joker-119 commented
> imagine copying other frameworks idea & stuff but changing the code, cringe, literally the synapse keypress system but edited

Coincidence since Synapse hasn't even been a thought in my mind since like.. SL 11.1, lol

2023-08-31 01:00 UTC, louis1706 requested changes

2023-08-31 01:00 UTC, louis1706 commented on Exiled.CustomRoles/API/Features/ActiveAbility.cs
> +            if (SelectedPlayers.Contains(player))
This check is not needed

2023-08-31 01:00 UTC, louis1706 commented on Exiled.CustomRoles/API/Features/KeypressActivator.cs
> +            Log.Warn($"{player.Nickname}: {pressCount} {(player.Role is FpcRole fpc ? fpc.MoveState : false)}");
Debug instead ?

2023-08-31 01:00 UTC, louis1706 commented on Exiled.CustomRoles/API/Features/KeypressActivator.cs
> +                    }
Why not just checking before the number of ability ? If( .Count <= 1) return false;

2023-08-31 01:27 UTC, louis1706 approved these changes

2023-08-31 01:42 UTC, merged