ChangedItemEventArgs : IItemEvent
Exiled-Team/EXILED pull request #2018
Opened 2023-08-29 22:23 UTC by louis1706

2023-08-29 22:23 UTC, Thundermaker300 approved these changes

2023-08-30 17:44 UTC, VALERA771 commented
Why not move NewItem to obsolete?

2023-08-30 18:08 UTC, joker-119 commented
It should be marked obsolete for the sake of removing it later.

2023-08-30 18:39 UTC, louis1706 commented
> It should be marked obsolete for the sake of removing it later.
i thinks it's better to keep the one with NewItem even if it's the same than Item to keep than it's more intuitive

2023-08-30 18:49 UTC, IRacle1 approved these changes

2023-08-30 18:49 UTC, joker-119 commented
I respectfully disagree, there's no reason for that kind of redundancy, not to mention if you use ev.Item, in this way, it'll be calling two property get methods instead of one, meaning it's objectively slower.

2023-08-30 20:11 UTC, VALERA771 requested changes

2023-08-30 20:11 UTC, VALERA771 commented on Exiled.Events/EventArgs/Player/ChangedItemEventArgs.cs
> +        public Item NewItem => NewItem;
```suggestion
        public Item NewItem => Item;
```

2023-08-31 00:43 UTC, Misaka-ZeroTwo approved these changes

2023-08-31 00:47 UTC, merged