No more TODO and obsoletes in API
Exiled-Team/EXILED pull request #2028
Opened 2023-08-31 20:32 UTC by VALERA771

2023-08-31 20:53 UTC, louis1706 requested changes
that the only change than need to be reverted in my opinion everything else is fine

2023-08-31 20:53 UTC, louis1706 commented on Exiled.API/Features/Items/Firearm.cs
> -                _ => throw new NotImplementedException("Should never happend"),
Why ?

2023-08-31 21:26 UTC, louis1706 approved these changes

2023-08-31 22:52 UTC, Misaka-ZeroTwo approved these changes

2023-09-01 00:38 UTC, Thundermaker300 approved these changes

2023-09-01 00:39 UTC, merged