Remove Singleton from Exiled.Example
Exiled-Team/EXILED pull request #2057
Opened 2023-09-03 16:47 UTC by Misfiy

crazy? i was crazy once

2023-09-03 16:50 UTC, Misfiy commented
i take it back

2023-09-03 17:38 UTC, louis1706 approved these changes

2023-09-04 01:27 UTC, Ruemena commented
imo i think that at the very least the constructor should be private

2023-09-14 20:18 UTC, Thundermaker300 requested changes

2023-09-14 20:18 UTC, Thundermaker300 commented on Exiled.Example/Example.cs
> +        public static Example Instance;
```suggestion
        public static Example Instance { get; set; }
```
Property

2023-10-01 16:51 UTC, Jesus-QC commented
This shouldnt be approved, it showcases how if there ia already an existing static instance and the constructor is private it will take that one instance instead of making a new one.

2023-10-06 17:28 UTC, closed without merging