add TargetOffset
Exiled-Team/EXILED pull request #2114
Opened 2023-09-20 01:59 UTC by Ruemena

this adds targetoffset, a way to change the number of targets displayed to scps. this allows you to implement npcs, custom roles, etc that aren't displayed as targets (among other things)
TargetOffset is added to the total number of targets - it doesn't allow you to directly set the number of targets directly, as that would break compatibility between plugins
UpdateTargetCount() forces an update in the number of targets. this is necessary because you may not want to immediately update the number of targets displayed.

**THIS MAY STILL NEED SOME REFINING** as rn there's no way to not have an incredibly quick increase followed by a decrease or vice versa when modifying the targetoffset and spawning or killing a player. this could prob be fixed by sending a sync var on the spawning event, or something like that

2023-09-20 13:04 UTC, louis1706 requested changes
the Patches should be ine Generic file not Fixed

2023-09-20 13:47 UTC, louis1706 requested changes

2023-09-20 13:47 UTC, louis1706 commented on Exiled.Events/Patches/Generic/TargetOffset.cs
> +namespace Exiled.Events.Patches.Events.Player
This is not the correct 'amespace

2023-09-20 14:04 UTC, Ruemena commented on Exiled.Events/Patches/Generic/TargetOffset.cs
> +namespace Exiled.Events.Patches.Events.Player
fixed

2023-09-26 08:15 UTC, louis1706 requested changes
Fix Build Error

2023-10-05 14:03 UTC, louis1706 commented on Exiled.API/Features/Round.cs
> +        public static int TargetOffset { get; set; } = 0;
```suggestion
        public static int TargetOffset { get; set; }
```

2023-10-08 18:23 UTC, louis1706 approved these changes

2023-10-10 21:50 UTC, NaoUnderscore requested changes

2023-10-10 21:50 UTC, NaoUnderscore commented on Exiled.API/Features/Round.cs
> +        private static void UpdateTargetCounter()
This method is called once, why making it a method then?

2023-12-08 15:01 UTC, louis1706 commented on Exiled.API/Features/Round.cs
> +        }
```suggestion
```

2023-12-08 15:01 UTC, louis1706 commented on Exiled.API/Features/Round.cs
> +                UpdateTargetCounter();
```suggestion
            foreach (Player player in Player.List)
            {
                player.SendFakeSyncVar(RoundSummary.singleton.netIdentity, typeof(RoundSummary), nameof(RoundSummary.Network_chaosTargetCount), RoundSummary.singleton._chaosTargetCount + TargetOffset);
            }
```

2023-12-08 15:02 UTC, louis1706 commented on Exiled.API/Features/Round.cs
> +            }
```suggestion
                targetOffset = value;
                foreach (Player player in Player.List)
                {
                    player.SendFakeSyncVar(RoundSummary.singleton.netIdentity, typeof(RoundSummary), nameof(RoundSummary.Network_chaosTargetCount), RoundSummary.singleton._chaosTargetCount + TargetOffset);
                }
```

2024-02-03 19:03 UTC, merged