Fix ClearInventory
Exiled-Team/EXILED pull request #2140
Opened 2023-10-10 22:10 UTC by louis1706

2023-10-11 11:42 UTC, IRacle1 requested changes

2023-10-11 11:42 UTC, IRacle1 commented on Exiled.API/Features/Player.cs
> +        /// Clears all ammo of the inventory.
```suggestion
        /// Clears all ammo in the inventory.
```

2023-10-19 19:05 UTC, Thundermaker300 commented on Exiled.API/Features/Player.cs
> +        public void ClearItem(bool destroy = true)
```suggestion
        public void ClearItems(bool destroy = true)
```

2023-10-19 19:05 UTC, Thundermaker300 commented on Exiled.API/Features/Player.cs
> +            ClearItem(destroy);
```suggestion
            ClearItems(destroy);
```

2023-10-24 00:28 UTC, merged