Big PickupAPI changes (Breaking)
Exiled-Team/EXILED pull request #2147
Opened 2023-10-15 11:08 UTC by IRacle1

- Better property saving between items/pickups.projectiles (without IsLoaded)
 - Armor `MovementSpeedMultiplier` setter was removed due desync
 - Optimization in `CreatePickup` method + now it creates item with exactly same serial
 - Pickup::Spawn is non static now, i think this is more logical and understandable
 - `Player::AddItem` now has more overloads with `FirearmType` and attachments

2023-10-16 09:05 UTC, louis1706 requested changes

2023-10-16 09:05 UTC, louis1706 commented on Exiled.API/Features/Pickups/Pickup.cs
> -        }
this method can keep at Obsolete

2023-10-16 09:05 UTC, louis1706 commented on Exiled.API/Features/Pickups/Projectiles/Projectile.cs
> -        public static Projectile Spawn(Projectile pickup, Vector3 position, Quaternion rotation, bool shouldBeActive = true, Player previousOwner = null)
a copy of the Static method can be keep at Obsolete and call the new one

2023-10-16 09:05 UTC, louis1706 commented on Exiled.API/Features/Player.cs
> -        public Item AddItem(ItemType itemType, IEnumerable<AttachmentIdentifier> identifiers = null)
we can make a copy of this method at Obsolete to call the new one

2023-10-16 09:05 UTC, louis1706 commented on Exiled.API/Features/Player.cs
> -        public IEnumerable<Item> AddItem(ItemType itemType, int amount, IEnumerable<AttachmentIdentifier> identifiers)
we can make a copy of this method at Obsolete to call the new one

2023-10-16 09:05 UTC, louis1706 commented on Exiled.API/Features/Player.cs
> -        public IEnumerable<Item> AddItem(Dictionary<ItemType, IEnumerable<AttachmentIdentifier>> items)
we can make a copy of this method at Obsolete to call the new one

2023-10-16 09:05 UTC, louis1706 commented on Exiled.API/Features/Player.cs
> -
Make this Obsolete

2023-10-16 09:05 UTC, louis1706 commented on Exiled.Events/EventArgs/Map/ChangedIntoGrenadeEventArgs.cs
> -        public double FuseTime { get; set; }
We need to make this Obsolete

2023-10-16 09:10 UTC, louis1706 commented
this actually not a lot of Breaking change

2023-10-25 14:30 UTC, louis1706 approved these changes

2023-11-10 00:09 UTC, louis1706 approved these changes

2023-11-13 00:29 UTC, Misaka-ZeroTwo approved these changes

2023-11-13 00:42 UTC, Misaka-ZeroTwo approved these changes

2023-11-13 00:47 UTC, louis1706 approved these changes

2023-11-13 00:48 UTC, merged