Add WhiteList extension
Exiled-Team/EXILED pull request #2160
Opened 2023-10-21 12:12 UTC by ITeMbI4

This PR adds WhiteList extension to the Player

2023-10-21 19:00 UTC, VALERA771 reviewed
Why we can't just use File.AppendAllLines() or smth else

2023-10-21 19:41 UTC, louis1706 requested changes
Don't make Breaking Change please keep the previous method and just add the new one with new args

2023-10-21 22:01 UTC, VALERA771 approved these changes

2023-10-21 22:35 UTC, Thundermaker300 commented on Exiled.API/Features/Player.cs
> +        public static void PermanentlyAddReservedSlot(string userId) => ReservedSlots.Add(userId);
Maybe instead of a different method, we can add a `bool permanent` to `AddReservedSlot`?

2023-10-21 22:35 UTC, Thundermaker300 commented on Exiled.API/Features/Player.cs
> +        public static void PermanentlyAddReservedSlot(string userId) => ReservedSlots.Add(userId);
Oh, that was the original intention. Thanks, Yamato

2023-10-23 21:14 UTC, louis1706 approved these changes

2023-10-24 00:26 UTC, merged