feat(events): implement EventExceptionLogger to capture event exceptions
Exiled-Team/EXILED pull request #2183
Opened 2023-10-29 03:56 UTC by Nekonyx

No breaking changes.

I extracted error logging from `Exiled.Events.Features.Event.InvokeSafely()` into a separate public static class.

This can be useful for patching, logging errors not only to the console but also to services like Sentry, Hawk, DataDog, or any other destination of choice.

2023-10-29 09:30 UTC, IRacle1 approved these changes

2023-10-29 10:22 UTC, louis1706 commented
> No breaking changes.
> 
> I extracted error logging from `Exiled.Events.Features.Event.InvokeSafely()` into a separate public static class.
> 
> This can be useful for patching, logging errors not only to the console but also to services like Sentry, Hawk, DataDog, or any other destination of choice.

can you do the same PR but for DevBranch ? halloween branch will not be merged on DevBranch or MainBranch

2023-10-29 10:23 UTC, louis1706 requested changes
Config inside Exiled.Event for enabling or disabling logging

2023-10-29 11:04 UTC, Nekonyx commented
@louis1706 
> can you do the same PR but for DevBranch ? halloween branch will not be merged on DevBranch or MainBranch
Okay
> Config inside Exiled.Event for enabling or disabling logging
I don't think that it is a good idea to disable error logs in configs. Logging event errors in the console is very necessary for everyone, they will never be redundant.

2023-11-04 13:47 UTC, closed without merging

2023-11-04 13:48 UTC, Nekonyx commented
@louis1706 #2207