Add voicelines SCP-3114
Exiled-Team/EXILED pull request #2192
Opened 2023-10-30 18:56 UTC by Rysik5318

2023-10-30 19:46 UTC, IRacle1 requested changes

2023-10-30 19:46 UTC, IRacle1 commented on Exiled.Events/EventArgs/Scp3114/VoiceLinesEventArgs.cs
> +    public class VoiceLinesEventArgs : IScp3114Event
also should inherit `IDeniableEvent`

2023-10-30 19:46 UTC, IRacle1 commented on Exiled.Events/Patches/Events/Scp3114/VoiceLines.cs
> +    [EventPatch(typeof(Scp3114), nameof(Scp3114.TryUseBody))]
Fix those `EventPatch` attribute and docs

2023-11-06 18:22 UTC, louis1706 requested changes

2023-11-06 18:22 UTC, louis1706 commented on Exiled.API/Features/Player.cs
> +        public void DropItem(Item item, bool isThrown = false) => Inventory.UserCode_CmdDropItem__UInt16__Boolean(item.Serial, isThrown);
Okay just see a Null Check Needed for item

2023-11-07 00:04 UTC, louis1706 requested changes

2023-11-07 00:04 UTC, louis1706 commented on Exiled.API/Features/Player.cs
> +        public void DropItem(Item item, bool isThrown = false) => Inventory.UserCode_CmdDropItem__UInt16__Boolean(item.Serial, isThrown);
You missed the null check for item

2023-11-08 08:42 UTC, louis1706 approved these changes

2023-11-09 01:29 UTC, ALEXWARELLC commented
👍

2023-11-09 17:07 UTC, closed without merging