Added bool WasDisguised
Exiled-Team/EXILED pull request #2204
Opened 2023-11-03 00:52 UTC by NikkiGardiner1

This has been tested.

.wasDisguised is used a bit throughout the 3114-identity class. Which controls if he can/cannot attack, if he is able to remove his disguise, and activates/devastates voicelines for 3114

2023-11-04 23:58 UTC, Misaka-ZeroTwo commented
Please resolve merge conflict

2023-11-05 01:49 UTC, NikkiGardiner1 commented
> Please resolve merge conflict

Merge conflict resolved

2023-11-05 04:52 UTC, Misaka-ZeroTwo commented on Exiled.API/Features/Roles/Scp3114Role.cs
> +        halloween-2023
```suggestion

```

2023-11-05 04:52 UTC, Misaka-ZeroTwo commented on Exiled.API/Features/Roles/Scp3114Role.cs
> +        halloween-2023
You forgot this line

2023-11-05 17:27 UTC, NikkiGardiner1 commented
Should be good now, mb for missing it

2023-11-06 18:14 UTC, louis1706 requested changes
Some Verification

2023-11-06 18:14 UTC, louis1706 commented on Exiled.API/Features/Roles/Scp3114Role.cs
> +            set => Identity._wasDisguised = value;
Can you make sure than setter update with client (i actually thinks than it's don't and than it's will imediatelly be overided)

2023-11-10 22:55 UTC, closed without merging