Is it a flashlight?
Exiled-Team/EXILED pull request #2225
Opened 2023-11-11 09:25 UTC by VALERA771

2023-11-11 10:50 UTC, louis1706 commented
i don't thinks it's needed there no difference between FlashLight and Lantern

2023-11-11 10:58 UTC, VALERA771 commented
Yeah, but it's 2 separate items. I think we can create just a base class from which inhernits both flashlight and lantern

2023-11-11 11:44 UTC, louis1706 requested changes

2023-11-11 11:44 UTC, louis1706 commented on Exiled.API/Features/Items/Flashlight.cs
> +        /// <returns>A string containing Lantern-related data.</returns>
not a lantern but can be both

2023-11-11 11:51 UTC, louis1706 commented
> Yeah, but it's 2 separate items. I think we can create just a base class from which inhernits both flashlight and lantern

yeah that what i was thinking

2023-11-11 11:51 UTC, louis1706 commented on Exiled.API/Features/Items/Flashlight.cs
> +        /// Returns the Lantern in a human readable format.
same for this i would this you would seen it sorry

2023-11-11 11:51 UTC, VALERA771 commented
Breaking changes are allowed? Cuz I'm changing Base property type

2023-11-11 11:56 UTC, louis1706 commented
> Breaking changes are allowed? Cuz I'm changing Base property type

it's not a breaking change since it's already change inside Halloween also it's Base propperty it's should't break too mush

2023-11-11 11:57 UTC, louis1706 commented on Exiled.API/Features/Items/Flashlight.cs
> -        public bool Active
don't do this breaking change is not needed now

2023-11-11 11:58 UTC, louis1706 commented on Exiled.API/Features/Items/Flashlight.cs
> -        public bool Active
you could make it Obsolete if you want

2023-11-11 15:52 UTC, louis1706 commented on Exiled.API/Features/Items/Flashlight.cs
>          internal Flashlight()
add ItemType item argument to choose wish Item will be initialised

2023-11-11 16:10 UTC, VALERA771 commented
build go brrr

2023-11-12 17:46 UTC, louis1706 approved these changes

2023-11-12 17:47 UTC, merged