Fixed Event StartingRecallEventArgs's IsAllowed issue.
Exiled-Team/EXILED pull request #2226
Opened 2023-11-11 12:32 UTC by XKaguya

StartingRecallEventArgs's IsAllowed won't stop the event. Patch at RagdollAbilityBase could solve this.

2023-11-11 13:26 UTC, XKaguya commented
The part of `                // base.CurRagdoll
                new(OpCodes.Ldarg_1),
                new(OpCodes.Callvirt, PropertyGetter(typeof(RagdollAbilityBase<Scp049Role>), nameof(RagdollAbilityBase<Scp049Role>.CurRagdoll))),` currently will lead into crash , dont merge before if i can fix this bug.Another option is to give up acquiring Target players, although I know this is not realistic, lol

2023-11-11 15:49 UTC, louis1706 commented
this will also be call for Scp0492

2023-11-11 16:51 UTC, XKaguya commented
> this will also be call for Scp0492 'RagdollAbilityBase'

yes , that is what the arg used for.Actually it will be call by Scp3114, but to doing limits on the Player , then it can be avoided.

2023-11-11 17:32 UTC, XKaguya commented
The problem about previous patch's ```IsAllowed``` is not vailed is because NW using non-zero as error code.Meanwhile ```Transpiler``` can't modify the return value.
So the patch must use ```Prefix``` instead of ```Transpiler ```.
Things are all done now.This event can get ```Target```, ```Player```, ```Ragdoll``` and ```IsAllowed```.

2023-11-11 17:59 UTC, louis1706 commented
> IsAllowed

Transpiler can modify return value ???

2023-11-11 18:00 UTC, XKaguya commented
> > IsAllowed
> 
> Transpiler can modify return value ???

uh , letme try that lol , forget its just stack

2023-11-11 18:41 UTC, XKaguya commented
> > IsAllowed
> 
> Transpiler can modify return value ???

Alright. now i've rewritten as Transpiler.And tested.

2023-11-11 23:44 UTC, Misaka-ZeroTwo commented
Please target dev branch.

2023-11-12 01:43 UTC, Misaka-ZeroTwo requested changes

2023-11-12 01:43 UTC, Misaka-ZeroTwo commented on Exiled.Events/EventArgs/Scp049/StartingRecallEventArgs.cs
> +        public StartingRecallEventArgsMod(Player player, Ragdoll ragdoll, bool isAllowed = true)
```suggestion
        public StartingRecallEventArgs(Player player, Ragdoll ragdoll, bool isAllowed = true)
```

2023-11-12 04:38 UTC, XKaguya commented
> Please target dev branch.

OK I'll do it after i get up

2023-11-12 04:59 UTC, Misaka-ZeroTwo commented
You will need to create a separate PR to prevent conflicts.

2023-11-12 05:01 UTC, closed without merging