Add `Fake Appearance`
Exiled-Team/EXILED pull request #2242
Opened 2023-11-13 18:30 UTC by Vladislav-CS

2023-11-16 08:44 UTC, louis1706 requested changes

2023-11-16 08:44 UTC, louis1706 commented on Exiled.Events/Handlers/Internal/Round.cs
> +                fpcRole.FakeAppearance = null;
that not needed

2023-11-16 14:49 UTC, louis1706 commented on Exiled.Events/Handlers/Internal/Round.cs
> +                fpcRole.FakeAppearance = null;
```suggestion
```

2023-11-16 17:29 UTC, louis1706 approved these changes

2023-11-18 13:18 UTC, louis1706 requested changes

2023-11-18 13:18 UTC, louis1706 commented on Exiled.API/Features/Roles/FpcRole.cs
> +                    Owner.ChangeAppearance(value.Value);
How do you reset the value ?

2023-11-18 17:42 UTC, louis1706 approved these changes

2023-11-29 19:38 UTC, Misaka-ZeroTwo commented
@Vladislav-CS tested?

2024-02-03 19:27 UTC, closed without merging