Add ```ChangeItemOwner```
Exiled-Team/EXILED pull request #2249
Opened 2023-11-14 15:24 UTC by XKaguya

```ChangeOwner``` is a internal method.
Add ```ChangeItemOwner``` for a public one.

2023-11-14 18:14 UTC, XKaguya commented
The reference github action using seems not new enough lol. Compiled failed.

2023-11-29 19:56 UTC, Misaka-ZeroTwo commented
tested?

2023-12-05 22:08 UTC, NaoUnderscore requested changes

2023-12-05 22:08 UTC, NaoUnderscore commented on Exiled.API/Features/Items/Item.cs
> +        /// A public method to change the owner of the <see cref="Item"/>.
```suggestion
        /// Changes the owner of the <see cref="Item"/>.
```

2023-12-05 22:08 UTC, merged