Add Door EVent
Exiled-Team/EXILED pull request #2267
Opened 2023-11-16 18:58 UTC by Rysik5318

2023-11-16 19:50 UTC, Misaka-ZeroTwo commented on Exiled.Events/EventArgs/Door/DoorDamagingEventArgs.cs
> +        ///     Gets or sets a value indicating the damage received by the door
Docs in here is confusing, is it supposed to be the remaining HP of the door, or the damage amount?

2023-11-16 21:29 UTC, louis1706 requested changes
![image](https://github.com/Exiled-Team/EXILED/assets/66829532/b20aee69-1971-4ad1-9abd-f6b381605a9e)
DamagingDoor event already exist

2023-11-16 22:01 UTC, Rysik5318 commented
> ![image](https://user-images.githubusercontent.com/66829532/283601786-b20aee69-1971-4ad1-9abd-f6b381605a9e.png) DamagingDoor event already exist

Should we move this event to `Door'?

2023-11-17 08:33 UTC, VALERA771 commented
> > ![image](https://user-images.githubusercontent.com/66829532/283601786-b20aee69-1971-4ad1-9abd-f6b381605a9e.png) DamagingDoor event already exist
> 
> 
> 
> Should we move this event to `Door'?

That event patches the same method so I think you need to merge your events with that patch

2023-11-17 12:39 UTC, louis1706 commented
> > ![image](https://user-images.githubusercontent.com/66829532/283601786-b20aee69-1971-4ad1-9abd-f6b381605a9e.png) DamagingDoor event already exist
> 
> Should we move this event to `Door'?

don't make breaking change

2023-11-17 14:21 UTC, louis1706 commented on Exiled.Events/EventArgs/Door/DoorDamagingEventArgs.cs
> +        public float Hp { get; set; }
Health

2023-11-17 21:28 UTC, louis1706 requested changes
since there BreakingChange this PR will need to wait Exiled 9 (or remove breaking change)

2023-11-17 21:30 UTC, Rysik5318 commented
I'll wait for Exiled 9.

2023-11-17 21:34 UTC, louis1706 commented
> I'll wait for Exiled 9.

ok i would love than next update they would use DamageHandler with Door lol would be more logic xD

2023-11-17 21:35 UTC, Rysik5318 commented
xD

2024-02-04 21:15 UTC, louis1706 commented
I have fixed all the conflict

2024-05-14 22:29 UTC, louis1706 commented on Exiled.Events/Patches/Events/Map/ServerDamage.cs
> +                    __instance.RemainingHealth += Health;
```suggestion
```

2024-05-29 20:35 UTC, Misfiy commented on Exiled.Events/EventArgs/Map/DestroyedDoorEventArgs.cs
> +        public DestroyedDoorEventArgs(DoorVariant doorVariant)
Add DoorDamageType here too

2024-05-30 05:23 UTC, Misfiy commented on Exiled.Events/EventArgs/Map/DestroyingDoorEventArgs.cs
> +        public DestroyingDoorEventArgs(DoorVariant doorVariant, bool isAllowed = true)
Add DoorDamageType here too

2024-05-30 14:57 UTC, merged