who wrote this?
Exiled-Team/EXILED pull request #2298
Opened 2023-11-25 19:01 UTC by Artyomus1337

tested

2023-11-25 23:05 UTC, louis1706 requested changes
Can you fix the other documentation that is on the same file ? (Also it is possibly my fault)

2023-11-26 10:23 UTC, Artyomus1337 commented
yep

2023-11-26 10:49 UTC, Artyomus1337 commented
that's it

2023-11-26 12:12 UTC, louis1706 approved these changes

2023-11-29 19:41 UTC, merged