ValidatingVisibility Event
Exiled-Team/EXILED pull request #2299
Opened 2023-11-28 15:31 UTC by Misfiy

2023-11-28 20:10 UTC, Misaka-ZeroTwo reviewed
Fix build errors

2023-11-30 00:04 UTC, Misaka-ZeroTwo requested changes

2023-11-30 00:04 UTC, Misaka-ZeroTwo commented on Exiled.Events/EventArgs/Scp939/ValidatingVisibilityEventArgs.cs
> +    ///     Contains all information before SCP-939 plays a stolen player's voice.
Copy pasta docs moment

2023-11-30 00:04 UTC, Misaka-ZeroTwo commented on Exiled.Events/EventArgs/Scp939/ValidatingVisibilityEventArgs.cs
> +    public class ValidatingVisibilityEventArgs : IScp939Event, IDeniableEvent
Validating or validated?

2023-11-30 17:26 UTC, louis1706 approved these changes

2023-12-03 23:00 UTC, Misaka-ZeroTwo commented on Exiled.Events/EventArgs/Scp939/ValidatingVisibilityEventArgs.cs
> +    ///     Contains all information about players before being validated to SCP-939.
Validating doesn't sound intuitive to me.

2023-12-05 22:04 UTC, NaoUnderscore requested changes

2023-12-05 22:04 UTC, NaoUnderscore commented on Exiled.Events/Handlers/Scp939.cs
> +        /// Called when a players visibility is being validated.
```suggestion
        /// Called before validating visibility.
```

2023-12-05 22:04 UTC, NaoUnderscore commented on Exiled.Events/Handlers/Scp939.cs
> +        /// Invoked when checking visibility for players.
```suggestion
        /// Invoked before validating visibility.
```

2023-12-05 22:04 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/Scp939/ValidatingVisibilityEventArgs.cs
> +        ///    Gets or sets a value indicating whether or not SCP-939 is allowed to view the player.
```suggestion
        ///    Gets or sets a value indicating whether visibility can be validated.
```

2023-12-05 22:04 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/Scp939/ValidatingVisibilityEventArgs.cs
> +        ///     Gets the player being shown to SCP-939.
```suggestion
        ///     Gets the player who's being shown to SCP-939.
```

2023-12-05 22:05 UTC, merged