Adding event TogglingRadio(Player, RadioItem, bool, bool)
Exiled-Team/EXILED pull request #2329
Opened 2023-12-12 16:27 UTC by Rysik5318

2023-12-12 16:44 UTC, VALERA771 reviewed
Everything except this looks pretty good

2023-12-12 16:44 UTC, VALERA771 commented on Exiled.Events/EventArgs/Player/TogglingRadioEventArgs.cs
> +        ///     Gets or sets a value indicating whether new state of the radio.
Rewrite this pls

2023-12-12 16:44 UTC, VALERA771 commented on Exiled.Events/Patches/Events/Player/TogglingRadio.cs
> +                        b = __instance._rangeId = (byte)playerChangeRadioRangeEvent.Range;
I thnk `b` should be used somewhere after this

2023-12-12 16:44 UTC, VALERA771 commented on Exiled.Events/Patches/Events/Player/TogglingRadio.cs
> +                        if (__instance._enabled || __instance._battery <= 0f || !EventManager.ExecuteEvent(new PlayerRadioToggleEvent(__instance.Owner, __instance, true)))
Should be of dev boi but I think our events should be executed before NW's

2023-12-12 16:44 UTC, VALERA771 commented on Exiled.Events/Patches/Events/Player/TogglingRadio.cs
> +                        if (!__instance._enabled || !EventManager.ExecuteEvent(new PlayerRadioToggleEvent(__instance.Owner, __instance, false)))
Same as above

2023-12-13 08:15 UTC, louis1706 requested changes

2023-12-13 08:15 UTC, louis1706 commented on Exiled.Events/Patches/Events/Player/TogglingRadio.cs
> +        private static bool Prefix(RadioItem __instance, RadioMessages.RadioCommand command)
i will see if @BoltonDev  can make you the Transpiler also yeah ExiledEvent need to be call before NWEvent if it's deniable

2023-12-13 08:20 UTC, louis1706 commented
also always build test in Release and not Debug

2023-12-14 11:28 UTC, VALERA771 commented
Also iirc if you would use prefix like this, `ChangingRadioPreset` event won't call

2023-12-15 20:43 UTC, BoltonDev commented on Exiled.Events/Patches/Events/Player/TogglingRadio.cs
> +            LocalBuilder ev = generator.DeclareLocal(typeof(TogglingRadioEventArgs));
```suggestion
```
Can you remove this pls ? I forgot to remove it

2023-12-15 21:41 UTC, louis1706 approved these changes

2023-12-16 14:04 UTC, NaoUnderscore requested changes

2023-12-16 14:04 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/Player/TogglingRadioEventArgs.cs
> +    ///     Contains all information before toggling a radio.
```suggestion
    /// Contains all information before toggling a radio.
```

Remove all white spaces as they're useless and it's horrible.
Do that for all occurrences.

2023-12-17 23:20 UTC, louis1706 approved these changes

2023-12-18 10:32 UTC, BoltonDev commented on Exiled.Events/Patches/Events/Player/TogglingRadio.cs
> +                // TogglingRadioEventArgs ev = new TogglingRadioEventArgs(Player, Radio, bool);
```suggestion
                // TogglingRadioEventArgs ev = new TogglingRadioEventArgs(Player, RadioItem, bool, bool);
```
Error on my part here and in the other below

2023-12-18 10:33 UTC, BoltonDev commented on Exiled.Events/Patches/Events/Player/TogglingRadio.cs
> +                // TogglingRadioEventArgs ev = new TogglingRadioEventArgs(Player, Radio, bool);
```suggestion
                // TogglingRadioEventArgs ev = new TogglingRadioEventArgs(Player, RadioItem, bool, bool);
```
Error on my part here and in the other below

2023-12-18 11:06 UTC, merged