adding AddingObserver event and RemovingObserver event for Scp173
Exiled-Team/EXILED pull request #2376
Opened 2024-01-03 22:58 UTC by skyyt15

the adding observer is triggered when a user just saw scp 173. for example, if ev.IsAllowed is set to false and the user is the only one who can saw scp173, the peanut can keep moving (it will be not added in the Observers list)

an example when the ev.IsAllowed is set to false
![image](https://github.com/Exiled-Team/EXILED/assets/99112969/35454fc1-938a-4c89-bc63-deb0d4dbfbf1)

he RemovingObserver is the same as the AddingObserver event but there is no a IsAllowed parameter (it's weird in this situation) and it's trigger when the player no longer saw scp173.

special thanks to Bolton who help me to find stupid IL errors special thing to yamato: i have compil this xmas-2023 version in release build :trollface:

2024-01-03 23:20 UTC, BoltonDev commented on Exiled.Events/EventArgs/Scp173/AddingObserverEventArgs.cs
> +    public class AddingObserverEventArgs : IExiledEvent, IDeniableEvent
```suggestion
    public class AddingObserverEventArgs : IScp173Event, IDeniableEvent
```

2024-01-03 23:20 UTC, BoltonDev commented on Exiled.Events/EventArgs/Scp173/AddingObserverEventArgs.cs
> +    /// Contains all information before a players just saw scp 173 (useful for an UTR for example).
```suggestion
    /// Contains all information before a player sees scp 173.
```
Remove example and doc rework

2024-01-03 23:22 UTC, BoltonDev commented on Exiled.Events/EventArgs/Scp173/AddingObserverEventArgs.cs
> +        public Player Scp173 { get; }
```suggestion
        /// <summary>
        /// Gets the player who controlling SCP-173.
        /// </summary>
        public Player Player { get; }

        /// <inheritdoc/>
        public Scp173Role Scp173 { get; }
```

2024-01-03 23:23 UTC, BoltonDev commented on Exiled.Events/EventArgs/Scp173/AddingObserverEventArgs.cs
> +        }
```suggestion
        public AddingObserverEventArgs(Player player, Player target, bool isAllowed = true)
        {
            Player = player;
            Scp173 = player.Role.As<Scp173Role>();
            Target = target;
            IsAllowed = isAllowed;
        }
```

2024-01-03 23:24 UTC, BoltonDev commented on Exiled.Events/EventArgs/Scp173/AddingObserverEventArgs.cs
> +        /// Gets or Sets a value indicating whether or not the player trigger scp 173 (for exemple, if scp173 is alone with the Target, it's can keep moving).
```suggestion
        /// Gets or sets a value indicating whether or not the player triggers scp 173.
```
Remove example

2024-01-05 00:22 UTC, NaoUnderscore requested changes
Keep the transpilers on the same patch as you're patching the same method, and it could lead to some issues, it's more maintainable in a single patch instead.

2024-01-05 00:22 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/Scp173/AddingObserverEventArgs.cs
> +    /// Contains all information before a player sees scp 173.
```suggestion
    /// Contains all information before a player sees SCP-173.
```

2024-01-05 00:22 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/Scp173/AddingObserverEventArgs.cs
> +        /// <param name="player">
Keep all `<param>`'s on the same line

2024-01-05 00:22 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/Scp173/AddingObserverEventArgs.cs
> +        /// Gets the target who saw the scp 173.
```suggestion
        /// Gets the target who have just seen SCP-173.
```

2024-01-05 00:22 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/Scp173/AddingObserverEventArgs.cs
> +        /// Gets the player who controlling scp 173.
```suggestion
        /// Gets the player who's controlling SCP-173.
```

2024-01-05 00:22 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/Scp173/AddingObserverEventArgs.cs
> +        /// Gets or Sets a value indicating whether or not the player trigger scp 173.
```suggestion
        /// Gets or sets a value indicating whether the player can be added as an observer.
```

2024-01-05 00:22 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/Scp173/RemovingObserverEventArgs.cs
> +    /// Contains all information before a player no longer see scp 173.
```suggestion
    /// Contains all information after a player stops looking at SCP-173.
```

2024-01-05 00:22 UTC, NaoUnderscore commented on Exiled.Events/Patches/Events/Scp173/AddingObserver.cs
> +                    PropertyGetter(typeof(StandardSubroutine<Scp173Role>), nameof(StandardSubroutine<Scp173Role>.Owner))),
Keep it on the same line

2024-01-05 00:22 UTC, NaoUnderscore commented on Exiled.Events/Patches/Events/Scp173/AddingObserver.cs
> +            {
No braces

2024-01-05 00:22 UTC, NaoUnderscore commented on Exiled.Events/Handlers/Scp173.cs
> +        /// Invoked before a user saw scp 173.
```suggestion
        /// Invoked before a player starts looking at SCP-173.
```

2024-01-05 00:22 UTC, NaoUnderscore commented on Exiled.Events/Handlers/Scp173.cs
> +        /// Invoked when a user no longer saw scp 173.
```suggestion
        /// Invoked after a player stops looking at SCP-173.
```

2024-01-05 00:22 UTC, NaoUnderscore commented on Exiled.Events/Handlers/Scp173.cs
> +        /// Called before a user is saw scp 173.
```suggestion
        /// Called before a player starts looking at SCP-173.
```

2024-01-05 00:22 UTC, NaoUnderscore commented on Exiled.Events/Handlers/Scp173.cs
> +        /// Called when a user no longer saw scp 173.
```suggestion
        /// Called after a player stops looking at SCP-173.
```

2024-01-13 09:53 UTC, closed without merging

2024-01-13 09:54 UTC, skyyt15 commented
fuck