Added `CustomModules.API.Extensions` extensions and new `CustomRole::Spawn` overload
Exiled-Team/EXILED pull request #2378
Opened 2024-01-07 01:13 UTC by SmusiJarviss

2024-01-07 01:26 UTC, NaoUnderscore requested changes

2024-01-07 01:26 UTC, NaoUnderscore commented on Exiled.CustomModules/API/Features/CustomRoles/CustomRole.cs
> +        /// Spawns the specified player with the custom role identified by the provided name.
```suggestion
        /// Spawns the specified player with the custom role identified by the provided type.
```

2024-05-26 18:44 UTC, Misfiy commented
If this is no longer draft, mark it as ready for review

2024-07-01 14:47 UTC, ALEXWARELLC commented
Since no further additions/changes have been made to this PR, I'll assume it's dead and reopen it as a new PR.

2024-07-01 16:42 UTC, ALEXWARELLC commented
@NaoUnderscore Close PR

2024-07-01 17:05 UTC, closed without merging