adding AddingObserver event and RemovingObserver event for Scp173 (again)
Exiled-Team/EXILED pull request #2384
Opened 2024-01-13 10:06 UTC by skyyt15

the adding observer is triggered when a user just saw scp 173. for example, if ev.IsAllowed is set to false and the user is the only one who can saw scp173, the peanut can keep moving (it will be not added in the Observers list)

an example when the ev.IsAllowed is set to false
![image](https://github.com/Exiled-Team/EXILED/assets/99112969/35454fc1-938a-4c89-bc63-deb0d4dbfbf1)

he RemovingObserver is the same as the AddingObserver event but there is no a IsAllowed parameter (it's weird in this situation) and it's trigger when the player no longer saw scp173.

special thanks to Bolton who help me to find stupid IL errors
special thing to yamato: i have compile this version in release build :trollface:

edit: ho i forgot to tell: i have build all change and tested the events with a different plugin in my personnal server

2024-01-13 10:08 UTC, skyyt15 commented
i think it's good now

2024-01-14 05:35 UTC, NaoUnderscore requested changes
Maintain all `<param name=>`, and such things, on the same line.

2024-01-14 05:35 UTC, NaoUnderscore commented on Exiled.Events/Patches/Events/Scp173/Observers.cs
> +            newInstructions[index].WithLabels(returnLabel);
```suggestion
            newInstructions[index].labels.Add(returnLabel);
```

2024-01-14 05:35 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/Scp173/RemoveObserverEventArgs.cs
> +        /// Gets the player who controlling scp 173.
```suggestion
        /// Gets the player who's controlling SCP-173.
```

2024-01-14 05:35 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/Scp173/RemoveObserverEventArgs.cs
> +        /// Gets the target who no longer see the scp 173.
```suggestion
        /// Gets the target who no longer sees SCP-173.
```

2024-01-14 05:35 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/Scp173/AddingObserverEventArgs.cs
> +        /// Gets the player who's controlling scp 173.
```suggestion
        /// Gets the player who's controlling SCP-173.
```

2024-01-14 05:35 UTC, NaoUnderscore commented on Exiled.Events/EventArgs/Scp173/AddingObserverEventArgs.cs
> +        /// Gets the target who have just seen SCP-173.
```suggestion
        /// Gets the target who has looked at SCP-173.
```

2024-01-25 23:49 UTC, NaoUnderscore approved these changes

2024-02-03 18:25 UTC, NaoUnderscore commented
Fix build errors

2024-02-03 18:53 UTC, merged