Added `Scp3114::Slapped` Event
Exiled-Team/EXILED pull request #2449
Opened 2024-02-10 10:27 UTC by CatyFoxt

Added Scp3114 Slapped Event

2024-02-10 10:29 UTC, VALERA771 commented
We prefer to use Hurt method cuz it's more common and covering all such events. I don't really think that this is useful

2024-02-10 10:37 UTC, CatyFoxt commented
@VALERA771, I saw that Scp939 has a Clawed event. That is why i created this event. And it is for the helpful for new developers because it is much more spesific for just Slapping. Hurt method can contains all type of hurting that Scp3114 can do.

2024-02-10 13:49 UTC, VALERA771 commented
> @VALERA771, I saw that Scp939 has a Clawed event. That is why i created this event. And it is for the helpful for new developers because it is much more spesific for just Slapping. Hurt method can contains all type of hurting that Scp3114 can do.

Clawed event is also firied when you claws "air" (aka no target). As far as I can see, your event won't work like this

2024-02-10 13:51 UTC, CatyFoxt commented
@VALERA771, You are wrong the event i did is firing every time Scp3114 tries to Slap. This contains **air, targets and every slapping action.**

2024-02-10 13:52 UTC, VALERA771 commented
Okay, then yeah

2024-02-10 15:01 UTC, louis1706 requested changes

2024-02-10 15:01 UTC, louis1706 commented on Exiled.Events/Patches/Events/Scp3114/Slapped.cs
> +            newInstructions.InsertRange(0, new CodeInstruction[]
You call your Event Slapp**ed** but it's call before the DamagePlayer method is executed and so we cannot differentiate a player who have get it's damage or not

2024-02-10 15:05 UTC, louis1706 commented on Exiled.Events/Patches/Events/Scp3114/Slapped.cs
> +            newInstructions.InsertRange(0, new CodeInstruction[]
also it's do not contain a lot of information

2024-02-10 15:28 UTC, VALERA771 reviewed
Some doc suggestions to make them "more clawed"

2024-02-10 15:28 UTC, VALERA771 commented on Exiled.Events/EventArgs/Scp3114/SlappedEventArgs.cs
> +        /// </summary>
```suggestion
        /// <inheritdoc/>
```

2024-02-10 15:28 UTC, VALERA771 commented on Exiled.Events/Handlers/Scp3114.cs
> +        /// Invoked when SCP-3114 slaps a player.
```suggestion
        /// Invoked after SCP-3114 slaps a player.
```

2024-02-10 15:28 UTC, VALERA771 commented on Exiled.Events/Handlers/Scp3114.cs
> +        /// Called when slapped.
```suggestion
        /// Called after SCP-3114 slaps a player.
```

2024-02-10 15:31 UTC, CatyFoxt commented
@louis1706, I changed the index of the method and fixed the orders of the using lines.

2024-02-10 15:50 UTC, louis1706 commented
> @louis1706, I changed the index of the method and fixed the orders of the using lines.

i thinks this place would be better to put the code 
			SlappedEventArgs ev = new(Player.Get(Owner), _syncAttack);
			Handlers.Scp3114.OnSlapped(ev)

			float num = this._humeShield.CurValue + ev.HumeShieldReward;
			this._humeShield.CurValue = Mathf.Min(num, this._humeShield.MaxValue);

2024-02-10 15:51 UTC, louis1706 commented
you can use the const to take the HumeShield value

2024-05-10 20:49 UTC, NaoUnderscore requested changes

2024-05-10 20:49 UTC, NaoUnderscore commented on Exiled.Events/Patches/Events/Scp3114/Slapped.cs
> +                Log.Info($"{newInstructions[z].opcode} {newInstructions[z].operand} : {string.Join(", ", newInstructions[z].labels.Select(x => newInstructions.FindIndex(y => y.operand == (object)x)))
Remove debug lines

2024-05-15 20:27 UTC, merged