Update README-Русский.md
Exiled-Team/EXILED pull request #2459
Opened 2024-02-15 23:18 UTC by Banalny-Banan

At the moment, russian readme is completely outdated, and is poorly translated overall, so i rewrote it

2024-02-16 21:37 UTC, VALERA771 reviewed
Есть также претензии к знакам препинания в некоторых местах

2024-02-16 21:37 UTC, VALERA771 commented on Localization/README-Русский.md
> +При публикации ваших плагинов, обязательно следуйте этим правилам:
Публикации тут не самое подходящее слово, эти пункты необходимы для базовой работы любого плагина

2024-02-16 21:37 UTC, VALERA771 commented on Localization/README-Русский.md
> +- Если плагин поддерживает динамические обновления, убедитесь, что когда вы помещаете новую версию плагина в папку "Плагины", вы также удаляете старую версию из папки перед перезагрузкой EXILED, несо
Название папки лучше оставлять без перевода

2024-02-16 21:37 UTC, VALERA771 commented on Localization/README-Русский.md
> +Перевод сделал BanalnyBanan
👀

2024-02-17 16:45 UTC, louis1706 requested changes

2024-02-17 16:45 UTC, louis1706 commented on Localization/README-Русский.md
> +Перевод сделал BanalnyBanan
Remove the Deleted part

2024-02-18 18:27 UTC, Vladislav-CS commented
Yeah, because I made the translation, not you

2024-02-18 18:57 UTC, bladuk commented
It's a collaborative environment, so you should show respect to every single contributor who made their changes to this file.

2024-02-18 22:36 UTC, louis1706 commented
> > It's a collaborative environment, so you should show respect to every single contributor who made their changes to this file.
> 
> First i thought that theres supposed to be no "translated by" part
> Then @louis1706 added the guy who made previous version
> 
> Is it supposed to be like "Translated by BanalnyBanan. Previous version was made by Ficus-x with IRacle and Remuchi. Version before that one was...." ?

That will be good just don't remove the previous contributor

2024-02-23 21:24 UTC, Vladislav-CS commented on Localization/README-Русский.md
> +Все события EXILED реализованы при помощи Harmony, что означает, что для их работы не требуется прямое редактирование кода игры, что позволяет получить два уникальных преимущества:
Типо, ты просто по другому перевел текст немного по другому? В чем смысл этих изменений?

2024-02-23 21:24 UTC, Vladislav-CS commented on Localization/README-Русский.md
> +Настройки плагинов ***НЕ*** будут находится в файле ``config_gameplay.txt``, вместо этого они задаются в файле ``~/.config/EXILED/Configs/(ПортСервера)-config.yml`` (``%AppData%\EXILED\(ПортСервера)-
Не настройки, а конфиги (конфигурации)

2024-02-23 21:24 UTC, Vladislav-CS commented on Localization/README-Русский.md
> +При разработке ваших плагинов, обязательно следуйте этим правилам:
При разработке **ваших** плагинов?

2024-02-23 21:24 UTC, Vladislav-CS commented on Localization/README-Русский.md
> +Чтобы использовать MEC, вам нужно будет ссылаться на ``Assembly-CSharp-firstpass.dll`` из файлов сервера и включить ``using MEC;``.
Ссылаться? Включить ``Using MEC;``? Ты когда-то плагины писал?

2024-02-23 21:24 UTC, Vladislav-CS commented on Localization/README-Русский.md
> +Это также означает, что вы можете *обновить* плагины без полной перезагрузки сервера. Однако существует несколько рекомендаций, которым должен следовать разработчик плагина, чтобы это работало:
В чем прикол заменять слова синонимами?

2024-02-23 21:24 UTC, Vladislav-CS commented on Localization/README-Русский.md
> -Перевод сделал Ficus-x при помощи IRacle и Remuchi.
Не нужно убирать авторов перевода

2024-02-23 21:24 UTC, Vladislav-CS commented on Localization/README-Русский.md
> +Не каждый плагин обязан поддерживать динамические обновления. Если вы не собираетесь этого делать, то имеете на это полное право. Главное не изменяйте название сборки, когда создаете новую версию пла
Запятые покинули чат

2024-02-23 21:24 UTC, Vladislav-CS commented on Localization/README-Русский.md
> +- Если вы обновляете плагин, убедитесь, что его имя сборки (Не файла а сборки!) не совпадает с текущей версией, которую вы установили (если таковая имеется). Плагин должен быть собран разработчиком с
Запятая перед а?

2024-02-23 21:24 UTC, Vladislav-CS commented on Localization/README-Русский.md
> +Однако, некоторые плагины могут самостоятельно получать свои настройки из других мест, а это просто стандартное местоположение EXILED, поэтому проверяйте отдельный плагин, если возникнут проблемы.
Запятые в русском языке ставятся в соответствии пунктуационных правил, а не так, как они звучат в устной речи

2024-02-23 21:24 UTC, Vladislav-CS commented on Localization/README-Русский.md
> +Однако, некоторые плагины могут самостоятельно получать свои настройки из других мест, а это просто стандартное местоположение EXILED, поэтому проверяйте отдельный плагин, если возникнут проблемы.
Во многих местах ты выделил слова запятыми, когда этого делать не нужно

2024-05-18 08:42 UTC, Vladislav-CS commented
Since there is no feedback and all changes are really bad I'm gonna close it

2024-05-18 08:42 UTC, closed without merging