[API + Events] [Additions] More events + Role API
Exiled-Team/EXILED pull request #2483
Opened 2024-03-12 14:37 UTC by Misfiy

2024-03-12 15:55 UTC, Misfiy commented
> Can you also add `Scp079LostSignalHandler::_ghostlightLockoutDuration`?
Scp2176LostTime exists already for this, would you prefer a rename?

2024-03-12 15:57 UTC, VALERA771 commented
No, missed it

2024-03-12 15:57 UTC, Misfiy commented
Lemme know what else you want for other roles too :3

2024-03-24 14:29 UTC, louis1706 requested changes

2024-03-24 14:29 UTC, louis1706 commented on Exiled.API/Features/Roles/Scp079Role.cs
> -        }
Where is LockDoor ?

2024-04-06 17:12 UTC, merged