`[Exiled::Events]` Adding a list of all subscribed plugins' names
Exiled-Team/EXILED pull request #2569
Opened 2024-05-22 10:36 UTC by VALERA771

2024-05-22 10:45 UTC, VALERA771 commented
**TESTING NOTICE**
Tested only with Exiled.Events (so some formatting issues may be).

2024-05-22 11:49 UTC, ALEXWARELLC approved these changes
> **TESTING NOTICE** Tested only with Exiled.Events (so some formatting issues may be).

I'll be the judge of that.

Jk, I think everything looks alright. Others may nitpick though.

2024-05-22 15:08 UTC, Misfiy approved these changes

2024-05-22 15:45 UTC, Vladislav-CS requested changes

2024-05-22 15:45 UTC, Vladislav-CS commented on Exiled.Events/Commands/PluginManager/DisplaySubscribed.cs
> +    public class DisplaySubscribed : ICommand
Use `IPermissionCommand` 😄

2024-05-22 17:43 UTC, VALERA771 commented on Exiled.Events/Features/Event{T}.cs
> +            @event.subscribedPlugins.Add(Server.PluginAssemblies[Assembly.GetCallingAssembly()].Name);
It will change GetCallingAssembly (going to return Exiled.Events always)

2024-05-22 19:01 UTC, VALERA771 commented on Exiled.Events/Commands/PluginManager/DisplaySubscribed.cs
> +                handler = typeof(Patches).Assembly.GetTypes().Where(x => x.Namespace != null && x.Namespace.Contains("Exiled.Events.Handlers")).SelectMany(x => x.GetProperties()).FirstOrDefault(x =>
It is not used anywhere else

2024-05-23 10:19 UTC, Misfiy requested changes

2024-05-23 10:19 UTC, Misfiy commented on Exiled.Events/Commands/PluginManager/DisplaySubscribed.cs
> +    public class DisplaySubscribed : ICommand, IPermissionCommand
```suggestion
    public class DisplaySubscribed : IPermissionCommand
```

2024-05-23 10:24 UTC, Misfiy approved these changes

2024-05-24 07:39 UTC, louis1706 requested changes

2024-05-24 07:39 UTC, louis1706 commented on Exiled.Events/Features/Event.cs
> +        public IReadOnlyCollection<string> SubscribedPlugins => subscribedPlugins;
Return all subscribe Delegate instead of plugin name

2024-05-24 07:39 UTC, louis1706 commented on Exiled.Events/Features/Event{T}.cs
> +        public IReadOnlyCollection<string> SubscribedPlugins => subscribedPlugins;
Same as above

2024-06-01 15:24 UTC, Vladislav-CS commented
Until https://github.com/Exiled-Team/EXILED/pull/2590 is merged

2024-06-23 13:19 UTC, merged