[API] PrefabHelper
Exiled-Team/EXILED pull request #2584
Opened 2024-05-30 19:58 UTC by Misfiy

2024-05-30 22:23 UTC, VALERA771 commented
I've put requires testing cuz not sure that Network client will work on server :)

2024-05-31 18:02 UTC, BoltonDev approved these changes

2024-06-01 08:32 UTC, VALERA771 approved these changes

2024-06-01 08:34 UTC, VALERA771 commented
Maybe add spawn to game entity? Cuz I think all of them (or at least a lot) supports spawning via Network server

2024-06-01 13:35 UTC, BoltonDev commented
> Maybe add spawn to game entity? Cuz I think all of them (or at least a lot) supports spawning via Network server

This is not needed since there is already a method in PrefabHelper

2024-06-01 22:53 UTC, VALERA771 commented
> > Maybe add spawn to game entity? Cuz I think all of them (or at least a lot) supports spawning via Network server
> 
> 
> 
> This is not needed since there is already a method in PrefabHelper

But then method in controller should be removed as I think or just edits so it'll use that method

2024-06-02 17:20 UTC, VALERA771 approved these changes
Seems good but why we have spawn methods in workstation and generator?

2024-06-02 17:32 UTC, Misfiy commented
> Seems good but why we have spawn methods in workstation and generator?
Multiple others did, and I thought it would be useful to also easily getting a workstation + more easy to find

2024-06-02 20:53 UTC, Vladislav-CS requested changes

2024-06-02 20:53 UTC, Vladislav-CS commented on Exiled.API/Features/Generator.cs
> +        /// <returns>The Generator that was spawned.</returns>
```suggestion
        /// <returns>The <see cref="Generator"/> that was spawned.</returns>
```

2024-06-02 20:55 UTC, Vladislav-CS approved these changes

2024-06-02 20:57 UTC, merged