[API] IGamePermissionCommand
Exiled-Team/EXILED pull request #2586
Opened 2024-05-31 16:04 UTC by Misfiy

2024-05-31 16:29 UTC, Vladislav-CS requested changes

2024-05-31 16:29 UTC, Vladislav-CS commented on Exiled.API/Interfaces/IGamePermissionCommand.cs
> +    /// Represents an interface for commands with permissions.
```suggestion
    /// Represents an interface for commands with game permissions.
```

2024-05-31 16:29 UTC, Vladislav-CS commented on Exiled.API/Interfaces/IGamePermissionCommand.cs
> +        public PlayerPermissions Permission { get; }
Should be array

2024-05-31 17:19 UTC, Vladislav-CS requested changes

2024-05-31 17:19 UTC, Vladislav-CS commented on Exiled.API/Interfaces/IGamePermissionCommand.cs
> +        public PlayerPermissions[] Permission { get; }
```suggestion
        public PlayerPermissions[] Permissions { get; }
```

2024-05-31 17:19 UTC, Vladislav-CS commented on Exiled.Events/Patches/Generic/ProcessQuery.cs
> +            else if (command is IGamePermissionCommand gamePermissionCommand && !sender.CheckPermission(gamePermissionCommand.Permission))
```suggestion
            else if (command is IGamePermissionCommand gamePermissionCommand && !sender.CheckPermission(gamePermissionCommand.Permissions))
```

2024-05-31 17:19 UTC, Vladislav-CS commented on Exiled.Events/Patches/Generic/ProcessQuery.cs
> +                sender.RaReply($"{command.Command}#You do not have permissions to use this command. Required permission: PlayerPermissions.{gamePermissionCommand.Permission}", false, true, string.Emp
It won't display required permissions because it's an array, use something like `string.join(", ", permissions)

2024-05-31 19:15 UTC, Vladislav-CS approved these changes

2024-06-01 08:37 UTC, VALERA771 approved these changes

2024-06-01 08:40 UTC, merged