Collection extensions upd
Exiled-Team/EXILED pull request #2649
Opened 2024-06-27 21:37 UTC by Banalny-Banan

`Shuffle<T>(this IEnumerable<T> enumerable, int iterations = 1)` - added documentation for thrown exceptions & added an actual shuffle instead of infinite recursive call

`AddRange<T>(this IEnumerable<T> enumerable, IEnumerable<T> collection)` - before was calling `AddItem()` in a loop. (multiple `Concat()`s internaly). It wouldnt even work because `AddItem()` is a pure method. Now using one `Concat()`.

`AddRange<T>(this T[] array, IEnumerable<T> collection)` - same changes.

`AddRange<T>(this HashSet<T> hashset, IEnumerable<T> collection)` - before was calling `Add()` in a loop. Now using `UnionWith()`.

2024-06-28 05:20 UTC, ALEXWARELLC approved these changes

2024-06-28 09:31 UTC, VALERA771 commented on Exiled.API/Extensions/CollectionExtensions.cs
> +                for (int j = array.Length - 1; j > 0; j--)
```suggestion
                for (int j = array.Length - 1; j >= 0; j--)
```

2024-06-29 01:40 UTC, ALEXWARELLC commented
> Maybe we should add an "Instance" field to Plugin<> class instead of making all those GetPlugin() methods ? I remember it existing in the example plugin and assigned in OnEnabled() We could just do it in base class

Isn't this outside the scope of the PR?

2024-06-29 21:34 UTC, VALERA771 commented on Exiled.API/Extensions/CollectionExtensions.cs
> -        public static IEnumerable<T> Shuffle<T>(this IEnumerable<T> enumerable, int iterations = 1)
Please, leave here `IEnumerable<T>`

2024-06-30 02:26 UTC, Misfiy commented on Exiled.API/Extensions/CollectionExtensions.cs
> -            array.Shuffle(iterations);
I believe that would call the Array Shuffle not the exiled extension, could be wrong

2024-06-30 21:02 UTC, VALERA771 commented on Exiled.API/Extensions/CollectionExtensions.cs
> -            array.Shuffle(iterations);
There is a `CollectionExtensions::ShuffleList` method compitable with arrays

2024-06-30 21:32 UTC, VALERA771 requested changes
Use a Nw extension (ShuffleList)

2024-07-01 17:50 UTC, ALEXWARELLC commented on Exiled.API/Extensions/CollectionExtensions.cs
> -        public static IEnumerable<T> Shuffle<T>(this IEnumerable<T> enumerable, int iterations = 1)
What's the issue here?

2024-07-01 17:50 UTC, ALEXWARELLC commented on Exiled.API/Extensions/CollectionExtensions.cs
> -            array.Shuffle(iterations);
> There is a `CollectionExtensions::ShuffleList` method compitable with arrays

I don't think it's possible to use.

2024-07-01 18:09 UTC, ALEXWARELLC approved these changes
I'm ok with this

2024-07-01 19:39 UTC, VALERA771 commented
Okay. Now you need to target dev branch (read exiled announcements if any questions)

2024-07-03 10:31 UTC, VALERA771 approved these changes

2024-07-03 11:46 UTC, ALEXWARELLC approved these changes

2024-07-03 11:49 UTC, Misfiy approved these changes

2024-07-05 09:21 UTC, merged