added example translation
Exiled-Team/EXILED pull request #2683
Opened 2024-07-09 17:14 UTC by TagGodOnYT

i dont feel like this needs an explanation...

2024-07-09 17:21 UTC, louis1706 approved these changes

2024-07-10 05:14 UTC, ALEXWARELLC requested changes
Please add an example usage of the translation.

E.G: `Log.Info(Translation.ExampleTranslation);`

2024-07-10 16:10 UTC, louis1706 requested changes
Fix error

2024-07-11 06:51 UTC, TagGodOnYT reviewed
Fixed Documentation Error

2024-07-12 15:31 UTC, merged