CustomItemsUnhold & CustomItemsHolded
Exiled-Team/EXILED pull request #2685
Opened 2024-07-09 23:28 UTC by Banalny-Banan

Current name is a bad one, calling .ToHashSet() every time property is accessed is heavily unoptimized, as it basicaly calls HashSet.Add for every item

2024-07-10 05:29 UTC, ALEXWARELLC approved these changes

2024-07-10 09:08 UTC, Misfiy approved these changes

2024-07-10 15:34 UTC, VALERA771 commented on Exiled.CustomModules/API/Features/CustomItems/CustomItem.cs
> +        public static IEnumerable<Pickup> CustomPickups => PickupManager.Keys.ToHashSet();
I don't think that this is necessarily. Value will still be hash set so nothing will change

2024-07-10 16:08 UTC, louis1706 requested changes
take care of Valera request

2024-07-10 17:21 UTC, VALERA771 commented
Requested review from nao to make sure that making this hash set was intended or not

2024-07-12 15:30 UTC, NaoUnderscore requested changes

2024-07-12 19:36 UTC, merged