`[EXILED::API]` Adding SendFakeSceneLoading
Exiled-Team/EXILED pull request #2756
Opened 2024-07-27 08:17 UTC by NotZer0Two

Adds a new way to load scenes to the client from the server without any client mod, what i could document was in the server, its only present "Facility" but by using [AssetRipper](https://github.com/AssetRipper/AssetRipper) there 6 scenes in total removing the 2 (NewMainMenu and Facility) that we know there are in total other 4 scenes never seen

They are
**MainMenuRemastered**
Seems some rework or the old menu still semi-working
![20240727094850_1](https://github.com/user-attachments/assets/20fef1f6-d759-47b6-8a85-a9c689049e99)

**FastMenu**
Old menu for the server list
![20240727095117_1](https://github.com/user-attachments/assets/02062a2d-76a6-4295-8d18-9633169e4b27)

**PreLoader**
Is the loading menu
![20240727095343_1](https://github.com/user-attachments/assets/6266a01c-c13e-43a8-bb5e-c1085bd0e282)

**Loader**
Black menu before the actual main menu

2024-07-27 08:26 UTC, NotZer0Two commented
I've made SceneType for making sure people don't type it wrong or just don't softlock their client if they only want to explore but if in the future some of them are wrong or bugged people can use the first method with string to load or for newer scenes, i will still updated it

2024-07-27 08:48 UTC, ALEXWARELLC commented on Exiled.API/Enums/ScenesType.cs
> +        Loader,
English better please.

2024-07-27 08:55 UTC, NotZer0Two commented on Exiled.API/Enums/ScenesType.cs
> +        Loader,
Probably better than before

2024-07-27 12:27 UTC, VALERA771 commented
I have doubts about moving methods from `MirrorExtensions` to other classes

2024-07-27 14:52 UTC, NotZer0Two commented
Its something already done, i don't know why github imports old one pr i've made https://github.com/Exiled-Team/EXILED/pull/2731

2024-07-28 05:44 UTC, xNexusACS requested changes
Fix build conflicts

2024-08-09 00:02 UTC, merged

2024-08-11 08:40 UTC, 6hundred9 commented
cool