`[EXILED::API]` Adding SpawnMice
Exiled-Team/EXILED pull request #2765
Opened 2024-08-11 06:02 UTC by NotZer0Two

Spawns rats.

(What to you expect something incredible nope it just spawns rats)

2024-08-11 06:04 UTC, NotZer0Two commented
Credits goes to yamato for the original finding

2024-08-11 09:49 UTC, NotZer0Two commented
Im fixing the issue and i will post a bug fix

2024-08-11 09:56 UTC, NotZer0Two commented
The issues where that Mouse spawn could overflow and cause crash and optimized the method because was resource consuming

2024-08-11 14:38 UTC, NaoUnderscore requested changes

2024-08-11 14:38 UTC, NaoUnderscore commented on Exiled.API/Features/Map.cs
> +        /// Spawns a Mice inside the <see cref="RoomType.EzShelter"/>.
```suggestion
        /// Spawns mice inside the <see cref="RoomType.EzShelter"/>.
```

2024-08-11 14:38 UTC, NaoUnderscore commented on Exiled.API/Features/Map.cs
> +                new OverflowException($"The mice type are from 1 to {SqueakSpawner.mice.Length}");
```suggestion
                throw new OverflowException($"Mouse type must be between 1 and {SqueakSpawner.mice.Length}.");
```

2024-08-13 16:29 UTC, xNexusACS approved these changes

2024-08-14 16:28 UTC, merged