`[EXILED::API]` Adding MoveNetworkIdentityObject
Exiled-Team/EXILED pull request #2766
Opened 2024-08-11 06:21 UTC by NotZer0Two

Lets the user move NetworkIdentities it can be bugged for the current culling system, in theory you can move object with a radius of 500m (Very small) and that will let them load in, could be useful for moving objects that you don't want in the facility to spawn or for example the Bowl of Candy

2024-08-11 06:25 UTC, NotZer0Two commented
![image](https://github.com/user-attachments/assets/0a8e71ae-6625-4fa6-ac96-0a600ce7bb3a)

This is what you can do

2024-08-11 14:39 UTC, NaoUnderscore requested changes

2024-08-11 14:39 UTC, NaoUnderscore commented on Exiled.API/Features/Player.cs
> +        /// Moves object for the player.
```suggestion
        /// Moves an object for the player.
```

2024-08-11 14:39 UTC, NaoUnderscore commented on Exiled.API/Features/Server.cs
> +        /// Moves object for all the players.
```suggestion
        /// Moves an object for all players.
```

2024-08-14 16:28 UTC, NaoUnderscore commented
Fix conflicts

2024-08-18 09:15 UTC, Monaldcry7788 approved these changes

2024-08-20 22:24 UTC, xNexusACS approved these changes

2024-08-20 22:28 UTC, merged