Cleaning a little bit the example plugin
Exiled-Team/EXILED pull request #466
Opened 2021-03-21 18:18 UTC by xRoier

- Deleted the private constructor.
- Moved down ``base.OnEnabled()`` and ``base.OnDisabled()``.

2021-03-21 18:54 UTC, iRebbok requested changes
The private constructor used here to tell to Exiled to use one from a static property instead. Revert deletion.

2021-03-21 18:54 UTC, iRebbok commented on Exiled.Example/Example.cs
> -
Revert that like breaker. It looks better, you don't get confused in logs and method calls with a large number of logs.

2021-03-21 18:54 UTC, iRebbok commented on Exiled.Example/Example.cs
> +            base.OnEnabled();
Add a line breaker above that line.

2021-03-21 19:37 UTC, iRebbok approved these changes

2021-03-21 19:37 UTC, iRebbok commented
Ignore CI, it fails due to a certificate issue on www.exiled.host.

2021-03-22 00:29 UTC, iopietro approved these changes

2021-03-22 00:30 UTC, merged