Allow Handcuffing event.IsAllowed to override team checks.
Exiled-Team/EXILED pull request #484
Opened 2021-04-17 15:21 UTC by steven4547466

This update will have the Handcuffing event still be called regardless of the team checks. If the target is on the same team as the cuffer, `ev.IsAllowed` will default to false, but if set to `true`, the player will still be handcuffed. Other than that it works the exact same.

2021-04-18 08:15 UTC, iRebbok approved these changes

2021-04-18 23:07 UTC, iopietro requested changes

2021-04-18 23:07 UTC, iopietro commented on Exiled.Events/Patches/Events/Player/Handcuffing.cs
> +            // Search for the last "stloc.3".
```suggestion
            // Search for the last "ldloc.3".
```

2021-04-18 23:07 UTC, iopietro commented on Exiled.Events/Patches/Events/Player/Handcuffing.cs
> +            var offset = 1;
```suggestion
            var offset = 0;
```

2021-04-18 23:07 UTC, iopietro commented on Exiled.Events/Patches/Events/Player/Handcuffing.cs
> +            var index = newInstructions.FindLastIndex(instruction => instruction.opcode == OpCodes.Stloc_3) + offset;
```suggestion
            var index = newInstructions.FindLastIndex(instruction => instruction.opcode == OpCodes.Ldloc_3) + offset;
```

2021-04-19 00:05 UTC, iopietro approved these changes

2021-04-19 00:06 UTC, merged