Add Player:Ping
Exiled-Team/EXILED pull request #501
Opened 2021-05-24 03:18 UTC by green1052

add get player ping func

2021-05-25 14:12 UTC, joker-119 approved these changes
How was this not already a thing?

2021-05-25 14:15 UTC, joker-119 requested changes
Fix the build errors.

2021-05-25 19:54 UTC, BuildBoy12 commented
This should also be a property instead of a method.

2021-05-25 20:18 UTC, green1052 commented
like this?

```
public int Ping 
{

    get 
    {
        return LiteNetLib4MirrorServer.GetPing(Connection.connectionId);
    }

}

2021-05-26 00:12 UTC, BuildBoy12 commented
`public int Ping => LiteNetLib4MirrorServer.GetPing(Connection.connectionId)`; is identical to what you posted.

2021-05-26 01:03 UTC, green1052 commented
https://github.com/Exiled-Team/EXILED/pull/501/commits/136b395a705112cac352cf300d7855cf56f04d50 thx

2021-05-26 01:58 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        /// Get player ping.
```suggestion
        /// Gets player's ping.
```

2021-05-26 02:08 UTC, iopietro approved these changes

2021-05-26 02:18 UTC, iopietro commented
Like Joker said, fix build errors.

2021-05-26 19:34 UTC, BuildBoy12 approved these changes

2021-05-26 22:15 UTC, iopietro approved these changes

2021-05-28 00:50 UTC, merged