Add Player::ShowHitMarker Round::ProgressTime
Exiled-Team/EXILED pull request #504
Opened 2021-06-03 03:21 UTC by green1052

2021-06-13 06:54 UTC, PintTheDragon requested changes

2021-06-13 06:54 UTC, PintTheDragon commented on Exiled.API/Features/Player.cs
> +        /// Show HitMarker.
Change to `Show a HitMarker`.

2021-06-13 06:54 UTC, PintTheDragon commented on Exiled.API/Features/Round.cs
> +
What does this value actually mean? `Now - (Now - ElapsedTime)` will just end up being `ElapsedTime`, so this property seems redundant.

2021-06-13 07:40 UTC, Nekonyx commented on Exiled.API/Features/Player.cs
> +        public void ShowHitMarker() => ReferenceHub.GetComponent<Scp173PlayerScript>()?.TargetHitMarker(Connection);
`ReferenceHub.characterClassManager.Scp173`?

2021-06-18 23:14 UTC, iopietro approved these changes

2021-06-19 09:58 UTC, iRebbok requested changes

2021-06-19 09:58 UTC, iRebbok commented on Exiled.API/Features/Player.cs
> +        /// Show a HitMarker.
```suggestion
        /// Shows a HitMarker.
```

as following most of the documentation.

2021-06-24 01:50 UTC, BuildBoy12 approved these changes

2021-06-27 10:12 UTC, iRebbok approved these changes

2021-06-27 23:38 UTC, BuildBoy12 approved these changes

2021-06-30 15:52 UTC, merged