Allow custom items to be given to all players at once
Exiled-Team/EXILED pull request #510
Opened 2021-06-15 18:41 UTC by 0b10000

The title explains most of this PR. I also added a check to exclude giving cuffed players custom items.

2021-06-18 23:33 UTC, iopietro requested changes

2021-06-18 23:33 UTC, iopietro commented on Exiled.CustomItems/Commands/Give.cs
> +                response = "give [Custom item name/Custom item ID] [Nickname/PlayerID/UserID/*]";
```suggestion
                response = "give [Custom item name/Custom item ID] [Nickname/PlayerID/UserID/all/*]";
```

2021-06-18 23:33 UTC, iopietro commented on Exiled.CustomItems/Commands/Give.cs
> +                case "*":
```suggestion
                case "*":
                case "all":
```

2021-06-18 23:33 UTC, iopietro commented on Exiled.CustomItems/Commands/Give.cs
> +                    }
```suggestion
                    foreach (var player in eligiblePlayers)
                        item.Give(player);
```

2021-06-19 03:09 UTC, iopietro approved these changes

2021-06-19 10:02 UTC, iRebbok requested changes
Address those build errors.

2021-06-19 14:49 UTC, iRebbok approved these changes
Approb

2021-06-22 23:57 UTC, merged