Added SetPlayerRoom for tinybrain peaple
Exiled-Team/EXILED pull request #512
Opened 2021-06-18 21:29 UTC by Monaldcry7788

*Done with the phone, I may have been wrong*

2021-06-18 23:09 UTC, iopietro commented
Just add a setter to [Player::CurrentRoom](https://github.com/Exiled-Team/EXILED/blob/cd4b256834bb78fe4d1ce6f5d1a8fb2dbd2546ee/Exiled.API/Features/Player.cs#L810).

2021-06-19 09:56 UTC, iRebbok commented
> Just add a setter to [Player::CurrentRoom](https://github.com/Exiled-Team/EXILED/blob/cd4b256834bb78fe4d1ce6f5d1a8fb2dbd2546ee/Exiled.API/Features/Player.cs#L810).

It'll force devs to find an instance of `Room`, could a new property called `CurrentRoomType` or something be good to address this?

2021-06-19 13:04 UTC, Monaldcry7788 reviewed
Updated Player::CurrentRoom for sets the current player's room

2021-06-19 14:45 UTC, Remuchi commented
Setting player position to room.gameobject.position will not work properly for some rooms. For example, 939 chamber (you will spawn in air, fall down and die), 079 room (you spawn between walls), collapsed tunnels in entrance zone etc 
Don't know about surface

2021-06-22 23:33 UTC, iopietro commented
> It'll force devs to find an instance of Room, could a new property called CurrentRoomType or something be good to address this?
Yes, you're right, what do you think about having bot `CurrentRoom` and `CurrentRoomType`? 
In my opinion the first one could still be useful for devs who search for rooms directly from `Map.Rooms`.

> Setting player position to room.gameobject.position will not work properly for some rooms. For example, 939 chamber (you will spawn in air, fall down and die), 079 room (you spawn between walls), collapsed tunnels in entrance zone etc
Don't know about surface.

@Monaldcry7788 Because of that, you should use `PlayerMovementSync::FindSafePosition`, which is a base game method.

2021-06-23 06:22 UTC, iRebbok commented
> Yes, you're right, what do you think about having bot CurrentRoom and CurrentRoomType?
In my opinion the first one could still be useful for devs who search for rooms directly from Map.Rooms.

Sure!

2021-06-24 09:01 UTC, Monaldcry7788 commented
Updated

2021-06-25 00:45 UTC, 4310V343k commented
Chill, chill! It's only one line!

<details>
<summary></summary>

![](https://i.imgur.com/yyJwOpP.png)

</details>

2021-06-25 10:27 UTC, Monaldcry7788 commented
Removed white line at L1194

2021-06-30 15:55 UTC, joker-119 commented on Exiled.API/Features/Player.cs
> +                switch (value.Type)
There needs to be more problematic rooms added to this check, for example: 173's room, 079's room, 939's room, etc. You also need to take into account that these rooms can be facing 4 different directions along the x axis, Vector3.back may not always be the safest direction for a particular room.

2021-06-30 15:59 UTC, joker-119 requested changes
More rooms need to be added to the switch check, for ex, 173's room will put you in a wall, 079's put you inside the cage, 939's puts you in the middle of the air, etc.

Also you need to keep in mind that all rooms can be facing 4 different directions along the x axis, Vector3.back (negative z) may not always be the direction of 'safety', I'd recommend using the room's transform instead of the static Vector3

2021-08-02 06:35 UTC, closed without merging