Fixing the Coroutine example
Exiled-Team/EXILED pull request #545
Opened 2021-07-13 04:51 UTC by babyboucher

2021-07-13 05:13 UTC, Thundermaker300 commented
documentation commits 😳

2021-07-13 05:25 UTC, babyboucher commented
I tried to copy and paste it and got annoyed it was wrong

2021-07-13 12:42 UTC, Michal78900 commented on README.md
> -        yield return Timing.WaitForSecond(5f); //Tells the coroutine to wait 5 seconds before continuing, since this is at the end of the loop, it effectively stalls the loop from repeating for 5seco
`5 seconds.` instead `5seconds.`

2021-07-13 12:42 UTC, Michal78900 commented on README.md
> +        yield return Timing.WaitForSeconds(5f); //Tells the coroutine to wait 5 seconds before continuing, since this is at the end of the loop, it effectively stalls the loop from repeating for 5sec
Same as above

2021-07-13 12:42 UTC, Michal78900 commented on README.md
>      for(;;) //repeat the following infinitely
you can add space bettween `for` and `(`

2021-07-13 16:17 UTC, joker-119 approved these changes

2021-07-13 17:05 UTC, iopietro requested changes
Fix what @Michal78900 said and then it's fine.

2021-07-13 19:56 UTC, babyboucher commented
Done

2021-07-13 20:00 UTC, Michal78900 approved these changes

2021-07-16 15:42 UTC, iopietro approved these changes

2021-07-16 15:43 UTC, merged