Add GetValue() to UserGroupExtensions
Exiled-Team/EXILED pull request #550
Opened 2021-07-17 14:06 UTC by TheUltiOne

It didn't want to let me commit to my old PR so I had to remake this?

2021-07-17 15:25 UTC, iopietro requested changes
Fix build errors.

2021-07-17 17:47 UTC, TheUltiOne commented
> Fix build errors.
It _should_ be fixed.

2021-07-18 11:31 UTC, iopietro approved these changes

2021-07-18 12:57 UTC, TheUltiOne commented
fixed x2

2021-07-21 18:48 UTC, joker-119 approved these changes

2021-07-21 18:48 UTC, merged