Added some variants of Player.AddItem() method
Exiled-Team/EXILED pull request #551
Opened 2021-07-17 22:15 UTC by NaoUnderscore

Those're my extensions that I'm currently using to avoid filling the code with for / foreach loops.
May they be useful?

2021-07-17 22:25 UTC, NaoUnderscore commented
fuck autosave - "Create Player.cs"

2021-07-21 18:44 UTC, joker-119 requested changes

2021-07-21 18:44 UTC, joker-119 commented on Exiled.API/Features/Player.cs
> +                    Inventory.AddNewItem(itemType);
```suggestion
                for (int i = 0; i < items.Count; i++)
                    AddItem(items[i]);
```

There's no reason for us to use a foreach() with variable assignment here.

2021-07-21 18:44 UTC, joker-119 commented on Exiled.API/Features/Player.cs
> +                    Inventory.AddNewItem(item.id, item.durability, item.modSight, item.modBarrel, item.modOther);
```suggestion
                    AddItem(item);
```

2021-07-21 18:44 UTC, joker-119 commented on Exiled.API/Features/Player.cs
> +                    Inventory.AddNewItem(item.id, item.durability, item.modSight, item.modBarrel, item.modOther);
```suggestion
                for (int i = 0; i < items.Count; i++)
                    AddItem(items[i]);
```

2021-07-21 18:44 UTC, joker-119 commented on Exiled.API/Features/Player.cs
> +                    Inventory.AddNewItem(itemType);
```suggestion
                    AddItem(itemType);
```

2021-07-22 15:40 UTC, iopietro approved these changes

2021-07-26 13:34 UTC, joker-119 approved these changes

2021-07-26 13:34 UTC, merged