Added an "overrideMode" to both Player.Broadcast()
Exiled-Team/EXILED pull request #552
Opened 2021-07-17 22:43 UTC by NaoUnderscore

It's an optional parameter and it just clears player's broadcasts before sending the new one.
I'm just too lazy to ClearBroadcasts() and then send the new one.

2021-07-20 17:40 UTC, iopietro requested changes

2021-07-20 17:40 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        public void Broadcast(Broadcast broadcast, bool overrideMode = false)
```suggestion
        public void Broadcast(Broadcast broadcast, bool shouldClearPrevious = false)
```

2021-07-20 17:40 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        /// <param name="overrideMode">Clears the player's broadcast before sending the new one.</param>
```suggestion
        /// <param name="shouldClearPrevious">Clears all player's broadcasts before sending the new one.</param>
```

2021-07-20 17:40 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +            if (overrideMode) ClearBroadcasts();
```suggestion
            if (shouldClearPrevious) 
                ClearBroadcasts();

```

2021-07-20 17:40 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        /// <param name="overrideMode">Clears the player's broadcast before sending the new one.</param>
```suggestion
        /// <param name="shouldClearPrevious">Clears all player's broadcasts before sending the new one.</param>
```

2021-07-20 17:40 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +            if (overrideMode) ClearBroadcasts();
```suggestion
```

2021-07-20 17:40 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +                Broadcast(broadcast.Duration, broadcast.Content, broadcast.Type);
```suggestion
                Broadcast(broadcast.Duration, broadcast.Content, broadcast.Type, shouldClearPrevious);
```

2021-07-20 17:40 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        public void Broadcast(ushort duration, string message, global::Broadcast.BroadcastFlags type = global::Broadcast.BroadcastFlags.Normal, bool overrideMode = false)
```suggestion
        public void Broadcast(ushort duration, string message, global::Broadcast.BroadcastFlags type = global::Broadcast.BroadcastFlags.Normal, bool shouldClearPrevious = false)
```

2021-07-20 17:40 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        [Obsolete("Use Broadcast(Broadcast broadcast, bool overrideMode) instead.", false)]
```suggestion
        [Obsolete("Use Broadcast(Broadcast broadcast, bool shouldClearPrevious) instead.", true)]
```

2021-07-20 17:40 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        [Obsolete("Use Broadcast(ushort duration, string message, Broadcast.BroadcastFlags type, bool overrideMode) instead.", false)]
```suggestion
        [Obsolete("Use Broadcast(ushort duration, string message, Broadcast.BroadcastFlags type, bool shouldClearPrevious) instead.", true)]
```

2021-07-21 17:45 UTC, iopietro requested changes

2021-07-21 17:45 UTC, iopietro commented on Exiled.API/Features/Map.cs
> +                ClearBroadcasts();
```suggestion
```

2021-07-21 17:45 UTC, iopietro commented on Exiled.API/Features/Map.cs
> +                Server.Broadcast.RpcAddElement(broadcast.Content, broadcast.Duration, broadcast.Type);
```suggestion
                Broadcast(broadcast.Duration, broadcast.Content, broadcast.Type, shouldClearPrevious);
```

2021-07-21 22:27 UTC, iopietro requested changes
Fix build errors, make sure to always compile with the Release configuration before pushing your changes.

2021-07-22 15:45 UTC, iopietro approved these changes

2021-07-26 13:31 UTC, joker-119 approved these changes

2021-07-26 13:31 UTC, merged