Added Player.SetLevel() and edited Player::Level
Exiled-Team/EXILED pull request #558
Opened 2021-07-19 22:54 UTC by NaoUnderscore

2021-07-20 11:50 UTC, iopietro requested changes
Switch to dev branch

2021-07-20 11:52 UTC, NaoUnderscore commented
My bad, I was PR'ing too much and I didn't see that.

2021-07-20 17:22 UTC, iopietro requested changes

2021-07-20 17:22 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +                ReferenceHub.scp079PlayerScript.ForceLevel(value, false);
```suggestion
                ReferenceHub.scp079PlayerScript.ForceLevel(value, true);
```

2021-07-20 17:22 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        public void SetLevel(byte newLevel, bool displayMessage)
This method does the same thing as the `Level` property, except for `displayMessage`, it's almost like a duplicate, I don't think that's needed.

2021-07-21 18:15 UTC, joker-119 requested changes

2021-07-21 18:15 UTC, joker-119 commented on Exiled.API/Features/Player.cs
> +    using System.Collections.Generic;https://www.animeworld.tv/play/fumetsu-no-anata-e.tY9Ls/Tf-pb2
wtf is this?

2021-07-21 21:03 UTC, NaoUnderscore commented on Exiled.API/Features/Player.cs
> +    using System.Collections.Generic;https://www.animeworld.tv/play/fumetsu-no-anata-e.tY9Ls/Tf-pb2
Uhm.. Joker I'm sorry, really. lol

2021-07-21 22:21 UTC, PintTheDragon commented on Exiled.API/Features/Player.cs
> +    using System.Collections.Generic;https://www.animeworld.tv/play/fumetsu-no-anata-e.tY9Ls/Tf-pb2
animeworld.tv

2021-07-22 15:45 UTC, iopietro approved these changes

2021-07-26 13:24 UTC, joker-119 approved these changes

2021-07-26 13:24 UTC, merged