Added Player::IsVoiceChatting and Player::IsTransmitting
Exiled-Team/EXILED pull request #559
Opened 2021-07-21 07:34 UTC by NaoUnderscore

2021-07-21 18:21 UTC, joker-119 approved these changes

2021-07-22 13:41 UTC, iopietro commented on Exiled.API/Features/Player.cs
> +        public bool IsVoiceChatting => Player.GameObject.TryGetComponent(out Radio radio) && radio.isVoiceChatting;
Instead of getting it every time, it would be better to get and cache the `Radio` component inside the `Player` constructor.

2021-07-26 00:31 UTC, BuildBoy12 approved these changes

2021-07-26 00:32 UTC, BuildBoy12 requested changes
PR should not target master.

2021-07-26 04:58 UTC, NaoUnderscore commented
My bad 👍

2021-07-29 23:21 UTC, iopietro approved these changes

2021-07-29 23:23 UTC, merged