Added Player::NetworkIdentity
Exiled-Team/EXILED pull request #577
Opened 2021-08-12 22:07 UTC by NaoUnderscore

2021-08-13 06:18 UTC, PintTheDragon requested changes

2021-08-13 06:18 UTC, PintTheDragon commented on Exiled.API/Features/Player.cs
> +        /// Gets player's <see cref="NetworkIdentity"/>.
Change this to `Gets the player's`.

2021-08-13 18:41 UTC, PintTheDragon approved these changes
LGTM

2021-08-14 02:20 UTC, sanyae2439 approved these changes

2021-08-16 15:36 UTC, merged