Add method GetAllEffects
Exiled-Team/EXILED pull request #582
Opened 2021-08-17 03:07 UTC by RedRangerr

gets all enabled effects of the player.

2021-08-17 04:36 UTC, joker-119 requested changes

2021-08-17 04:36 UTC, joker-119 commented on Exiled.API/Features/Player.cs
> +            for (int i = 0; i < (int) EffectType.Visuals939; i++)
`for (int i = 0; i < Enum.GetValue(typeof(EffectType)).GetUpperBound(0); i++)` so we don't have to update this everytime a new effect type is added.

2021-08-17 04:36 UTC, joker-119 commented on Exiled.API/Features/Player.cs
> +        public List<PlayerEffect> GetAllEffects()
You should return a ReadOnlyCollection<PlayerEffect> instead, since people will be able to 'modify' this list but doing so results in nothing.

2021-08-18 01:18 UTC, PintTheDragon requested changes

2021-08-18 01:18 UTC, PintTheDragon commented on Exiled.API/Features/Player.cs
> +            return ActiveEffects;
Why not simply use `ReferenceHub.playerEffectsController.AllEffects`? I don't like the idea of getting the enum upper bounds constantly, then getting every effect twice.

2021-08-18 02:04 UTC, PintTheDragon requested changes

2021-08-18 02:04 UTC, PintTheDragon commented on Exiled.API/Features/Player.cs
> +                ActiveEffects.Add(GetEffect((EffectType)effect.Value));
The `GetEffect`s here are unnecessary. Please take a look at `GetEffect`'s definition.

2021-08-18 05:10 UTC, PintTheDragon requested changes

2021-08-18 05:10 UTC, PintTheDragon commented on Exiled.API/Features/Player.cs
> +                ActiveEffects.Add(effect.Value));
This won't compile. There's an extra closing parenthesis after each `effect.Value`.

2021-08-19 02:22 UTC, PintTheDragon requested changes

2021-08-19 02:22 UTC, PintTheDragon commented on Exiled.API/Features/Player.cs
> +
Stylecop will not be happy.

2021-08-19 02:31 UTC, RedRangerr commented on Exiled.API/Features/Player.cs
> +
i dont have any indentation issues.

2021-08-19 02:31 UTC, RedRangerr commented on Exiled.API/Features/Player.cs
> +
I don't have any indentation errors.

2021-08-19 05:55 UTC, joker-119 commented on Exiled.API/Features/Player.cs
> +
stylecop will not like this.

2021-08-20 05:05 UTC, PintTheDragon requested changes

2021-08-20 05:05 UTC, PintTheDragon commented on Exiled.API/Features/Player.cs
>      /// <summary>
There should be an empty line between the using and summary.

2021-08-20 19:03 UTC, joker-119 commented
Closing due to unready state and locking of dev branch in preparation for new game update.

2021-08-20 19:03 UTC, closed without merging