Added IsCHI
Exiled-Team/EXILED pull request #657
Opened 2021-08-29 16:31 UTC by babyboucher

Because it feels weird to have IsNTF and IsSCP but not one for CHI. Do this or remove IsNTF and just tell people to use Team

2021-08-29 23:17 UTC, joker-119 commented
Pull and merge from current dev branch before making PRs to prevent conflicts please.

2021-08-29 23:25 UTC, babyboucher commented
Done

2021-08-30 01:49 UTC, PintTheDragon requested changes

2021-08-30 01:49 UTC, PintTheDragon commented on Exiled.API/Features/Player.cs
> +        /// Gets a value indicating whether or not the player's <see cref="RoleType"/> is any Chaos rank.
Redundant "or not".

2021-08-30 05:03 UTC, merged