Room.LockDown and Room.UnlockAll
Exiled-Team/EXILED pull request #692
Opened 2021-09-02 22:41 UTC by babyboucher

2021-09-02 23:47 UTC, joker-119 requested changes
Since these methods affect ALL doors, these should be static.

2021-09-03 01:37 UTC, babyboucher commented
Done

2021-09-03 03:23 UTC, joker-119 requested changes

2021-09-03 03:23 UTC, joker-119 commented on Exiled.API/Features/Room.cs
> +        public static void LockDown(float duration, DoorLockType locktype = DoorLockType.Regular079)
static methods should be above non-static ones.

Also this should be renamed to LockAll() and the documentation changed to indicate that it affects all rooms.

2021-09-03 03:25 UTC, joker-119 commented
I'm actually a monke and thought this was in the Door class, not the Room class. I apologize, you were correct with the non-static methods.

2021-09-03 04:05 UTC, babyboucher commented
No problem

2021-09-03 04:10 UTC, joker-119 approved these changes

2021-09-03 06:24 UTC, PintTheDragon commented
Don't doors have a proper locking system? I feel like they should probably be used here.

2021-09-03 22:58 UTC, PintTheDragon commented
> 
> 
> > Don't doors have a proper locking system? I feel like they should probably be used here.
> 
> Yes, it's used by changing the DoorLockType property ??

I just think that there should be a way to undo a lockdown for your specific lock type, for when you want to undo the lock, and use the other method for when you want to ensure the door is open. Also, for plugins, I'd say that defaulting to the 079 locktype might not be the best.

2021-09-05 04:15 UTC, joker-119 commented
> > > Don't doors have a proper locking system? I feel like they should probably be used here.
> > 
> > 
> > Yes, it's used by changing the DoorLockType property ??
> 
> I just think that there should be a way to undo a lockdown for your specific lock type, for when you want to undo the lock, and use the other method for when you want to ensure the door is open. Also, for plugins, I'd say that defaulting to the 079 locktype might not be the best.

I still need to re-do the door lock system to properly use flags in exiled like they are in base-game, once done the code in the PR will need to be changed accordingly, but I will worry about that when the time comes, for now this is acceptable given the API's restrictions on the use of flags.

2021-09-05 09:28 UTC, merged