Added DroppingAmmo event
Exiled-Team/EXILED pull request #713
Opened 2021-09-09 20:36 UTC by DGvagabond

2021-09-09 23:34 UTC, PintTheDragon commented
What the fuck

2021-09-14 23:55 UTC, joker-119 requested changes
Fix:

`[2021-09-14 23:53:14.520 +00:00] [ERROR] [Exiled.Events] Patching by attributes failed!
HarmonyLib.HarmonyException: IL Compile Error ---> System.FormatException: Method System.Void InventorySystem.Inventory::UserCode_CmdDropAmmo(System.Byte ammoType, System.UInt16 amount) cannot be patched. Reason: Invalid IL code in (wrapper dynamic-method) InventorySystem.Inventory:InventorySystem.Inventory.UserCode_CmdDropAmmo_Patch0 (InventorySystem.Inventory,byte,uint16): IL_0017: newobj    0x00000007`

2021-09-17 18:35 UTC, BuildBoy12 requested changes
`HarmonyLib.HarmonyException: Patching exception in method System.Void InventorySystem.Inventory::UserCode_CmdDropAmmo(System.Byte ammoType, System.UInt16 amount) ---> System.FormatException: Method System.Void InventorySystem.Inventory::UserCode_CmdDropAmmo(System.Byte ammoType, System.UInt16 amount) cannot be patched. Reason: Invalid IL code in (wrapper dynamic-method) InventorySystem.Inventory:InventorySystem.Inventory.UserCode_CmdDropAmmo_Patch0 (InventorySystem.Inventory,byte,uint16): IL_002d: ret`

Fix^

2021-09-17 20:31 UTC, BuildBoy12 approved these changes

2021-09-21 01:15 UTC, merged