Add ev.Item to ProcessingHotketEventArgs
Exiled-Team/EXILED pull request #735
Opened 2021-09-22 02:10 UTC by steven4547466

2021-09-22 19:08 UTC, joker-119 commented on Exiled.Events/EventArgs/ProcessingHotkeyEventArgs.cs
> +        public Item Item { get; set;  }
The setter for this should check if the player actually possesses the item, and either throw an invalid operation error, or give them the item if they do not have it.

2021-09-22 19:09 UTC, joker-119 requested changes

2021-11-03 17:37 UTC, TheUltiOne commented
Did Nao ever make this? Can this be closed?

2021-11-04 00:52 UTC, NaoUnderscore commented
I didn't make it yet, because I was dealing with attachments.

2021-11-04 01:17 UTC, TheUltiOne commented
yeah but shouldnt this be closed as you're "cloning" this? since it will be a different PR.

2021-11-04 19:27 UTC, closed without merging