Fixed Player.Handcuff being broken (Issue #868)
Exiled-Team/EXILED pull request #869
Opened 2021-11-10 10:37 UTC by zhaguanyang

Tested

2021-11-10 10:37 UTC, zhaguanyang commented
#868

2021-11-10 12:28 UTC, Michal78900 commented on Exiled.API/Features/Player.cs
> +                Inventory.SetDisarmedStatus(cuffer.Inventory);
The `Cuffer` property setter already calls `Inventory.SetDisarmedStatus()`, so this is redundant.

2021-11-10 12:29 UTC, Michal78900 requested changes

2021-11-10 12:29 UTC, Michal78900 commented on Exiled.API/Features/Player.cs
> +                new DisarmedPlayersListMessage(DisarmedPlayers.Entries).SendToAuthenticated();
This should also be moved into `Cuffer`'s setter, so the entire thing will look like this.
```cs
if (value != null)
{
    Inventory.SetDisarmedStatus(value.Inventory);
    new DisarmedPlayersListMessage(DisarmedPlayers.Entries).SendToAuthenticated();
}

```

2021-11-10 13:01 UTC, Michal78900 approved these changes

2021-11-11 21:31 UTC, PintTheDragon approved these changes

2021-11-12 16:21 UTC, merged