Added Chance option for customroles
Exiled-Team/EXILED pull request #885
Opened 2021-11-17 13:51 UTC by Monaldcry7788

2021-11-17 14:45 UTC, joker-119 requested changes

2021-11-17 14:45 UTC, joker-119 commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +        public abstract float Chance { get; set; }
1. Breaking change, this should not be abstract.
2. Why would we include a spawn chance property in the first place, when we don't handle the spawning of custom roles ourselves?

2021-11-17 14:45 UTC, joker-119 commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +        protected virtual RoleType EscapeAsCuffed { get; set; }
This property is never used anywhere?

2021-11-17 14:45 UTC, joker-119 commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +        protected virtual RoleType EscapeAsUnCuffed { get; set; }
Same as above, if we're adding the ability to have custom escape mechanics for custom roles, we should add the logic to process them within EXILED.

2021-11-18 01:42 UTC, PintTheDragon requested changes
You also marked Joker's things as closed when they aren't fixed so there's also that

2021-11-18 01:42 UTC, PintTheDragon commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +        /// Gets or sets a value indicating the role when player escape as cuffed.
escapes while cuffed

2021-11-18 01:42 UTC, PintTheDragon commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +        /// Gets or sets a value indicating the role when player escape hasn't cuffed.
when the player escapes while not cuffed

2021-11-18 01:42 UTC, PintTheDragon commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +                if (Scale != Vector3.zero)
Scale should be Vector3.One by default.

2021-11-18 07:50 UTC, Marco15453 commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +                player.Scale = new Vector3(1, 1, 1);
Use `Vector3.One`

2021-11-18 12:09 UTC, zhaguanyang requested changes
Why are u adding properties without adding anything that uses them?

2021-11-18 15:12 UTC, Marco15453 requested changes

2021-11-18 15:12 UTC, Marco15453 commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +        protected virtual RoleType EscapeAsCuffed { get; set; }
This property is never used anywhere?

2021-11-18 15:12 UTC, Marco15453 commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +        protected virtual RoleType EscapeAsUnCuffed { get; set; }
Still the same as @joker-119 said it

2021-11-18 15:12 UTC, Marco15453 commented on Exiled.CustomRoles/API/Features/CustomRole.cs
> +            if (Scale != Vector3.zero)
The Default Scale for a player is 1 1 1 (Vector3.One)

2021-11-18 17:58 UTC, joker-119 commented
The unused escape related properties will be implemented by me after i accept this PR, btw.

2021-11-26 00:44 UTC, Marco15453 requested changes

2021-11-26 00:44 UTC, Marco15453 commented on Exiled.CustomRoles/API/Features/CustomRole.cs
>              if (Scale != Vector3.zero)
If you set this to Vector3.zero (0, 0, 0) it will always be true even when the player is in his normal size of Vector3.one (1, 1, 1)

2021-12-04 05:39 UTC, Marco15453 commented
Fix Build Issue

2021-12-04 17:59 UTC, Marco15453 requested changes
fix build issue

2022-01-08 13:18 UTC, closed without merging