Added `Candy` Feature
Exiled-Team/EXILED pull request #951
Opened 2021-12-16 19:07 UTC by Marco15453

Adds Candy Features for EXILED

2021-12-18 18:44 UTC, NaoUnderscore commented
This doesn't make sense. Just make a wrapper for the entire class instead.

2021-12-19 04:10 UTC, NaoUnderscore commented
Add an enum for CandyKindID or whatever is it.

2021-12-19 04:12 UTC, Marco15453 commented
> Add an enum for CandyKindID or whatever is it.

You mean like CandyType?

2021-12-19 04:26 UTC, NaoUnderscore requested changes
However, `Scp330Bag` is a `UsableItem`. So use Exiled's Item API, which is totally abstract.

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        public ReferenceHub Owner => Base.Owner;
We don't use `ReferenceHub` 😏

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        public int SelectedCandiesId => Base.SelectedCandyId;
Candi**es**?

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        public bool CandySelected => Base.IsCandySelected;
`IsCandySelected` was fine, why changing it?

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        /// Give an random Candy to the player.
Give**s**

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        /// Give an random Candy to the player.
**a** random

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        /// Give a specific Candy to the player.
Give**s**

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +    /// A Wrapper class for Scp-330.
I'd change it to `<see cref="Scp330Bag"/>`

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        public Transform Transform => Base.transform;
Since you're getting the Transform, you should add the Position/Rotation as well.

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        /// Gets the transform from the bag.
I'd change to `<see cref="GameObject.Transform"/>` or whatever is it.

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        /// Gets a value indicating whether the bag is allowed to be equipped.
I'd change to _Gets a value indicating whether the bag can be equipped_.

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        public bool AllowEquip => Base.AllowEquip;
I'd change it to `CanBeEquipped`.

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        /// Gets a value indicating whether the bag is allowed to be holstered.
I'd change to _Gets a value indicating whether the bag can be holstered_.

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        public bool AllowHolster => Base.AllowHolster;
I'd change to `CanBeHolstered`.

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        /// Gets the owner of the bag.
I'd change to _Gets the `<see cref="Player"/>` who owns the bag_.

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        /// Gets the owners inventory.
I'd change it to _Gets the `<see cref="Scp330.Owner"/>`s  `<see cref="Inventory"/>`_ or something like that.

2021-12-19 04:26 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        /// Gets the remaining cooldown from the bag.
I'd change it to _Gets the remaining cooldown of the bag_.

2021-12-19 04:29 UTC, NaoUnderscore commented
> > Add an enum for CandyKindID or whatever is it.
> 
> You mean like CandyType or what exactly you mean?

Yeah

2021-12-22 01:22 UTC, NaoUnderscore requested changes

2021-12-22 01:22 UTC, NaoUnderscore commented on Exiled.API/Features/Scp330.cs
> +        /// Give a random Candy to the player.
Give**s**

2021-12-24 20:34 UTC, joker-119 requested changes
TBH your entire Scp330 class needs to be removed as it already exists.

2021-12-24 20:34 UTC, joker-119 commented on Exiled.API/Features/Scp330.cs
> +// -----------------------------------------------------------------------
1. Item features belong in the Features/Items/ sub-directory
2. This item already exists in the API in Features/Items/Scp330.cs

2021-12-24 20:34 UTC, joker-119 commented on Exiled.API/Features/Scp330.cs
> +    public class Scp330
Item wrappers should inherit the Features/Items/Item class, or the most appropriate subclass (in this case, Usable)

2021-12-24 20:34 UTC, joker-119 commented on Exiled.API/Features/Scp330.cs
> +            Room = scp330Bag.GetComponentInParent<Room>();
Why would we specifically need the room it's in?

2021-12-24 20:34 UTC, joker-119 commented on Exiled.API/Features/Scp330.cs
> +        public Vector3 Position => Base.transform.position;
Why is this a get-only property?

2021-12-24 20:34 UTC, joker-119 commented on Exiled.API/Features/Scp330.cs
> +        public Quaternion Rotation => Base.transform.rotation;
Same as above

2021-12-24 20:34 UTC, joker-119 commented on Exiled.API/Features/Scp330.cs
> +        public bool CanBeEquipped => Base.AllowEquip;
More get-only properties for no reason

2021-12-24 20:34 UTC, joker-119 commented on Exiled.API/Features/Scp330.cs
> +        public List<CandyKindID> Candies => Base.Candies;
You made a Candy enum and aren't even using it??

2021-12-24 22:18 UTC, joker-119 commented
You have a mixture of properties here that makes no sense.
You have some properties/methods that only can bs used if the base is a Scp330Bag, which is what this class is a wrapper for, but then you also have properties for the Scp330Pickup class, such as position and rotation. 
It's clear you have no clue what you are doing here.

2021-12-24 22:18 UTC, closed without merging