Fix the FlickerableLightController == null
Exiled-Team/EXILED pull request #975
Opened 2022-01-01 19:26 UTC by louis1706

- Take more door (I can explain on discord) my english is too bad for write it
- not change Camera
- Always take FlickerableLightController

2022-01-02 13:41 UTC, Jesus-QC requested changes

2022-01-02 13:41 UTC, Jesus-QC commented on Exiled.API/Features/Room.cs
> +        private static void FindObjectInTheRoom(GameObject gameObject, out List<Camera079> cameraList, out List<Door> doors, out FlickerableLightController flickerableLightController)
FindObjectsInRoom

2022-01-02 13:41 UTC, Jesus-QC commented on Exiled.API/Features/Room.cs
> +                if (!(scp079Interactable == null))
!=

2022-01-03 18:54 UTC, Jesus-QC approved these changes

2022-01-03 22:16 UTC, BuildBoy12 requested changes

2022-01-03 22:16 UTC, BuildBoy12 commented on Exiled.API/Features/Room.cs
> +            return;
Return statement here is redundant

2022-01-06 09:30 UTC, merged